[#common_core_coffee-rest]
= coffee-rest
Modul célja a REST kommunikáció és a kezelése.

Tartalmazza az apache http klienst, különböző REST loggereket és filtereket. Továbbá a nyelvesítés, REST aktivátor és Response util osztály is itt található.

== BaseRestLogger
Az osztály célja, hogy loggolja az alkalmazásba érkező HTTP request-response kéréseket.
Aktiválása kézzel történik, projekt szinten a következő minta alapján:

.Projektben aktiválás
[source,java]
----
package hu.icellmobilsoft.project.common.rest.logger;

import javax.inject.Inject;
import javax.ws.rs.ext.Provider;

import hu.icellmobilsoft.coffee.cdi.logger.AppLogger;
import hu.icellmobilsoft.coffee.cdi.logger.ThisLogger;
import hu.icellmobilsoft.coffee.rest.log.BaseRestLogger;
import hu.icellmobilsoft.coffee.rest.log.LogConstants;

@Provider // <1>
public class RestLogger extends BaseRestLogger {

    @Inject
    @ThisLogger
    private AppLogger log;

    @Override
    public String sessionKey() { // <2>
        return LogConstants.LOG_SESSION_ID;
    }
}
----
<1> JAX-RS aktivátor (ez a lényeg ami aktiválja)
<2> HTTP headerben szereplő session azonosító kulcs neve

Maga a HTTP request-response log összeállításáról a `hu.icellmobilsoft.coffee.rest.log.RequestResponseLogger` osztály gondoskodik, és ha igény van rá ezt lehet felhasználni más helyzetekben is, például hiba esetén loggolásnál.

A request loggolása során az érzékeny adatok mind a header-ek közül, mind a json/xml body-ból maszkolásra kerülnek (pl. `X-PASSWORD: 1234` helyett `X_PASSWORD: +++*+++`).
Az adatokról a kulcsuk (header és JSON tartolmnál a kulcs, XML-nél a tag) alapján kerül megállapításra, hogy védendőek-e; ezek alapértelmezetten a `+++[\w\s]*?secret[\w\s]*?+++` vagy `+++[\w\s]*?pass[\w\s]*?+++` regexek-nek megfelelő kulcsok (pl. userPassword, secretToken, ...),
amennyiben a projekten szükséges, úgy a regex felülírható ha valamelyik *alapértelmezett* microprofile-config forrásban (sys var, env var, META-INF/microprofile-config.properties) megadjuk a `coffee.config.log.sensitive.key.pattern` konfigot, több pattern is megadható vesszővel elválasztva.

.Példa request log
[source,text]
----
2019-02-01 16:31:33.044 INFO  [thread:default task-1] [hu.icellmobilsoft.coffee.rest.log.BaseRestLogger] [sid:2G7XOSOJBCFRMW08] - * Server in-bound request
> POST http://localhost:8083/external/public/sampleService/sample/interface
> -- Path parameters:
> -- Query parameters:
> -- Header parameters:
> accept: text/xml;charset=utf-8
> Connection: keep-alive
> Content-Length: 106420
> content-type: text/xml;charset=utf-8
> Host: localhost:8083
> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_191)
> X-Client-Address: 10.10.20.49
> X-CustomerNumber: 10098990
> X-Password: *
> X-UserName: sample
> 
> entity: [<?xml version="1.0" encoding="UTF-8"?>
<SampleRequest xmlns="http://schemas.nav.gov.hu/OSA/1.0/api">
    <header>
        <requestId>RID314802331803</requestId>
        <timestamp>2019-02-01T15:31:32.432Z</timestamp>
        <requestVersion>1.1</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <passwordHash>*</passwordHash>
... // röviditve
----

.Példa response log
[source,text]
----
2019-02-01 16:31:34.042 INFO  [thread:default task-1] [hu.icellmobilsoft.coffee.rest.log.BaseRestLogger] [sid:2G7XOSOJBCFRMW08] - < Server response from [http://localhost:8083/external/public/sampleService/sample/interface]:
< Status: [200], [OK]
< Media type: [text/xml;charset=UTF-8]
< -- Header parameters:
< Content-Type: [text/xml;charset=UTF-8]
< entity: [{"transactionId":"2G7XOSYJ6VUEJJ09","header":{"requestId":"RID314802331803","timestamp":"2019-02-01T15:31:32.432Z","requestVersion":"1.1","headerVersion":"1.0"},"result":{"funcCode":"OK"},"software":{"softwareId":"123456789123456789","softwareName":"string","softwareOperation":"LOCAL_SOFTWARE","softwareMainVersion":"string","softwareDevName":"string","softwareDevContact":"string","softwareCountryCode":"HU","softwareDescription":"string"}]
----

[#common_core_coffee-rest_LogSpecifier]
== LogSpecifier
A REST logolás végpontonként testreszabható a `hu.icellmobilsoft.coffee.rest.log.annotation.LogSpecifier` annotációval,
ez egy helyen többször is megadható, valamint a scope-ja korlátozható a `target` mezőjével,
amiből több is megadható az annotációban (alapértelmezetten minden target-ra aktiválódik);
így megvan a lehetőség, hogy a REST request-response, microprofile-client request-response-okat külön-külön testreszabjuk.

IMPORTANT: Egy végponton `LogSpecifierTarget`-enként csak egy LogSpecifier szerepelhet.

.Megadható `target`-ek, a `hu.icellmobilsoft.coffee.rest.log.annotation.enumeration.LogSpecifierTarget` enum értékei:
|===
| LogSpecifierTarget | Scope

| `REQUEST` | REST végpont request-je

| `RESPONSE` | REST végpont response-a

| `CLIENT_REQUEST` | Microprofile REST Client végpont request-je

| `CLIENT_RESPONSE` | Microprofile REST Client végpont response-a
|===

Jelenleg a LogSpecifier a következő esetekre van felkészítve:

* a végponton a request-response logolása kikapcsolható a `LogSpecifier` annotáció `noLog` kapcsolójával.
* a végponton a kilogolt body méretét a `LogSpecifier` annotáció `maxEntityLogSize` mezőjével lehet korlátozni.

IMPORTANT: ha a `maxEntityLogSize` `LogSpecifier.NO_LOG`-tól *eltérő* értékre van állítva, akkor a REST endpoint-hoz érkező `application/octet-stream` mediaType esetében csak a kérés első 5000 karaktere íródik ki.

.LogSpecifier példa
[source,java]
----
    @POST
    @Produces({ MediaType.APPLICATION_JSON, MediaType.TEXT_XML, MediaType.APPLICATION_XML })
    @Consumes({ MediaType.APPLICATION_JSON, MediaType.TEXT_XML, MediaType.APPLICATION_XML })
    @LogSpecifier(target={LogSpecifierTarget.REQUEST, LogSpecifierTarget.CLIENT_REQUEST}, maxEntityLogSize =  100) //<1>
    @LogSpecifier(target=LogSpecifierTarget.RESPONSE, maxEntityLogSize =  5000) //<2>
    @LogSpecifier(target=LogSpecifierTarget.CLIENT_RESPONSE, noLog =  true) //<3>
    WithoutLogResponse postWithoutLog(WithoutLogRequest withoutLogRequest) throws BaseException;
----
<1> Request entity log méretét 100 byte-ra korlátozza, REST hívások és microprofile client használatánál is
<2> Response entity log méretét 5000 karakterre korlátozza a REST hívásoknál
<3> Kikapcsolja a response logolást microprofile rest client válaszoknál.

=== LogSpecifiersAnnotationProcessor

A `LogSpecifier`-hez tartozik a `hu.icellmobilsoft.coffee.rest.log.annotation.processing.LogSpecifiersAnnotationProcessor`,
ennek feladata, hogy a `LogSpecifier` többszöri definiálhatósága miatt ne lehessen ugyanarra a `target`-re több értéket is definiálni.
Ehhez fordítási időben ellenőrzi, hogy hány `@LogSpecifier` lett definiálva `LogSpecifierTarget`-enként, amennyiben többet talál úgy a fordítást buktatja.

.Invalid példa
[source,java]
----
    @POST
    @Produces({ MediaType.APPLICATION_JSON, MediaType.TEXT_XML, MediaType.APPLICATION_XML })
    @Consumes({ MediaType.APPLICATION_JSON, MediaType.TEXT_XML, MediaType.APPLICATION_XML })
    @LogSpecifier(maxEntityLogSize =  100) //<1>
    @LogSpecifier(target = LogSpecifierTarget.RESPONSE, maxEntityLogSize =  5000) //<2>
    ValidatorResponse postValidatorTest(ValidatorRequest validatorRequest) throws BaseException;
----
<1> Mivel nincs megadva target, ezért minden entity log méretét 100 byte-ra/karakterre korlátozza, beleértve a `LogSpecifierTarget.RESPONSE`-ét is.
<2> *LogSpecifierTarget.RESPONSE* entity log méretét 5000 karakterre korlátozza.

Mivel fenti példában a REST response mérete az első annotáció miatt 100, a második annotáció miatt pedig 5000 kellene legyen, így elkerülendő a rejtett logikát a `LogSpecifiersAnnotationProcessor` el fogja buktatni a fordítást az alábbi error-ral:

[source,log]
----
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project project-sample-service: Compilation failure
[ERROR] .../project-sample-service/src/main/java/hu/icellmobilsoft/project/sample/service/rest/ISampleTestRest.java:[43,23] Multiple LogSpecifiers are defined for the [RESPONSE] of [postValidatorTest]! Conflicting LogSpecifiers:[[@hu.icellmobilsoft.coffee.rest.log.annotation.LogSpecifier(noLog=false, maxEntityLogSize=100, target={REQUEST, RESPONSE, CLIENT_REQUEST, CLIENT_RESPONSE}), @hu.icellmobilsoft.coffee.rest.log.annotation.LogSpecifier(noLog=false, maxEntityLogSize=5000, target={RESPONSE})]]
----

[#common_core_coffee-rest_JaxbTool]
== JaxbTool
Az osztály célja hogy az XML objektummal kapcsolatos transzformációkat és kezeléseket foglalja össze.
A felépítése teljes mértékben moduláris, mindent projekt saját igényére tudja szabni a CDI segítségével.
A moduljai alapesetben ilyen működést biztosítanak:

=== Request verzió megállapítása
Ezt az `*IXmlRequestVersionReader*` interfész biztosítja.
Az implementáló beépített és cserélhető osztály: `hu.icellmobilsoft.coffee.rest.validation.xml.reader.XmlRequestVersionReader`.

Minta alapján a

[source,text]
----
 ...<header>...<requestVersion>1.1</requestVersion>...</header>...
----

XML struktúrából keresi, persze szabadon módosítható más struktúrára vagy akár HTTP header olvasásból.

=== XSD hiba gyűjtése
Marshal (DTO -> XML String) vagy unmarshal (XML String/Stream -> DTO) esetén kérhető a XSD szerinti ellenőrzés.
Ilyenkor `hu.icellmobilsoft.coffee.rest.validation.xml.exception.XsdProcessingException`
formában megkapjuk a XSD szabályokat sértő hibákat, listában.
Ezeket a hibákat a `*IXsdValidationErrorCollector*` interfész kezeli és biztosítja.

Az implementáló beépített és cserélhető osztály: `hu.icellmobilsoft.coffee.rest.validation.xml.error.XsdValidationErrorCollector`.

=== XSD (schema) fájlok kezelése
Az XSD schema leíró fájlok kezelésére plusz logika szükséges, mivel azokban különféle összekötés lehetséges.
Ezzel a problémával a `*IXsdResourceResolver*` interfész foglalkozik.

Az implementáló beépített és cserélhető osztály: `hu.icellmobilsoft.coffee.rest.validation.xml.utils.XsdResourceResolver`.
Olyan alap probléma hogy az XSD-k egymást importálják egy közös könyvtárban múködik alapból is,
de az hogy tudjunk importáljni XSD-t egy másik projektből, arra már extra logika szükséges.
Ebben az osztályban ez a helyzet van lekezelve.

== XSD Catalog schema kezelés
A <<howto_xsd_catalog, XSD Catalog és generálás>> részben található leírás foglalkozik az XSD generálással.
Ez a felyezet a kódban lévő aktiválását veszi célba - XML validálása XSD catalog segítségével.

Egész funkciót a <<common_core_coffee-rest_JaxbTool,JaxbTool>> osztály végzi.
Szándékosan olyan modulárisan van felépítve hogy könnyen lehessen igényekhez hajlítani.
A fenti leírás alapján a Coffee tartalmaz egy `*IXsdResourceResolver*` implementációt,
ami fel tudja olvasni az XSD Catalog-ban megadott séma struktúrát.
Ez az osztály a 

.hu.icellmobilsoft.coffee.rest.validation.catalog.PublicCatalogResolver
[source,java]
----
@Alternative
@Priority(100)
public class PublicCatalogResolver implements LSResourceResolver, IXsdResourceResolver {
----
Mivel az XSD Catalog generálásnál használunk maven által bekötött függőségeket, mint pl.:

./xxx/super.catalog.xsd
[source,xml]
----
...
<public publicId="http://common.dto.coffee.icellmobilsoft.hu/common" uri="maven:hu.icellmobilsoft.coffee.dto.xsd:coffee-dto-xsd:jar::!/xsd/hu.icellmobilsoft.coffee/dto/common/common.xsd"/>
...
----
Így fel kell készülni a `maven:` URI protokolhoz kezelésére.
Ez el is készült a `hu.icellmobilsoft.coffee.tool.protocol.handler.MavenURLHandler` osztályban,
amit aktiválni kell.
Ez megtörténhet több féle képpen, ajánlott megoldás a következő: 

.src/main/resources/META-INF/services/java.net.spi.URLStreamHandlerProvider
[source,txt]
----
hu.icellmobilsoft.coffee.rest.validation.catalog.MavenURLStreamHandlerProvider
----
Tehát létre kell hozni a `src/main/resources/META-INF/services/java.net.spi.URLStreamHandlerProvider` fájlt
és beleírni azt a class-t mely kezelésbe veszi (Coffee része).

WARNING: Lehetnek olyan rendszerek (pl. Thorntail),
melyek nem képesek ezt a fájlt beolvasni időben az alkalmazás felfutása idejében.
Ilyenkor van még egy lehetőségünk a `URL.setURLStreamHandlerFactory(factory);` megoldáson keresztül.

=== Catalog JaxbTool aktiválása
A `maven:` URI protokol kezelési beállítás után már csak 2 dolog van hátra:

* `PublicCatalogResolver` aktiválása
* catalog fájl megadása

A `PublicCatalogResolver` aktiválása klasszikus CDI módon történik:

.beans.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/beans_1_1.xsd"
    version="1.1" bean-discovery-mode="all">

    <alternatives>
        <class>hu.icellmobilsoft.coffee.rest.validation.catalog.PublicCatalogResolver</class>
    </alternatives>
</beans>
----

A catalog xsd fájl megadása pedig a konfiguráción keresztül történik, pontosabban a 

 coffee.config.xml.catalog.path

kulcs megdásával, íme egy példa:

.project-defaults.yml
[source,yml]
----
coffee:
    config:
        xml:
            catalog:
                path: xsd/hu/icellmobilsoft/project/dto/super.catalog.xml
----
Ezekután készen is vagyunk és XSD Catalog szerint fog történni a XSD séma felolvasás.

== Json támogatás

A keretrendszer támogatja a REST kommunikáció során a JSON formátumú üzeneteket is az XML mellett.
Ezen üzenetek szerializálására/deszerializálására egy külső modult használ, a Google által karbantartott https://github.com/google/gson[Gson]-t A keretrendszer kiegészíti/felüldefiniálja a Gson-t néhány saját adapterrel.
Alább látható egy példa JSON, és a saját hozzáadott adapterek.
Az idővel kapcsolatos értékeknél egy eset kivételével az ISO 8601 szabvány került alkalmazásra.
A ```Date``` osztály esetén a formátum az egyetemes UNIX epoch lett milliszekundumban

.example.json
[source,json]
----
{
    "date": 1549898614051,
    "xmlGregorianCalendar": "2019-02-11T15:23:34.051Z",
    "bytes": "dGVzdFN0cmluZw==",
    "string": "test1",
    "clazz": "hu.icellmobilsoft.coffee.tool.gson.JsonUtilTest",
    "offsetDateTime": "2019-02-11T15:23:34.051Z",
    "offsetTime": "15:23:34.051Z",
    "localDate": "2019-02-11",
    "duration": "P1Y1M1DT1H1M1S"
}
----

.Saját hozzáadott adapterek szerializálásának formátuma az egyes típusoknál
|===
| Java típus | Formátum

| `Class` | A ```Class.getName()``` metódusának visszatérési értéke.

| `XMLGregorianCalendar` | A ```XMLGregorianCalendar.toXMLFormat()``` metódusának visszatérési értéke.
Alapértelmezetten a ```XMLGregorianCalendarImpl``` az elérhető leszármazott ehhez az absztrakt osztályhoz.

| `Date` | Az 1970-01-01T00:00:00.000 óta eltelt időt adja meg milliszekundumban.

| `OffsetDateTime` | A ```DateTimeFormatter.ISO_OFFSET_DATE_TIME``` metódusának visszatérési értéke, ahol a zóna helyett offset kerül megjelölésre.
| `OffsetTime` | A ```DateTimeFormatter.ISO_OFFSET_TIME``` metódusának visszatérési értéke, ahol a zóna helyett offset kerül megjelölésre.
| `LocalDate` | A ```DateTimeFormatter.ISO_DATE``` metódusának visszatérési értéke.
| `Duration` | A ```javax.xml.datatype.Duration.toString()``` metódusának visszatérési értéke.
| `byte[]` | A ```Base64.getName().encodeToString()``` metódusának visszatérési értéke.
Alapértelmezett kódoló: RFC4648
|===

Megjegyzés: A JSON-höz köthető műveletek többsége util jellegű és publikusan elérhető a link:coffee-tool.adoc[coffee-tool] alatt a `JsonUtil` osztályban.


[#common_core_coffee-rest_OpenAPIFilter]
== OpenApiFilter
A Microprofile OpenApi lehetőséget biztosít az org.eclipse.microprofile.openapi.OASFilter interface implementációján keresztül további OpenApi configuráció beállításhoz.
A hu.icellmobilsoft.coffee.rest.filter.OpenAPIFilter implementáció a projekten belül tartalmazza a coffee hibakezeléséhez kapcsolódó általános hibakódokat és a hozzájuk tartozó response objektumoat, melyek a filteren kereszül minden végpontra általánosan rákerülnek, pontosabb dokumentációt adva a coffee-t használó microservice-ekben írt openapi.yml config fájlhoz képest, mivel dinamikusan töltődik ez az információ.

Ennek a filternek az aktiválásához configurációba meg kell adni az `mp.openapi.filter` configurációs kulcsban az  `hu.icellmobilsoft.coffee.rest.filter.OpenAPIFilter` értéket, ami az implementációt végző osztály.

Példa egy microprofile default properties configban:

.microprofile-default.properties
[source,properties]
----
mp.openapi.filter=hu.icellmobilsoft.coffee.rest.filter.OpenAPIFilter
----

=== Customizálhatóság
A megvalósítás tovább pontosítható, kiegészíthető leszármaztatással, amire egy példa:

.CustomerOpenAPIFilter
[source,java]
----
package hu.icellmobilsoft.test.rest.filter;

...

@Vetoed
public class CustomerOpenAPIFilter extends OpenAPIFilter {

    private static final String CUSTOM_999_RESPONSE = "#/components/schemas/Custom999Response";

    @Override
    protected Map<Integer, APIResponse> getCommonApiResponseByStatusCodeMap() { // <1>
        Map<Integer, APIResponse> apiResponseByStatusCodeMap = super.getCommonApiResponseByStatusCodeMap();
        APIResponse customApiResponse = OASFactory.createAPIResponse() //
                .content(OASFactory.createContent()
                        .addMediaType(MediaType.APPLICATION_JSON,
                                OASFactory.createMediaType().schema(OASFactory.createSchema().ref(CUSTOM_999_RESPONSE)))
                        .addMediaType(MediaType.APPLICATION_XML,
                                OASFactory.createMediaType().schema(OASFactory.createSchema().ref(CUSTOM_999_RESPONSE)))
                        .addMediaType(MediaType.TEXT_XML,
                                OASFactory.createMediaType().schema(OASFactory.createSchema().ref(CUSTOM_999_RESPONSE))))
                .description(Response.Status.BAD_REQUEST.getReasonPhrase() //
                        + "\n" + "* Custom 999 error" //
                        + "\n\t **resultCode** = *OPERATION_FAILED*" //
                );
        apiResponseByStatusCodeMap.put(999,customApiResponse );
        return apiResponseByStatusCodeMap;
    }

    @Override
    protected List<Parameter> getCommonRequestHeaderParameters() { //<2>
        Parameter xCustomHeader1 = OASFactory.createObject(Parameter.class).name("X-CUSTOM-HEADER-1").in(Parameter.In.HEADER).required(false)
                .description("Description of custom header 1").schema(OASFactory.createObject(Schema.class).type(Schema.SchemaType.STRING));
        Parameter xCustomHeader2 = OASFactory.createObject(Parameter.class).name("X-CUSTOM-HEADER-2").in(Parameter.In.HEADER).required(false)
                .description("Description of custom header 2").schema(OASFactory.createObject(Schema.class).type(Schema.SchemaType.STRING));
        List<Parameter> headerParams = new ArrayList();
        headerParams.add(xCustomHeader1);
        headerParams.add(xCustomHeader2);
        return headerParams;
    }
}
----
<1> Példa egy saját response válasz hozzáadása a 999es http státusz kóddal. Fontos megjegyezni hogy a Custom999Response-nak léteznie kell a DTO-k közt.
<2> Példa 2 darab saját header megadására leírással sémával.

és így a konfiguráció a következő hozzá:

.microprofile-default.properties
[source,properties]
----
mp.openapi.filter=hu.icellmobilsoft.test.rest.filter.CustomerOpenAPIFilter
----

== MessageBodyWriter

A modul tartalmaz `application/octet-stream` + `BaseResultType` writert.
Ennek köszönhetően octet-stream válaszban tudja küldeni a rendszer az esetleges
saját DTO BaseResultType objektumot.
Ez nagyon hasznos például a hibával elszált file generálásnál.

== ProjectStage

A modul tartalmaz egy Deltaspike által inspirált ProjectStage objektumot, melyet injectelni lehet.
Ennek szerepe, hogy meghatározható legyen felfutáskor configuráción keresztül megadva, hogy a projekt production állapotban fut, vagy development, esetleg teszt állapotban.

Használatához 2 konfiguráció megadásával van lehetőség:

* coffee.app.projectStage
* org.apache.deltaspike.ProjectStage

Megadható értékek konvertálódnak a `hu.icellmobilsoft.coffee.rest.projectstage.ProjectStageEnum` értékeire.
Minden enum érték tartalmazza, hogy mely config érték melyik enumot jelenti.

IMPORTANT: Fontos kiemelni, hogyha nincs megadva, vagy ha nem található a configurációs érték egyik enum név listájában, akkor PRODUCTION-ként viselkedeik a ProjectStage!

Configurációk az Microprofile Config segítségével megadhatók több helyről is, de csak a fent leírt sorrend szerint az elsőt fogja figyelembe venni.


