[#common_core_coffee-jpa]
= coffee-jpa

Modul célja a JPA bekötése.

Tartalmazza a deltaspike jpa és a hibernate bekötését.
Itt találhatók a lapozás segítő osztályok, tranzakció kezelési osztályok, és minden *Service őse, a BaseService osztály.

== TransactionHelper [[TransactionHelper]]

Segédmetódusokat tartalmaz *@Transactional* annotációval ellátva a *FunctionalInterfaces* osztályban deklarált *@FunctionalInterface*-ekhez.

Így lehetőségünk van arra, hogy ha egy osztály első belépési pontja nincs tranzakcióban, de azon belül szeretnénk tranzakcióban futtatni egy kód részletet, akkor elegendő a kívánt részt kiemelni egy *private* metódusba vagy bármilyen coffee által nyújtott *@FunctionalInterface*-be és meghívni a *TransactionHelper* megfelelő metódusát, ami elvégzi a tranzakcióban való futtatást.

Ezzel elkerüljük, hogy *@Transactional* annotációval ellátott *public* metódusba kelljen kiemelni a tranzakcióban futtatandó logikát és *CDI.current()*-en keresztül meghívni az osztályon belül elkészített metódust vagy ugyan ezt külön osztályba kiemelve elvégezni.

.TransactionHelper használati példa
[source,java]
----
import javax.enterprise.inject.Model;
import javax.inject.Inject;

import hu.icellmobilsoft.coffee.dto.exception.BaseException;
import hu.icellmobilsoft.coffee.dto.exception.TechnicalException;
import hu.icellmobilsoft.coffee.dto.exception.enums.CoffeeFaultType;
import hu.icellmobilsoft.coffee.jpa.helper.TransactionHelper;

@Model
public class TransactionHelperExample {

    @Inject
    private InvoiceService invoiceService;

    @Inject
    private TransactionHelper transactionHelper;

    public void example(Invoice invoice) throws BaseException {
        if (invoice == null) {
            throw new TechnicalException(CoffeeFaultType.WRONG_OR_MISSING_PARAMETERS, "invoice is NULL!");
        }

        // tranzakción kívüli műveletek
        // ...

        // tranzakcióban futó BaseExceptionFunction
        transactionHelper.executeWithTransaction(invoiceService::save, invoice);

        // tranzakcióban futó BaseExceptionRunner (pl.: void metódus esetén)
        transactionHelper.executeWithTransaction(() -> saveInvoice(invoice));

        // tranzakción kívüli műveletek
        // ...
    }

    private void saveInvoice(Invoice invoice) throws BaseException {
        invoiceService.save(invoice);
    }
}
----

== microprofile-health támogatás

A *DatabaseHealth* ellenőrizni tudja hogy elérhető-e az adatbázis.
A *DatabasePoolHealth* ellenőrizni tudja mennyire terhelt az adatbázishoz műveletekhez használt connection pool.

.Startup használati példa
[source,java]
----
@ApplicationScoped
public class DatabaseHealthCheck {
    @Inject
    private DatabaseHealth databaseHealth;
    public HealthCheckResponse checkDatabaseConnection() {
        DatabaseHealthResourceConfig config = new DatabaseHealthResourceConfig();
        config.setBuilderName("postgre");
        config.setDatasourceUrl("jdbc:postgresql://service-postgredb:5432/service_db?currentSchema=service");
        config.setDsName(DatabaseHealthConstant.Database.DEFAULT_DATASOURCE_NAME);
        try {
            return databaseHealth.checkDatabaseConnection(config);
        }catch (BaseException e) {
            // need to be careful with exceptions, because the probe check will fail if we don't handle the exception correctly
            return HealthCheckResponse.builder().name("postgre").up().build();
        }
    }
    
    @Produces
    @Startup
    public HealthCheck produceDataBaseCheck() {
        return this::checkDatabaseConnection;
    }
}
----

.Readiness használati példa
[source,java]
----
@ApplicationScoped
public class DatabaseHealthCheck {
    @Inject
    private DatabaseHealth databaseHealth;
    public HealthCheckResponse checkDatabasePoolUsage() {
        try {
            return databasePoolHealth.checkDatabasePoolUsage("oracle");
        }catch (BaseException e) {
            return HealthCheckResponse.builder().name("oracle").up().build();
        }
    }
    
    @Produces
    @Readiness
    public HealthCheck produceDataBasePoolCheck() {
        return this::checkDatabasePoolUsage;
    }
}
----
