[#common_module_coffee-module-csv]
= coffee-module-csv

The purpose of this module is to generate a CSV file from Java beans using binding annotations, or to create beans by parsing a CSV file.

Here is an example of bean annotation:
[source,java]
----
public class TestBean {

    @CsvBindByNamePosition(position = 0, column = "IDENTIFIER")
    private long id;

    @CsvBindByNamePosition(position = 4)
    private String name;

    @CsvBindByNamePosition(position = 2)
    private boolean active;

    @CsvDate("yyyy-MM-dd")
    @CsvBindByNamePosition(position = 3)
    private LocalDate creationDate;

    @CsvBindByNamePosition(position = 1)
    private Status status;

    // getters, setters...
}
----

The `@CsvBindByNamePosition` annotation provided by the module allows specifying the position and name of the CSV column.

You can convert a list of instances of such classes to CSV using the following call:
[source,java]
----
String csv = CsvUtil.toCsv(beans, TestBean.class);
----

The result of the above call would be:
[source,csv]
----
"IDENTIFIER";"STATUS";"ACTIVE";"CREATIONDATE";"NAME"
"11";"IN_PROGRESS";"true";"2021-11-23";"foo"
"12";"DONE";"false";"2020-01-02";"bar"
----

For reverse conversion, you can use the following call:
[source,java]
----
List<TestBean> beans = CsvUtil.toBean(csv, TestBean.class);
----

== Localization

To localize the values in fields, you need to specify a `LocalizationConverter` using annotations starting with `@CsvCustomBind`:

[source,java]
----
@CsvCustomBindByNamePosition(position = 0, converter = LocalizationConverter.class)
private Status status;

@CsvCustomBindByNamePosition(position = 1, converter = LocalizationConverter.class)
private boolean active;
----

TIP: If you want to localize custom types or change the localization logic for handled types, you can do so by inheriting from `LocalizationConverter`.

Next, you need to provide the localization for columns and the values associated with annotated fields
(e.g., in the `messages_hu.properties` file):

[source,properties]
----
java.lang.Boolean.TRUE=Igen
java.lang.Boolean.FALSE=Nem
hu.icellmobilsoft.coffee.module.csv.LocalizedTestBean.status=Státusz
hu.icellmobilsoft.coffee.module.csv.LocalizedTestBean.active=Aktív
hu.icellmobilsoft.coffee.module.csv.LocalizedTestBean$Status.IN_PROGRESS=Folyamatban
hu.icellmobilsoft.coffee.module.csv.LocalizedTestBean$Status.DONE=Kész
----

Finally, you need to call the `CsvUtil#toLocalizedCsv` method with the desired language:

[source,java]
----
String csv = CsvUtil.toLocalizedCsv(beans, TestBean.class, "hu");
----

The provided code examples would result in the following CSV:

[source,csv]
----
"STÁTUSZ";"AKTÍV"
"Folyamatban";"Igen"
"Kész";"Nem"
----