[#common_module_coffee-module-mp-opentracing]
= coffee-module-mp-opentracing

A modul célja a microprofile opentracing támogatása mely tartalmazza a következő alapelveket:

* Coffee kompatibilitás - lehetőséget biztosít hogy a coffee moduljai trace információkat szolgáltassanak. A benne lévő interceptor a coff:ee moduljait képes kezelni, továbbfejleszthető saját tagek bevezetésével, amik a coffee-cdi modulban találhatóak.
* Metrika és logolást egészíti ki a teljes observability érdekében.
* Jelenleg saját osztályokat használunk mivel nem lehet extension szinten jól kezelni azt hogy melyik komponens adjon trace információkat.

== microprofile-opentracing
Alapja a https://github.com/eclipse/microprofile-opentracing  valamint a
https://github.com/opentracing-contrib/java-interceptors  projekt.
Az `org.eclipse.microprofile.opentracing.Traced` annotáció helyett saját bindingot használunk, mivel így teljesen le tudjuk választani a moduljaink trace-elhetőségét.

== Core
Az extension-ben található bindingok szolgálnak arra hogy a modulok különböző technológiáit trace-elhetővé tegye.


=== OpenTraceInterceptor
Az interceptor azokat a metódusokat kezeli amik `hu.icellmobilsoft.coffee.cdi.trace.annotation.Traced`.
Ezt használja fel az `OpenTraceInterceptor`. Ezzel a megoldással később könnyen lehet cserélni/módosítani a trace interceptor működését.
Automatikusan kezeli a rest, redis, redis-stream, etcd, gRPC trace flow kezelését.

=== coffee-module-redis trace
Az `OpenTraceInterceptor` a `@Traced` annotációban kitöltött span értékekkel dolgozik. Ha az annotációban található `@Traced.component` értéke 'Jedis'
akkor az interceptor a functionName paramétert fogja alapul venni amiből meghatározza a span nevét, egyébként az annotált metódus osztaly neve lesz felhasználva. Ez az érték dönti el hogy a Jedis client művelet egy meglévő trace folyamba csatlakozzon be, ne kezdjen magától uj trace folyamatot. Ez a működés a `RedisManager`-en keresztül lett megvalósítva.

=== coffee-module-redisstream trace
Annotálva lett az `AbstractStreamConsumer.onStream` metódus valamint az `AbstractStreamPipeConsumer.onStream` metódus.
A `@Traced` annotáción keresztül megadott Tag értékekkel indít új trace folyamatot. Magába foglalja automatikusan az innen kimenő Rest hívásokat, és Jedis műveleteket. A span operáció neve az annotált metódust tartalmazó class neve lesz.

=== coffee-module-etcd trace
A `ConfigEtcdHandler` lett annotálva, az ebben lévő metódushívások adnak trace adatot.

=== coffee-grpc-opentracing-impl trace
Az `OpenTraceInterceptor` kezeli a gRPC-n keresztül jövő trace adatokat, összeköti a többi művelettel amik a trace részei. (redis, consumerek, rest).

=== coffee-deltaspike-data trace
Az `OpenTraceHandler` kezeli a repository rétegben lévő adatbázis műveletek trace flowba csatornázását.

=== OpenTraceErrorResponseFilter
Azok a rest operációk amik HTTP500, vagy magasabb hibakódot adnak, nem látszanak a trace-ben hibásnak.
Ez a filter kellene kezelje, de ez jelenleg exception alapú, ami a resten nem fog megtörténni.
https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/SpanFinishingFilter.java
A filter feladata hogy ezt az esetet lekezelje.


=== Thorntail alapú projekt konfig
Default a Jaeger trace implementációt használja.
https://docs.thorntail.io/2.5.0.Final/#_jaeger


.project-defaults.yml
[source,yaml]
----
thorntail:
    jaeger:
        service-name: ${service.name}
        sampler-type: const #There are 4 supported type: 'const', 'probabilistic', 'ratelimiting' and 'remote'.
        sampler-parameter: 1 #For a 'Constant' sampler 0 means no trace and 1 means all traces.
        remote-reporter-http-endpoint: 'http://jaeger-collector.istio-system:14268/api/traces'
----
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mp-opentracing</artifactId>
</dependency>
<dependency>
    <groupId>io.thorntail</groupId>
    <artifactId>microprofile-opentracing</artifactId>
</dependency>
<dependency>
    <groupId>io.thorntail</groupId>
    <artifactId>jaeger</artifactId>
</dependency>
----
=== Wildfly alapú projekt konfig
Default a Jaeger trace implementációt használja.
https://docs.wildfly.org/20/wildscribe/subsystem/microprofile-opentracing-smallrye/jaeger-tracer/index.html
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mp-opentracing</artifactId>
</dependency>
----