= v2.0.0 → v2.1.0

coff:ee v2.0.0 -> v2.1.0 migration description, news, changes

== What's new

THe gRPC support has been introduced. 
Thanks to this, a new subproject collector named `coffee-grpc` was created.

=== coffee-grpc
The following feature supports have been added to the system:

* `coffee-grpc-api`: General gRPC handling for the Coff:ee API, including annotations and versioning.
* `coffee-grpc-base`: Collector of protobuf and gRPC stubs for general usage.
* `coffee-grpc-protoc`: Support for generating classes from proto files.
* `coffee-dto/coffee-dto-xsd2proto`: Generated proto files generated from the `coffee-dto-xsd` XSD files.
* `coffee-dto/coffee-dto-stub-gen`: Generated classes from Coff:ee proto files.
* `coffee-grpc-server-extension` - Support for CDI gRPC server implementation.
* `coffee-grpc-client-extension` - Support for CDI gRPC client implementation.
* `coffee-grpc-traces-api` - Coffee tracing API (annotations...)
* `coffee-grpc-opentracing-impl` - gRPC https://github.com/eclipse/microprofile-opentracing[microprofile-opentracing] implementation

== Changes

* Bump com.google.guava:guava https://github.com/google/guava/releases/tag/v31.1[31.1-jre]
-> https://github.com/google/guava/releases/tag/v32.1.1[32.1.1-jre]
(https://github.com/advisories/GHSA-7g45-4rm6-3mm3[CVE-2023-2976])

=== coffee-module-etcd

** Bump io.etcd:jetcd-core 0.6.1 -> 0.7.5
** In case of multiple classloaders, the `DefaultEtcdConfigImpl` class was unable to find the values defined in the microprofile-config.properties file.

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-rest

* An `OptimisticLockException` has been introduced, with the default error code `CoffeeFaultType.OPTIMISTIC_LOCK_EXCEPTION`.
* The error handling in the `DefaultBaseExceptionMapper` class has been redesigned:
* Business error - for BusinessException, a status code of 422 is given instead of the previous 500 status codes.
* For a technical error - OptimisticLockException, a status code of 409 is given instead of the previous 500 status codes.
* `JsonMessageBodyReaderBase` uses the charset attribute coming in HTTP header `Content-Type` when deserializing the JSON request. Proper use of header: `Content-Type: application/json; charset=utf-8`. If charset is not specified the deserialization uses UTF-8 by default!

==== Migration

* To keep the exception status code handling as before, it is necessary to create a separate ExceptionMapper on projects.

=== coffee-module-mp-restclient

** The `DefaultBaseExceptionResponseExceptionMapper` sets the HTTP status code in the `RestClientResponseException` 

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-tool

** NPE fix in AnnotationUtil.getAnnotation(Class<?> clazz, Class<A> annotationClass) method 

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-jpa

** NoSuchMethodException fix in JPAUtil.toNativeSQL(NoEx) which has been caused by the hibernate 6.x upgrade.
** Possible integer-overflow fix in PagingUtil.getPagingResult* methods. XSD validation and some internal checks have been added. 

==== Migration

PagingUtil methods may throw BaseException from now on, which may need to be handled in the calling application. (though probably not necessary) 

The rest of changes are backwards compatible and doesnt need any migration.

=== BatchService

** Even the native insert/update methods (batchMergeNative, batchInsertNative, batchUpdateNative) take the insertable and updateable flags into account.

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-cdi

** The `hu.icellmobilsoft.coffee.cdi.trace.constants.Tags` has received new values for passing relational database trace data.
** New package for modularizing tracing operations, `hu.icellmobilsoft.coffee.cdi.trace.spi`
** `IOpenTraceHandler` Enables the integration of dynamic tracing implementation.
** `OpenTraceHandlerProducer` Provides the activated tracing module and gives default behavior if no tracing module is plugged in.

==== Migration

The changes do not result in any migration work, it is backwards compatible.

=== coffee-deltaspike-data

** The repository layer received dynamic trace handling, provided that the tracing module is active.

==== Migration

The changes do not result in any migration work, it is backwards compatible.

=== coffee-module-mp-opentracing

** `OpenTraceHandler` Facilitates the placement of modules into the trace flow where reliance on the existing OpenTraceInterceptor is not possible.

==== Migration

The changes do not result in any migration work, it is backwards compatible.

