= v2.7.0 → v2.8.0

coff:ee v2.7.0 -> v2.8.0 migration description, news, changes

== Global

=== coffee-jpa

💥 ***BREAKING CHANGE*** 💥

The `hu.icellmobilsoft.coffee.jpa.sql.batch.BatchService` has been deleted.

==== Migration

* Add the new `hu.icellmobilsoft.frappee:frappee-jpa-batch-api` module to the Maven dependencies.
* The `hu.icellmobilsoft.frappee.jpa.batch.IJpaBatchService` must be used instead of the former `BatchService`.
* The `HibernateBatchService` Hibernate specific implementation of the `IJpaBatchService` can be found in the
`hu.icellmobilsoft.frappee:frappee-hiberante-batch` module.
* The JakartaEE 10 producer of the `HibernateBatchService` can be found in the `frappee-hiberante-batch-jee10`
module.
* If the former `BatchService` is extended by your project the new `HibernateBatchService` must be extended and a new
producer must be created. For more information check the Frapp:EE documentation.

=== coffee-rest

* Support of multiple xml catalog file separated with `,`
* For marshalling, you can give `JaxbTool` multiple classes to add to `JAXBContext`

==== Migration

Changes are backwards compatible doesn't need any migration.
