= v2.3.0 → v2.4.0

coff:ee v2.3.0 -> v2.4.0 migration description, news, changes

=== coffee-rest
* *RequestResponseLogger memory tuning*: Based on the `BaseRestLogger` class an optimized version was created: <<common_core_coffee-rest_BaseRestLoggerOptimized,BaseRestLoggerOptimized>>. With its help applications use less memory while logging request and response bodies.
In addition, the `RequestResponseLoggerOptimized` class was created as well, where the request and response entity log limits are determined according to whether the request or response entity is `application/octet-stream` vagy `multipart/form-data` and the REST interface is not annotated with the LogSpecifier then we limit the log size.
Also, in this version, the `BYTECODE_MAX_LOG` constant has been renamed to `ENTITY_MAX_LOG`.

==== Migration

* When switching to `BaseRestLoggerOptimized`, it is advisable to switch to the `ENTITY_MAX_LOG` constant instead of `BYTECODE_MAX_LOG`, if it is used, as the former may be deprecated over time.
