= v2.5.0 → v2.6.0

coff:ee v2.5.0 -> v2.6.0 migration description, news, changes

== Global

💥 ***BREAKING CHANGE*** 💥
```
Global change that coffee-bom was used to import coffee dependency on projects. This has been changed to coffee-bom-project.

You then need to import the project elements as follows:

<dependencyManagement>
    <dependency>
        <groupId>hu.icellmobilsoft.coffee</groupId>
        <artifactId>coffee-bom-project</artifactId> <1>
        <version>${version.hu.icellmobilsoft.coffee}</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
</dependencyManagement>

This also means that the transitive dependencies that were previously put on projects from coffee-bom, are now removed.
Because of this, these dependencies will be reported as not found by maven, so they will need to be defined in the project using coffee.
```
<1> - coffee-bom -> changed to coffee-bom-project

* Bump hibernate-core https://github.com/hibernate/hibernate-orm/releases/tag/6.1.5[6.1.5.Final] -> https://github.com/hibernate/hibernate-orm/releases/tag/6.2.13[6.2.13.Final]

== Changes

=== coffee-jpa

==== BatchService

* Based on the Hibernate 6.2.x changes, the `Insert`, `Update` and `Delete` SQL statements have been updated.
* Since Hibernate 6.2.x, the EnumType is deprecated, because they are processing enum values differently, so the handling of the EnumType in `BatchService` has been deleted.
* Since Hibernate 6.2.x, the Byte[] and Character[] types mapping changed, which also affects `BatchService`.
See more: https://github.com/hibernate/hibernate-orm/blob/6.2/migration-guide.adoc#bytecharacter-mapping-changes[hibernate 6.2 migration guide]

==== Migration

* The Byte[] types were handled until now, but due to hibernate changes, one of the following is required:
** Replace Byte[] with byte[]
** For the old behavior, it is necessary to enable the legacy array processing in the `persistence.xml` with the following property: `<property name="hibernate.type.wrapper_array_handling" value="legacy"/>`

==== JpaUtil

** Since Hibernate 6.2.x, the `JdbcSelect` class was renamed to `JdbcOperationQuerySelect`, and the `getSql()` method used from it to  `getSqlString()`, so we updated the `JpaUtil` with these changes.

==== Migration

Changes are backwards compatible doesn't need any migration.

=== coffee-rest

==== Jsonb Config

Added the definition of the Jsonb configuration.

==== Migration

The changes do not result in migration work, backwards default values are set for correct usage.
