= v2.4.0 → v2.5.0

coff:ee v2.4.0 -> v2.5.0 migration description, news, changes

=== coffee-tool

* Added tool class for "AES/CBC/PKCS5PADDING" de/cipher
(`hu.icellmobilsoft.coffee.tool.utils.crypto.AesCbcCryptoUtil`)
* Added SHA3-512 message digest to `hu.icellmobilsoft.coffee.tool.utils.string.EncodeUtil` class,
deprecating old `Sha512(String str)`.
* In MavenURLHandler class, fix getting resource over class to current thread-based getting

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-module-redisstream

* The Redis consumers received functionality to assist graceful shutdown
(`hu.icellmobilsoft.coffee.module.redisstream.bootstrap.ConsumerLifeCycleManager`)

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-rest

* If version is not defined in the validateXMLs annotation, it won't attempt to read the requestVersion from the request body.

==== Migration

Changes are backwards compatible doesnt need any migration.

=== coffee-module-mongodb

* Removed classes and method annotated with `@Deprecated(forRemoval = true, since = "1.1.0")`
* Removed unimplemented and unused method: `hu.icellmobilsoft.coffee.module.mongodb.service.MongoService#getMongoCollection()`
==== Migration

* Instead of `hu.icellmobilsoft.coffee.module.mongodb.annotation.MongoConfiguration` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoClientConfiguration`
* Instead of `hu.icellmobilsoft.coffee.module.mongodb.config.MongoDbConfig` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoConfigHelper`
* Instead of `hu.icellmobilsoft.coffee.module.mongodb.config.MongoDbConfigImpl` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoClientConfiguration`
* Instead of `hu.icellmobilsoft.coffee.module.mongodb.handler.MongoDbHandler` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClient`
* Instead of `hu.icellmobilsoft.coffee.module.mongodb.producer.MongoFactory` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClientFactory`
* Instead of `hu.icellmobilsoft.coffee.module.mongodb.service.MongoServiceImpl` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClient`
* Instead of `hu.icellmobilsoft.coffee.module.mongodb.service.MongoService#getMongoCollection()` use: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClient#initRepositoryCollection(java.lang.String)`