= v2.10.0 → v2.11.0

coff:ee v2.10.0 -> v2.11.0 migration description, news, changes

* A new coffee-bom-grpc module has been added for maintaining grpc versions
* The coffee-grpc can be built on osx-aarch_64. (see documentation for some extra configuration)
* ETCD driver version bump to 0.8.5
* io.grpc version bump to 1.70.0
* com.google.protobuf version bump to 3.25.5
* commons-lang3 version bump 3.12.0 -> 3.15.0 
* commons-codec version bump 1.15 -> 1.17.1
* commons.io version bump 2.11.0 -> 2.16.1
* httpcomponents-httpclient version bump 4.5.13 -> 4.5.14 
* httpcomponents-httpcore version bump 4.4.15 -> 4.4.16 
* eclipse-yasson version bump 3.0.3 -> 3.0.4

=== coffee-tool
* GZipUtil got some new method for lower memory usage and direct DTO/JSON compression
* RandomSplitGenerator added
* JsonbUtil#getCustomClassInstance implementation changed, using Thread.currentThread().getContextClassLoader().loadClass instead of Class.forName
* DateUtil new functions: `daysBetweenLocalDates` and `tryToParseAbsoluteRelativeDate`
* A new AbstractEntityProcessorAction class has been added for common entity processing
* New abstract cache implementations: AbstractCache and AbstractLoadingCache
* New AbstractRedisStreamPipeConsumerExecutor and EventControlAction classes added to redisstream module

==== Migration
Changes are backwards compatible doesnt need any migration.

=== coffee-rest
* A new AbstractEvictAction class has been added to allow uniform invocation of classes implementing Evictable for cache clearing purposes
* System Rest Service (with ISystemRest interface) has been added with default endpoint /versionInfo

==== Migration
Changes are backwards compatible doesnt need any migration.
However, it's recommended to implement the coffee `ISystemRest` interface in the project's existing SystemRest service.

=== Hibernate version upgrade
Hibernate `6.2.13.Final` -> `6.6.1.Final` upgrade (Wildfly 34 support).

==== Migration
* https://docs.jboss.org/hibernate/orm/6.6/migration-guide/migration-guide.html[Hibernate 6.6 migration guide]
* Otherwise, no changes were made at coff:ee that would prevent the use of the previous hibernate version with a dependency exclude

=== coffee-module-etcd-extension

New Quarkus extension to support Quarkus native compatibility for the coffee-module-etcd module.
Description: <<common_coffee-quarkus-extensions-module-etcd, coffee-module-etcd-extension>>

=== coffee-tool-extension

New Quarkus extension to support Quarkus native compatibility for the coffee-tool module.
Description: <<common_coffee-quarkus-extensions-tool, coffee-tool-extension>>

=== coffee-module-redisstream

BaseRedisConsumerStarter update with thread checking and metrics data propagation with CDI async event

