= v2.12.0 → v2.13.0

coff:ee v2.12.0 -> v2.13.0 migration description, news, changes

=== coffee-module-redis

* Jedis upgraded from 5.1.2 to 7.2.1
* Replaced the deprecated `JedisPooled` and `JedisCluster` class

Notable bugfixes:

* Ensure closing connection in Pipeline even if there is an error in sync method. https://github.com/redis/jedis/pull/3865[#3865]

Jedis changelog with breaking changes:

* https://github.com/redis/jedis/releases/tag/v5.2.0[v5.2.0]
** JedisConnectionException contains HostAndPort from DefaultJedisSocketFactory (#3896)
** Address change in JSON.GET command without path (#3858)
** Modify and fail-fast GeoSearchParam (#3827)
** Support transaction from UnifiedJedis without calling multi first (#3804)
** Reduce the log level of validateObject to WARN (#3750)
* https://github.com/redis/jedis/releases/tag/v6.0.0[v6.0.0]
** Make default client side search dialect to 2 (#4060)
** Remove Graph module support (#4073)
** Change FT.PROFILE to return generic object (#4067)
** Remove Triggers and Functions feature (#3969)
** COMMAND INFO reply contains subcommand detail (#4022)
* https://github.com/redis/jedis/releases/tag/v6.1.0[v6.1.0]
* https://github.com/redis/jedis/releases/tag/v6.2.0[v6.2.0]
* https://github.com/redis/jedis/releases/tag/v7.0.0[v7.0.0]
** Removed deprecated constructors, classes, and JedisSharding (#4311)
** Automatic Failover and Failback API changes (#4317, #4310, #4308, #4306, #4297, #4228)
** MultiCluster* classes and methods have been renamed and improved.
** Users upgrading from v6.x should consult the Automatic Failover and Failback Migration Guide.
** https://redis.github.io/jedis/migration-guides/v6-to-v7/#breaking-changes[More details on breaking changes]
* https://github.com/redis/jedis/releases/tag/v7.1.0[v7.1.0]
* https://github.com/redis/jedis/releases/tag/v7.2.0[v7.2.0]
* https://github.com/redis/jedis/releases/tag/v7.2.1[v7.2.1]

==== Migration

* Address the jedis changelog breaking changes. Other migration steps not needed.

=== new config-watcher module

* Introduced a config source with file watcher. See doc: xref:#common_module_coffee-module-config-watcher[]

==== Migration
The changes are backwards compatible and do not require any migration.

=== coffee-module-mongodb

* MongoDB Java Driver (mongodb-driver-sync) upgraded from 4.5.1 to 5.5.2

Notable changes:

* `BsonDecimal128.isNumber()` now returns `true` and `BsonDecimal128.asNumber()` returns the equivalent `BsonNumber` (since v5.0).
* `ClusterSettings` computes `ClusterConnectionMode` consistently using the replica set name regardless of how it is configured (since v5.0).
* Dropped server support for MongoDB 3.4 and earlier (since v4.8), MongoDB 3.6 (since v5.2), and MongoDB 4.0 (since v5.5).

MongoDB Java Driver changelog with breaking changes:

* https://github.com/mongodb/mongo-java-driver/releases/tag/r5.0.0[v5.0.0]
** `SocketSettings` timeout parameters changed from `int` to `long`
** `BsonDecimal128` now behaves as a number
** `ClusterConnectionMode` computation changed
** Removed deprecated `ServerAddress.getSocketAddress()` / `getSocketAddresses()`
** Removed `Parameterizable` interface
** Removed `MapCodec` and `IterableCodec` classes
** Removed `StreamFactoryFactory` and related classes
* https://github.com/mongodb/mongo-java-driver/releases/tag/r5.5.0[v5.5.0]
** Dropped support for MongoDB 4.0
** BSON codec lookup and decoding performance optimizations

==== Migration

* Address the MongoDB Java Driver changelog breaking changes listed above: https://www.mongodb.com/docs/drivers/java/sync/current/upgrade/[Full upgrade guide]. Other migration steps aren’t needed.


=== coffee-model
💥 ***BREAKING CHANGE*** 💥

The pom maven module and its submodules `coffee-model-base` and `coffee-model-security` moved to frapp:ee project.

==== Migration
* It is necessary to replace the maven dependencies as described below:

[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-model-base</artifactId>
</dependency>
----
->
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.frappee</groupId>
    <artifactId>frappee-model-base</artifactId>
</dependency>
----

[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-model-security</artifactId>
</dependency>
----
->
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.frappee</groupId>
    <artifactId>frappee-model-security</artifactId>
</dependency>
----


* It is necessary to replace the imports as described below:
** `hu.icellmobilsoft.coffee.model.base.AbstractAuditEntity` -> `hu.icellmobilsoft.frappee.model.base.AbstractAuditEntity`
** `hu.icellmobilsoft.coffee.model.base.AbstractEntity` -> `hu.icellmobilsoft.frappee.model.base.AbstractEntity`
** `hu.icellmobilsoft.coffee.model.base.AbstractIdentifiedAuditEntity` -> `hu.icellmobilsoft.frappee.model.base.AbstractIdentifiedAuditEntity`
** `hu.icellmobilsoft.coffee.model.base.AbstractIdentifiedEntity` -> `hu.icellmobilsoft.frappee.model.base.AbstractIdentifiedEntity`
** `hu.icellmobilsoft.coffee.model.base.AbstractProvider` -> `hu.icellmobilsoft.frappee.model.base.AbstractProvider`
** `hu.icellmobilsoft.coffee.model.base.ClassFieldsAndMethodsCache` -> `hu.icellmobilsoft.frappee.model.base.ClassFieldsAndMethodsCache`
** `hu.icellmobilsoft.coffee.model.base.IAuditEntity` -> `hu.icellmobilsoft.frappee.model.base.IAuditEntity`
** `hu.icellmobilsoft.coffee.model.base.IIdentifiedEntity` -> `hu.icellmobilsoft.frappee.model.base.IIdentifiedEntity`
** `hu.icellmobilsoft.coffee.model.base.IVersionable` -> `hu.icellmobilsoft.frappee.model.base.IVersionable`
** `hu.icellmobilsoft.coffee.model.base.annotation.CreatedBy` -> `hu.icellmobilsoft.frappee.model.base.annotation.CreatedBy`
** `hu.icellmobilsoft.coffee.model.base.annotation.CurrentUser` -> `hu.icellmobilsoft.frappee.model.base.annotation.CurrentUser`
** `hu.icellmobilsoft.coffee.model.base.annotation.Dictionary` -> `hu.icellmobilsoft.frappee.model.base.annotation.Dictionary`
** `hu.icellmobilsoft.coffee.model.base.annotation.DictionaryType` -> `hu.icellmobilsoft.frappee.model.base.annotation.DictionaryType`
** `hu.icellmobilsoft.coffee.model.base.annotation.ModifiedBy` -> `hu.icellmobilsoft.frappee.model.base.annotation.ModifiedBy`
** `hu.icellmobilsoft.coffee.model.base.audit.AuditProvider` -> `hu.icellmobilsoft.frappee.model.base.audit.AuditProvider`
** `hu.icellmobilsoft.coffee.model.base.exception.ProviderException` -> `hu.icellmobilsoft.frappee.model.base.exception.ProviderException`
** `hu.icellmobilsoft.coffee.model.base.generator.EntityIdGenerator` -> `hu.icellmobilsoft.frappee.model.base.generator.EntityIdGenerator`
** `hu.icellmobilsoft.coffee.model.base.history.AbstractHistoryEntity` -> `hu.icellmobilsoft.frappee.model.base.history.AbstractHistoryEntity`
** `hu.icellmobilsoft.coffee.model.base.history.HistoryPk` -> `hu.icellmobilsoft.frappee.model.base.history.HistoryPk`
** `hu.icellmobilsoft.coffee.model.base.history.enums.State` -> `hu.icellmobilsoft.frappee.model.base.history.enums.State`
** `hu.icellmobilsoft.coffee.model.base.javatime.AbstractAuditEntity` -> `hu.icellmobilsoft.frappee.model.base.javatime.AbstractAuditEntity`
** `hu.icellmobilsoft.coffee.model.base.javatime.AbstractIdentifiedAuditEntity` -> `hu.icellmobilsoft.frappee.model.base.javatime.AbstractIdentifiedAuditEntity`
** `hu.icellmobilsoft.coffee.model.base.javatime.annotation.CreatedOn` -> `hu.icellmobilsoft.frappee.model.base.javatime.annotation.CreatedOn`
** `hu.icellmobilsoft.coffee.model.base.javatime.annotation.ModifiedOn` -> `hu.icellmobilsoft.frappee.model.base.javatime.annotation.ModifiedOn`
** `hu.icellmobilsoft.coffee.model.base.javatime.history.AbstractHistoryEntity` -> `hu.icellmobilsoft.frappee.model.base.javatime.history.AbstractHistoryEntity`
** `hu.icellmobilsoft.coffee.model.base.javatime.listener.TimestampsProvider` -> `hu.icellmobilsoft.frappee.model.base.javatime.listener.TimestampsProvider`
** `hu.icellmobilsoft.coffee.model.security.SecurityGroup` -> `hu.icellmobilsoft.frappee.model.security.SecurityGroup`
** `hu.icellmobilsoft.coffee.model.security.SecurityPermission` -> `hu.icellmobilsoft.frappee.model.security.SecurityPermission`
** `hu.icellmobilsoft.coffee.model.security.SecurityRole` -> `hu.icellmobilsoft.frappee.model.security.SecurityRole`
** `hu.icellmobilsoft.coffee.model.security.SecurityRoleSecurityGroup` -> `hu.icellmobilsoft.frappee.model.security.SecurityRoleSecurityGroup`
** `hu.icellmobilsoft.coffee.model.security.SecurityRoleSecurityPermission` -> `hu.icellmobilsoft.frappee.model.security.SecurityRoleSecurityPermission`
** `hu.icellmobilsoft.coffee.model.security.SecurityUser` -> `hu.icellmobilsoft.frappee.model.security.SecurityUser`
** `hu.icellmobilsoft.coffee.model.security.SecurityUserSecurityGroup` -> `hu.icellmobilsoft.frappee.model.security.SecurityUserSecurityGroup`
** `hu.icellmobilsoft.coffee.model.security.SecurityUserSecurityRole` -> `hu.icellmobilsoft.frappee.model.security.SecurityUserSecurityRole`
** `hu.icellmobilsoft.coffee.model.security.enums.UserStatus` -> `hu.icellmobilsoft.frappee.model.security.enums.UserStatus`

=== coffee-jpa
💥 ***BREAKING CHANGE*** 💥

The maven module moved to frapp:ee project.

==== Migration
* It is necessary to replace the maven dependencies as described below:

[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-jpa</artifactId>
</dependency>
----
->
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.frappee</groupId>
    <artifactId>frappee-jpa-util</artifactId>
</dependency>
----

* It is necessary to replace the imports as described below:
** `hu.icellmobilsoft.coffee.jpa.annotation.Transactional` -> `hu.icellmobilsoft.frappee.jpa.util.annotation.Transactional`
** `hu.icellmobilsoft.coffee.jpa.health.DatabaseHealth` -> `hu.icellmobilsoft.frappee.jpa.util.health.DatabaseHealth`
** `hu.icellmobilsoft.coffee.jpa.health.DatabaseHealthConstant` -> `hu.icellmobilsoft.frappee.jpa.util.health.DatabaseHealthConstant`
** `hu.icellmobilsoft.coffee.jpa.health.DatabaseHealthResourceConfig` -> `hu.icellmobilsoft.frappee.jpa.util.health.DatabaseHealthResourceConfig`
** `hu.icellmobilsoft.coffee.jpa.health.DatabasePoolHealth` -> `hu.icellmobilsoft.frappee.jpa.util.health.DatabasePoolHealth`
** `hu.icellmobilsoft.coffee.jpa.helper.TransactionHelper` -> `hu.icellmobilsoft.frappee.jpa.util.helper.TransactionHelper`
** `hu.icellmobilsoft.coffee.jpa.service.BaseService` -> `hu.icellmobilsoft.frappee.jpa.util.service.BaseService`
** `hu.icellmobilsoft.coffee.jpa.sql.entity.EntityHelper` -> `hu.icellmobilsoft.frappee.jpa.util.sql.entity.EntityHelper`
** `hu.icellmobilsoft.coffee.jpa.sql.paging.PagingResult` -> `hu.icellmobilsoft.frappee.jpa.util.sql.paging.PagingResult`
** `hu.icellmobilsoft.coffee.jpa.sql.paging.PagingUtil` -> `hu.icellmobilsoft.frappee.jpa.util.sql.paging.PagingUtil`
** `hu.icellmobilsoft.coffee.jpa.sql.paging.QueryMetaData` -> `hu.icellmobilsoft.frappee.jpa.util.sql.paging.QueryMetaData`
** `hu.icellmobilsoft.coffee.jpa.util.JpaUtil` -> `hu.icellmobilsoft.frappee.jpa.util.JpaUtil`
** `hu.icellmobilsoft.coffee.jpa.util.ReflectionUtils` -> `hu.icellmobilsoft.frappee.jpa.util.ReflectionUtils`
** `hu.icellmobilsoft.coffee.jpa.service.BaseServiceTest` -> `hu.icellmobilsoft.frappee.jpa.util.service.BaseServiceTest`

=== coffee-system
💥 ***BREAKING CHANGE*** 💥

The pom maven module and its submodule `coffee-system-jpa` moved to frapp:ee project.

==== Migration
* It is necessary to replace the maven dependency as described below:

[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-system-jpa</artifactId>
</dependency>
----
->
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.frappee</groupId>
    <artifactId>frappee-system-jpa</artifactId>
</dependency>
----

* It is necessary to replace the imports as described below:

** `hu.icellmobilsoft.coffee.system.jpa.converter.Converter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.Converter`
** `hu.icellmobilsoft.coffee.system.jpa.converter.DtoAuditConverter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.DtoAuditConverter`
** `hu.icellmobilsoft.coffee.system.jpa.converter.DtoConverter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.DtoConverter`
** `hu.icellmobilsoft.coffee.system.jpa.converter.IEntityConverter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.IEntityConverter`
** `hu.icellmobilsoft.coffee.system.jpa.converter.IRequestConverter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.IRequestConverter`
** `hu.icellmobilsoft.coffee.system.jpa.converter.IResponseConverter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.IResponseConverter`
** `hu.icellmobilsoft.coffee.system.jpa.converter.list.CommonIdListTypeConverter` -> `hu.icellmobilsoft.frappee.system.jpa.converter.list.CommonIdListTypeConverter`