= v2.11.0 → v2.12.0

coff:ee v2.11.0 -> v2.12.0 migration description, news, changes

=== Global

* Apache commons-lang3 version bump 3.15.0 -> 3.18.0
* parent-oss-pom upgraded from `1.4.0` to `1.5.0`
* The `oss.sonatype.org` snapshot repository was replaced by `central.sonatype.com`, and module names were added for validations.

==== Migration
The commons-lang3 version update introduces some deprecated methods, which will need to be updated across the projects. The list can be found here: https://commons.apache.org/proper/commons-lang/apidocs/deprecated-list.html

=== coffee-rest
* JaxbTool CDI dependent bean destroy fix
* ResponseUtil extended, in case of getFileResponse the filename is also sent back in the header with UTF-8 encoding (filename*=UTF-8''...)
* The `DefaultGeneralExceptionMapper` handles the new `IBaseExceptionWrapper` instead of the `BaseExceptionWrapper`. For more info check the `coffee-dto-base` and `coffee-se-api`.

==== Migration
Changes are backwards compatible doesnt need any migration.

=== coffee-module-docgen

* A new `coffee-module-docgen` pom module has been added for containing modules for generating documentation
** `coffee-module-configdoc`
*** Renamed to `coffee-module-docgen-config` and moved in `coffe-module-docgen`
*** Some class renames are also occurred
** General documentation generation functionality extracted to a new `coffee-module-docgen-common` module
** A new `coffee-module-docgen-sqlcatalog` module has been added for generating sql catalog

=== Migration

Change maven dependency from
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-configdoc</artifactId>
</dependency>
----
to
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-docgen-config</artifactId>
</dependency>
----

---

Change `maven-compiler-plugin` compilerArgs from
----
<compilerArgs>
    <arg>-Acoffee.configDoc.outputDir=${outputDir}</arg>
    <arg>-Acoffee.configDoc.outputFileName=${outputFileName}</arg>
    <arg>-Acoffee.configDoc.outputToClassPath=${outputToClassPath}</arg>
    <arg>-Acoffee.configDoc.dynamicOutputFileName=${dynamicOutputFileName}</arg>
    <arg>-Acoffee.configDoc.columns=${columns}</arg>
</compilerArgs>
----

to

----
<compilerArgs>
    <arg>-Acoffee.docgen.config.outputDir=${outputDir}</arg>
    <arg>-Acoffee.docgen.config.outputFileName=${outputFileName}</arg>
    <arg>-Acoffee.docgen.config.outputToClassPath=${outputToClassPath}</arg>
    <arg>-Acoffee.docgen.config.dynamicOutputFileName=${dynamicOutputFileName}</arg>
    <arg>-Acoffee.docgen.config.columns=${columns}</arg>
</compilerArgs>
----

---

As a result of the move and renames, if these classes are also used on the usage project, the imports must be updated:

* `hu.icellmobilsoft.coffee.module.configdoc.ConfigDoc` -> `hu.icellmobilsoft.coffee.module.docgen.config.ConfigDoc`
* `hu.icellmobilsoft.coffee.module.configdoc.writer.impl.AsciiDocWriter` -> `hu.icellmobilsoft.coffee.module.docgen.config.writer.impl.ConfigDocAsciiDocWriter`
* `hu.icellmobilsoft.coffee.module.configdoc.config.ConfigDocColumn` -> `hu.icellmobilsoft.coffee.module.docgen.config.config.ConfigDocColumn`
* `hu.icellmobilsoft.coffee.module.configdoc.config.ConfigDocConfig` -> `hu.icellmobilsoft.coffee.module.docgen.config.config.ConfigDocConfig`
* `hu.icellmobilsoft.coffee.module.configdoc.processor.ConfigDocProcessor` -> `hu.icellmobilsoft.coffee.module.docgen.config.processor.ConfigDocProcessor`
* `hu.icellmobilsoft.coffee.module.configdoc.processor.ConfigDocVisitor` -> `hu.icellmobilsoft.coffee.module.docgen.config.processor.ConfigDocVisitor`
* `hu.icellmobilsoft.coffee.module.configdoc.data.DocData` -> `hu.icellmobilsoft.coffee.module.docgen.config.data.DocData`
* `hu.icellmobilsoft.coffee.module.configdoc.writer.impl.DynamicAsciiDocWriter` -> `hu.icellmobilsoft.coffee.module.docgen.config.writer.impl.DynamicAsciiDocWriter`
* `hu.icellmobilsoft.coffee.module.configdoc.DynamicConfigDocs` -> `hu.icellmobilsoft.coffee.module.docgen.config.DynamicConfigDocs`
*  `hu.icellmobilsoft.coffee.module.configdoc.processor.DynamicConfigDocsProcessor` -> `hu.icellmobilsoft.coffee.module.docgen.config.processor.DynamicConfigDocsProcessor`
* `hu.icellmobilsoft.coffee.module.configdoc.processor.DynamicConfigDocsVisitor` -> `hu.icellmobilsoft.coffee.module.docgen.config.processor.DynamicConfigDocsVisitor`
* `hu.icellmobilsoft.coffee.module.configdoc.DynamicConfigTemplate` -> `hu.icellmobilsoft.coffee.module.docgen.config.DynamicConfigTemplate`
* `hu.icellmobilsoft.coffee.module.configdoc.processor.DynamicConfigTemplateProcessor` -> `hu.icellmobilsoft.coffee.module.docgen.config.processor.DynamicConfigTemplateProcessor`
* `hu.icellmobilsoft.coffee.module.configdoc.data.DynamicDocData` -> `hu.icellmobilsoft.coffee.module.docgen.config.data.DynamicDocData`
* `hu.icellmobilsoft.coffee.module.configdoc.writer.IDocWriter` -> `hu.icellmobilsoft.coffee.module.docgen.common.writer.IDocWriter`

=== coffee-module-redis
* Redis cluster support has been added to module
** injectable Jedis object is replaced to UnifiedJedis object
** `cluster` configuration key has been added to redis configuration, which contains an url or url list in `$(host):$(port)` format, example:

[source,yaml]
----
coffee:
    redis:
        ...
        auth:
            ...
            cluster:
              - sample-sandbox.icellmobilsoft.hu:6380
              - sample-sandbox.icellmobilsoft.hu:6381
----

==== Migration
As the result of replacing Jedis object, in the usage project must update Jedis usages to UnifiedJedis.

=== coffee-quarkus-extensions
* Every groupId has been changed from `hu.icellmobilsoft.coffee` to `hu.icellmobilsoft.coffee.quarkus`
* Description: <<common_coffee-quarkus-extensions, coffee-quarkus-extensions>>

==== Migration
In projects using quarkus extensions, the groupIds must be changed from `hu.icellmobilsoft.coffee` to `hu.icellmobilsoft.coffee.quarkus`.

=== coffee-dto-base
`BaseExceptionWrapper` interface has been deprecated and a new alternative is introduced in `coffee-se-api`:
`hu.icellmobilsoft.coffee.se.api.exception.wrapper.IBaseExceptionWrapper`.

==== Migration
The changes are backwards compatible and do not require any migration. However, it is recommended to use the new `IBaseExceptionWrapper` at the project level.

=== coffee-se-api
A new `IBaseExceptionWrapper` has been introduced as a replacement for `BaseExceptionWrapper`.

==== Migration
The changes are backwards compatible and do not require any migration. It is recommended to use this new interface instead of `BaseExceptionWrapper`.

=== coffee-cdi
* `hu.icellmobilsoft.coffee.cdi.trace.annotation.Traced.LITERAL` type changed so it can be used with `ITraceHandler`,
and initialized with default values.
* The `LogContainer` now only stores a limited number of log messages. The limit can be configured with the `coffee.logger.logContainer.maxSize` config key. (default: `1000`)

==== Migration
* If you want the old `LogContainer` behaviour back, set the `coffee.logger.logContainer.maxSize` konfig to `2147483647`. But this is highly discouraged.

=== coffee-tool
`JsonbConfigBuilder` introduce to create `JsonbConfig`.

==== Migration
The changes are backwards compatible and do not require any migration.

=== coffee-module-repserv
* New module, more info in the description.
