[#common_core_coffee-tool]
= coffee-tool

The purpose of this module is to collect basic util classes.

All date, String, Number or other static classes should be placed here.

`MavenURLHandler`::
Auxiliary class for XSD Catalog usage, allows to
+
 maven:hu.icellmobilsoft.coffee.dto.xsd:coffee-dto-xsd:jar::!/xsd/en/icellmobilsoft/coffee/dto/common/common.xsd
+
URL handling in the code.
It needs to be activated separately, so it's not a complication (but it's not activated either).

`AesGcmUtil`::
AES 256 GCM encryption and decryption helper class. The cipher is based on `AES/GCM/NoPadding`, the key must be 256 bits long, the IV is 12 bytes long. Includes helper methods for key and IV generation.
+
Example usage:
+
[source, java]
----
String inputText = "test input test";
byte[] key = AesGcmUtil.generateKey(); //B64: HMTpQ4/aEDKoPGMMqMtjeTJ2s26eOEv1aUrE+syjcB8=
byte[] iv = AesGcmUtil.generateIv(); //B64: 5nqOVSjoGYk/oSwj

byte[] encoded = AesGcmUtil.encryptWithAes256GcmNoPadding(key, inputText.getBytes(StandardCharsets.UTF_8), iv);
String encodedB64 = Base64.getEncoder().encodeToString(encoded); //fRCURHp5DWXtrESNHMo1DUoAcejvKDu9Y5wd5zXblg==

byte[] decoded = AesGcmUtil.decryptWithAes256GcmNoPadding(key, encoded, iv);
String decodedString = new String(decoded, StandardCharsets.UTF_8); //test input test
----
+
IMPORTANT: Given key-IV pair must not be reused! For this reason, encrypt/decrypt without IV should only be called with single-use keys!

`JSON serialization/deserialization`::

Serialization and deserialization of java object to/from JSON is done by https://projects.eclipse.org/projects/ee4j.yasson[Eclipse Yasson], which provides a standard binding layer between Java classes and JSON documents (Yasson is the official reference implementation of JSON Binding)
+
Configuration can be done via project-defaults.yml, here is an example:

[source, yml]
----
coffee:
    jsonb:
        config:
            propertyVisibilityStrategyClass: hu.icellmobilsoft.coffee.tool.jsonb.FieldOnlyVisibilityStrategy <1>
            binaryDataStrategy: BASE_64 <2>
            nullValues: false <3>
            formatting: false <4>
            failOnUnknownProperties: true <5>
            encoding: "UTF-8" <6>
            strictIJSON: false <7>
            propertyNamingStrategy: IDENTITY <8>
            propertyOrderStrategy: LEXICOGRAPHICAL <9>
            dateFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ" <10>
            locale: "en_US" <11>
            customAdapters: <12>
              - "your.custom.JsonbAdapter1"
              - "your.custom.JsonbAdapter2"
            customSerializers: <13>
              - "your.custom.JsonbSerializer1"
              - "your.custom.JsonbSerializer2"
            customDeserializers: <14>
              - "your.custom.JsonbDeserializer1"
              - "your.custom.JsonbDeserializer2"
            customProperties: <15>
              - "jsonb.other-config-parameter1#value1"
              - "jsonb.other-config-parameter2#value2"
----

In the above configuration, the following elements can be set:

<1> Property used to specify custom visibility strategy, which fields/properties should be (de)serialized. this configuration requires full class name implementing the interface PropertyVisibilityStrategy in jakarta.json.bind.config.PropertyVisibilityStrategy.
<2> This type can take the values of the enum BinaryDataStrategy in jakarta.json.bind.config.BinaryDataStrategy to determine how binary data is handled.
<3> Property used to specify if json should include fields with null values or not.
<4> Use this setting if you want to pretty format json content.
<5> Property used to specify behaviour in case of unknown properties.
<6> Serialized JSON output encoding format
<7> Enable/Disable restricted profile I-JSON (short for "Internet JSON") https://datatracker.ietf.org/doc/html/rfc7493[I-JSON rfc]
<8> Set predefined naming strategy which affects serialization and deserialization https://jakarta.ee/specifications/jsonb/1.0/apidocs/javax/json/bind/config/propertynamingstrategy[javadoc]
<9> Set predefined ordering strategy which affects serialization and deserialization https://jakarta.ee/specifications/jsonb/1.0/apidocs/javax/json/bind/config/propertyorderstrategy[javadoc]
<10> Customized dateFormat applied globally
<11> Customized local in ISO standard format applied globally
<12> Custom JsonbAdapter classes for additional control over JSON processing.
<13> Custom JsonbSerializer classes for serializing specific types.
<14> Custom JsonbDeserializer classes for deserializing specific types.
<15> Custom jsonb config parameters, key-values are separated by #

The values mention above in the example are the default values, these are used in case of missing configuration.

`JsonUtil`::
JsonUtil is a kind of wrapper of JSONB
+
[source, java]
.example - deserialization of generic type
----
String paramString = "[{\"key\":\"testTitleKey\",\"value\":\"testTitleValue\"}]";
Type paramListType = new TypeToken<List<ParameterType>>() {}.getType();
List<ParameterType> list = JsonUtil.toObject(paramString, paramListType);
System.out.println(list.get(0).getKey());
----
