[#common_core_coffee-grpc]
= coffee-grpc

The purpose of this module is to support gRPC communication and handling.

== coffee-grpc-api
Collector of general gRPC handling for the Coff:ee API (annotations, version, ...).

== coffee-grpc-base
Collector of general Protobuf and gRPC classes. It includes exception handling, status management, CDI, and other general Coff:ee functionalities.

== coffee-grpc-protoc
Helper tool for generating classes from proto files. It uses the https://mustache.github.io/[Mustache] template system, which will be included in the `com.salesforce.jprotoc.ProtocPlugin` system.

Sample usage in a .pom.xml file:
[source,xml]
----
    <build>
        <plugins>
            <plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <configuration>
...
                    <outputTargets>
...
                        <outputTarget>
                            <type>grpc-coffee</type>
                            <pluginArtifact>hu.icellmobilsoft.coffee:coffee-grpc-protoc:${version.hu.icellmobilsoft.coffee}</pluginArtifact>
                        </outputTarget>
                    </outputTargets>
                </configuration>
...
            </plugin>
        </plugins>
    </build>
----

For a more complex example, refer to the https://github.com/i-Cell-Mobilsoft-Open-Source/backend-sampler[backend-sampler] project, specifically the https://github.com/i-Cell-Mobilsoft-Open-Source/backend-sampler/blob/main/api/api-grpc/api-grpc-stub-gen/pom.xml[pom.xml] file.

== coffee-dto/coffee-dto-xsd2proto
Collector of generated schema2proto files for general Coff:ee XSD descriptors (`coffee-dto-xsd` module) and other manually created proto files. This package is used for using Coff:ee proto files, so projects don't need to generate their own Coff:ee proto files.

Unfortunately, the used schema2proto plugin is not compatible with the Windows operating system, so automatic compilation and generation are not configured. If there are changes in the XSD files, the following command should be executed on a Linux-compatible system:

[source,bash]
----
mvn clean install -Dschema2proto -Dcopy-generated-sources
----

Where the `schema2proto` parameter activates XSD -> proto generation, and the `copy-generated-sources` parameter activates copying the generated proto files into the sources. Afterward, the changes will appear in the git diff.

== coffee-dto/coffee-dto-stub-gen
Generated classes for all Coff:ee proto files.
