[#common_core_coffee-grpc]
= coffee-grpc

The purpose of this module is to support gRPC communication and handling.

== coffee-grpc-api
A collector for general gRPC handling of the Coff:ee API (annotations, version, ...).

== coffee-grpc-base
A collector for general Protobuf and gRPC classes. It includes exception handling, status handling, and other general CDI (Contexts and Dependency Injection) and Coff:ee functionalities.

.ExceptionMapper and ExceptionHandler
A generic ExceptionMapper interface following the JAX-RS pattern. It allows converting a specific Exception type to a gRPC Status using the capabilities provided by CDI.

== coffee-grpc-protoc
A helper tool used for proto -> class generation. The logic utilizes the https://mustache.github.io/[Mustache] template system, which will be present in the `com.salesforce.jprotoc.ProtocPlugin` system.

Example usage in a pom.xml:
[source,xml]
----
    <build>
        <plugins>
            <plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <configuration>
...
                    <outputTargets>
...
                        <outputTarget>
                            <type>grpc-coffee</type>
                            <pluginArtifact>hu.icellmobilsoft.coffee:coffee-grpc-protoc:${version.hu.icellmobilsoft.coffee}</pluginArtifact>
                        </outputTarget>
                    </outputTargets>
                </configuration>
...
            </plugin>
        </plugins>
    </build>
----
A more complex example can be found in the https://github.com/i-Cell-Mobilsoft-Open-Source/backend-sampler[backend-sampler] project's https://github.com/i-Cell-Mobilsoft-Open-Source/backend-sampler/blob/main/api/api-grpc/api-grpc-stub-gen/pom.xml[pom.xml].

== coffee-grpc-server-extension
Module containing a CDI-compatible implementation of a gRPC server.

It reads all classes implementing `IGrpcService` and delegates them to the gRPC service through the `GrpcServerManager`.

Implemented features:

* gRPC server configuration based on https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java[NettyServerBuilder]
* MDC (Mapped Diagnostic Context) handling
* Request/Response log, applicable with <<common_core_coffee-rest_LogSpecifier,LogSpecifier>>
annotation on GRPC service implementation method/class
* Exception handling
** Grpc status code mapping
*** General exception: `hu.icellmobilsoft.coffee.grpc.server.mapper.GrpcGeneralExceptionMapper`
*** BaseException exception: `hu.icellmobilsoft.coffee.grpc.server.mapper.GrpcBaseExceptionMapper`
** Grpc header response additions:
*** Business error code (`com.google.rpc.ErrorInfo`)
*** Business error code translation by request locale (`com.google.rpc.LocalizedMessage`)
*** Debug informations (`com.google.rpc.DebugInfo`)

=== Server thread pool
The thread handling is an important part of the gRPC server. Two solutions have been implemented:

* `ThreadPoolExecutor` - default thread pool:
** Configurable through the `coffee.grpc.server.threadpool.default` configuration.
* `ManagedExecutorService` - Jakarta EE managed thread pool:
** A thread pool managed by the server, with context propagation support.

.gRPC server configuration
[source,yaml]
----
coffee:
  grpc:
    server:
      port: 8199 # default 8199
      maxConnectionAge: 60000000 # nano seconds, default Long.MAX_VALUE
      maxConnectionAgeGrace: 60000000 # nano seconds, default Long.MAX_VALUE
      maxInboundMessageSize: 4194304 # Bytes, default 4 * 1024 * 1024 (4MiB)
      maxInboundMetadataSize: 8192 # Bytes, default 8192 (8KiB)
      maxConnectionIdle: 60000000 # nano seconds, default Long.MAX_VALUE
      keepAliveTime: 5 # minutes, default 5
      keepAliveTimeout: 20 # seconds, default 20
      permitKeepAliveTime: 5 # minutes, default 5
      permitKeepAliveWithoutCalls: false

 # default false
      threadPool:
        default:
          corePoolSize: 64 # default 32
          maximumPoolSize: 64 # default 32
          keepAliveTime: 60000 # milliseconds, default 0
        jakarta:
          active: true # default false <1>
----
<1> if `true`, then `coffee.grpc.server.threadpool.default` is ignored.

In case `ManagedExecutorService` thread pool handling an additional Wildfly configuration is required.

.Wildfly gRPC managed executor service configuration
[source,xml]
----
<managed-executor-services>
    <managed-executor-service name="grpc" jndi-name="java:jboss/ee/concurrency/executor/grpc" context-service="default" hung-task-termination-period="0" hung-task-threshold="60000" core-threads="${env.MANAGED_EXECUTOR_SERVICE_GRPC_CORE_THREADS,managed-executor-service.grpc.core-threads:16}" keepalive-time="5000"/>
</managed-executor-services>
----
This configuration is provided in the https://github.com/i-Cell-Mobilsoft-Open-Source/docker-wildfly[docker-wildfly] MicroProfile images starting from version 3.1.

* The jndi-name must match the one in the example (`java:jboss/ee/concurrency/executor/grpc`).
* The minimum number of threads (`core-threads`) can be parameterized according to the example with the `MANAGED_EXECUTOR_SERVICE_GRPC_CORE_THREADS` environment parameter or `managed-executor-service.grpc.core-threads` MicroProfile parameter.

== gRPC client (coffee-grpc-client-extension)
It includes support for implementing a gRPC client.
This includes:

* Configuration management
* Request logging
* Response logging

.gRPC client configuration
[source,yaml]
----
coffee:
  grpc:
    client:
      _configKey_:
        host: localhost # default localhost
        port: 8199 # default 8199
        maxInboundMetadataSize: 8192 # Bytes, default 8192 (8KiB)
        requestLogSize: 1000 # Characters, default 1000
        responseLogSize: 1000 # Characters, default 1000
----

.CDI inject DummyServiceGrpc usage
[source,java]
----
@Inject
@GrpcClient(configKey = "_configKey_") //<1>
private DummyServiceGrpc.DummyServiceBlockingStub dummyGrpcService; //<2>

...
// add header
DummyServiceGrpc.DummyServiceBlockingStub stub = GrpcClientHeaderHelper
    .addHeader(dummyGrpcServiceStub, GrpcClientHeaderHelper.headerWithSid(errorLanguage)); //<3>

// equivalent with `stub.getDummy(dummyRequest);` + exception handling
DummyResponse helloResponse = GrpcClientWrapper.call(stub::getDummy, dummyRequest); //<4>
...
----
<1> Configuration key for connection parameters (e.g., server host and port)
<2> Generated service Stub
<3> Add custom header
<4> gRPC service call + exception handling

== gRPC Metrics
The gRPC server and client can optionally activate interceptors to provide metric data.
For this, only the inclusion of the Maven dependency is required:

.enable gRPC server https://github.com/eclipse/microprofile-metrics[microprofile-metrics] implementation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-server-extension</artifactId>
</dependency>
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-metrics-mpmetrics</artifactId>
</dependency>
----

.enable gRPC client https://github.com/eclipse/microprofile-metrics[microprofile-metrics] implementation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-client-extension</artifactId>
</dependency>
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-metrics-mpmetrics</artifactId>
</dependency>
----

If the metric module is not included at the dependency level, the server/client operation remains unchanged, only metric data is not provided.

Provided metrics: 

* gRPC server
** Received request counter
** Responded response counter
** Request-response processing per second
* gRPC Client
** Sent request counter
** Responded response counter
** Request-response processing per second

== gRPC Tracing
The gRPC server and client can optionally activate interceptors to provide tracing data.
For this, only the inclusion of the Maven dependency is required:

.enable gRPC server https://github.com/eclipse/microprofile-opentracing[microprofile-opentracing] implementation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-server-extension</artifactId>
</dependency>
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-tracing-opentracing</artifactId>
</dependency>
----

.enable gRPC server https://github.com/eclipse/microprofile-telemetry implementation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-server-extension</artifactId>
</dependency>
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-tracing-telemetry</artifactId>
</dependency>
----

.enable gRPC client https://github.com/eclipse/microprofile-opentracing[microprofile-opentracing] implementation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-client-extension</artifactId>
</dependency>
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-tracing-opentracing</artifactId>
</dependency>
----

.enable gRPC client https://github.com/eclipse/microprofile-telemetry implementation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-client-extension</artifactId>
</dependency>
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-grpc-tracing-telemetry</artifactId>
</dependency>
----

If the tracing module is not included at the dependency level, the server/client operation remains unchanged, only tracing data is not provided.

== coffee-dto/coffee-dto-xsd2proto
A collector of generated schema2proto for general XSD descriptors (`coffee-dto-xsd` module) and other manually created proto files. This package serves to use Coff:ee proto files, so projects don't need to generate them again.

Unfortunately, the used schema2proto plugin is not compatible with the Windows operating system, so automatic compilation generation is not set. If there are any changes to the XSD files, the following command needs to be executed on a Linux-compatible system:

[source,bash]
----
mvn clean install -Dschema2proto -Dcopy-generated-sources
----
The `schema2proto` parameter activates XSD -> proto generation, and the `copy-generated-sources` parameter activates copying the generated proto files into the sources. Afterward, the changes will appear in the git diff.

== coffee-dto/coffee-dto-stub-gen
Contains all Coff:ee proto files and their generated classes. The plugin generates an interface descriptor that can be implemented in a full CDI environment. It also generates a BindableService implementation that delegates gRPC calls to the implemented interface.

== microprofile-health support

The *GrpcHealth* can check if the gRPC server is reachable.

.Startup example
[source,java]
----
@ApplicationScoped
public class GrpcHealthCheck {

    @Inject
    private GrpcHealth grpcHealth;

    public HealthCheckResponse checkGrpc() {
        try {
            return grpcHealth.check("gRPC");
        } catch (BaseException e) {
            return HealthCheckResponse.builder().name("gRPC").up().build();
        }
    }

    @Produces
    @Startup
    public HealthCheck produceGrpcStartup() {
        return this::checkGrpc;
    }
}
----