[#common_core_coffee-cdi]
= coffee-dto

Module designed to summarize the ancestors of the basic DTO, Adapters and Exception classes,
mainly to be able to extract some common code into the Coffee jakartaEE solution set.
It should not have any dependencies,
except annotations serving documentation and JAXB functions.

It consists of several submodules.

== coffee-dto-base
Contains java classes that serve as ancestors for the entire Coffee javaEE solution set.

This is where the java.time (java 8+) class for handling XSD universal adapters and basic paths to rest endpoints is served.


The module contains the basic exception classes.
All other exceptions that are created,
can only be derived from these.

== coffee-dto-xsd
Its content should preferably be XSDs to serve as guides on projects.
They should preferably contain very universal XSD simple and complexType,
which projects can bend to their own image.

IMPORTANT: This module does not generate DTO objects, it only adds XSDs.

== coffee-dto-gen
This module is used to generate the Coffee DTO.
It is organized separately to be easily replaced from the dependency structure.

== coffee-dto-impl
The module serves as a sample implementation for `coffee-dto-base`, `coffee-dto-xsd` and `coffee-dto-gen`.
Projects using Coffee will include it.
If the DTOs generated by Coffee do not match the target project, you will have to excelude them at this module.

By itself it is a universal, usable module.
