[#common_core_coffee-jpa]
= coffee-jpa

The purpose of this module is to connect the JPA.

Includes the deltaspike jpa and hibernate hookup.
It contains the paging helper classes, transaction handling classes, and the ancestor of all *Services, the BaseService class.

== TransactionHelper [[TransactionHelper]]

Contains helper methods with *@Transactional* annotations for *@FunctionalInterfaces* declared in the *FunctionalInterfaces* class.

Thus, it is possible that if the first entry point of a class is not in a transaction, but we want to run a code snippet in a transaction within it, we just need to highlight the desired snippet in a *private* method or in any *@FunctionalInterface* provided by coffee and call the corresponding method of *TransactionHelper*, which will perform the transactional execution.

This avoids the need to highlight the logic to be run in the transaction in a *public* method with *@Transactional* annotation and call the method created inside the class via *CDI.current()* or to do the same by highlighting it in a separate class.

.TransactionHelper usage example
[source,java]
----
import jakarta.enterprise.inject.Model;
import jakarta.inject.Inject;

import hu.icellmobilsoft.coffee.dto.exception.BaseException;
import hu.icellmobilsoft.coffee.dto.exception.InvalidParameterException;
import hu.icellmobilsoft.coffee.jpa.helper.TransactionHelper;

@Model
public class TransactionHelperExample {

    @Inject
    private InvoiceService invoiceService;

    @Inject
    private TransactionHelper transactionHelper;

    public void example(Invoice invoice) throws BaseException {
        if (invoice == null) {
            throw new InvalidParameterException("invoice is NULL!");
        }

        // operations outside the transaction
        // ...

        // BaseExceptionFunction running in transaction
        transactionHelper.executeWithTransaction(invoiceService::save, invoice);

        // in-transaction BaseExceptionRunner (e.g.: for void method)
        transactionHelper.executeWithTransaction(() -> saveInvoice(invoice));

        // operations outside the transaction
        // ...
    }

    private void saveInvoice(Invoice invoice) throws BaseException {
        invoiceService.save(invoice);
    }
}
----

== microprofile-health support

The *DatabaseHealth* can check if the database is reachable.
The *DatabasePoolHealth* can check how loaded the connection pool used for operations to the database is.

This function is based on metric data,
so it is necessary that one of the implementations is activated.

.pom.xml
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mp-micrometer</artifactId> <1>
</dependency>
<!-- or -->
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mp-metrics</artifactId> <2>
</dependency>
----
<1> Micrometer metric implementation
<2> Microprofile-metrics metric implementation

.Startup example
[source,java]
----
@ApplicationScoped
public class DatabaseHealthCheck {

    @Inject
    private DatabaseHealth databaseHealth;

    @Inject
    private Config mpConfig;

    public HealthCheckResponse checkDatabaseConnection() {
        DatabaseHealthResourceConfig config = new DatabaseHealthResourceConfig();
        config.setBuilderName("oracle");
        config.setDatasourceUrl("jdbc:postgresql://service-postgredb:5432/service_db?currentSchema=service");
        String datasourceName = mpConfig.getOptionalValue(IConfigKey.DATASOURCE_DEFAULT_NAME, String.class)
                .orElse(IConfigKey.DATASOURCE_DEFAULT_NAME_VALUE);
        config.setDsName(datasourceName);
        try {
            return databaseHealth.checkDatabaseConnection(config);
        }catch (BaseException e) {
            // need to be careful with exceptions, because the probe check will fail if we don't handle the exception correctly
            return HealthCheckResponse.builder().name("oracle").up().build();
        }
    }
    
    @Produces
    @Startup
    public HealthCheck produceDataBaseCheck() {
        return this::checkDatabaseConnection;
    }
}
----

.Readiness example
[source,java]
----
@ApplicationScoped
public class DatabaseHealthCheck {

    @Inject
    private DatabaseHealth databaseHealth;

    public HealthCheckResponse checkDatabasePoolUsage() {
        try {
            return databasePoolHealth.checkDatabasePoolUsage("oracle");
        }catch (BaseException e) {
            return HealthCheckResponse.builder().name("oracle").up().build();
        }
    }
    
    @Produces
    @Readiness
    public HealthCheck produceDataBasePoolCheck() {
        return this::checkDatabasePoolUsage;
    }
}
----
