[#howto_etcd]
= ETCD

Az projekt a konfigurációkat tárolhatja ETCD-ben. Ennek kezelésére már rendelkezésre állnak különböző segédosztályok.

== Konfigurációk használatba vétele, ETCD host bekonfigurálása
Az ETCD konfigurációk használatba vételéhez az coffee-module-etcd modult húzzuk be függőségként.
Ez szolgáltatja majd a konfigurációkezeléshez szükséges segédosztályokat,
valamint tartalmaz egy `EtcdConfig` implementációt, ami azt határozza meg,
hogy a Wildfly Swarm konfigurációjában meghatározott `coffee.etcd.default.url`
(hu.icellmobilsoft.coffee.module.etcd.config.DefaultEtcdConfigImpl osztályban található)
property lesz az ETCD elérhetősége.

== Konfigurációk kezelése backend oldalon
Backend oldalon több mód is van a konfigurációk kezelésére.
Ezek jellemzően egymást támogatják, egymást egészítik ki.

== Konfiguráció értékek injectelése
A microprofile-config  annotáció segítségével injectelhetőek az egyes konfiguráció értékek.
Ahhoz hogy a microprofile-config észlelje az ETCD tárhelyet, a kódunkban aktiválni kell a `coffee-module-etcd`-ben
található DefaultEtcdConfigSource osztályt. Ezért létre kell hozni a
"src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource" fájlt,
melybe a következőt kell rakni:

.src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
[source,java]
----
hu.icellmobilsoft.coffee.module.etcd.producer.DefaultEtcdConfigSource
----


Ennek a ConfigSource-nak 150 értékre van állítva a prioritása.

Lehetőség van String, Integer, Boolean, Long, Float ás Double típusú konfigurációk injectelésére. Az ETCD-ben mindenképp String tárolódik, az érték kiolvasása után történik meg a parsolás a kívánt típusra. A mechanizmus a háttérben a ConfigEtcdHandler-t használja az értékek kiolvasására.
Pl.:

.Konfigurációs értékek injectelése
[source,java]
----
// nem ajánlott, a többi módszerek közül érdemes választani
@Inject
@ConfigProperty(name="key")
Provider<String> keyValue;
 
 
// hagyományos microprofile-config lekérdezés
public String kodban() {
    Config config = ConfigProvider.getConfig();
    String keyValue =  config.getValue("key", String.class);
    return keyValue;
}
----

== ConfigurationHelper osztály
Az osztály segítségével lehetőség van típushelyes konfigurációk lekérdezésére.
A háttérben a konfiguráció injectelési mechanizmust használja, valamint RequestScope szintű
cache-t használ (request scopeon belül egy lekérdezés csak 1x van lekérdezve az ETCD-ből).

.Konfiguráció lekérdezése
[source,java]
----
@Inject
private ConfigurationHelper configurationHelper;
...
Integer ttl = configurationHelper.getInteger("public.login.session.token.validity");
----

== ApplicationConfiguration osztály
Hasonlóképpen a ConfigurationHelper osztályhoz, csak @ApplicationScope szintű cache-t használ,
melyben az eltárolt értékek 30 percre tárolódnak. Lehetőséget nyújt ezeknek az eltárolt értékeknek azonnali
felejtésére, amire további logikát lehet építeni (például külsőleg változtatni az értéken ETCD-ben,
majd topic JMS-re elfelejteni az értékeket hogy azonnal olvassa is ki újra).

.ApplicationConfiguration példa
[source,java]
----
@Inject
private ApplicationConfiguration applicationConfiguration;
 
public String kodban() {
    String minVersion = applicationConfiguration.getString(EtcdVal.KEY_PUBLIC_INVOICE_MIN_REQUEST_VERSION);
    return minVersion;
}
----

== ConfigEtcdHandler osztály
Lehetőséget biztosít konfiguráció értékek írására és olvasására. A háttérben a ConfigEtcdService-t használja.

.Konfiguráció írása
[source,java]
----
@Inject
private ConfigEtcdHandler configEtcdHandler;
...
configEtcdHandler.putValue("public.email.sender", "noreply@sample.teszt.hu");
----

.Konfiguráció lekérdezése
[source,java]
----
@Inject
private ConfigEtcdHandler configEtcdHandler;
...
String adminEmail = configEtcdHandler.getValue("public.email.sender");
----

=== Hivatkozás másik konfigurációra
A ConfigEtcdHandler, és így közvetett módon a ConfigurationHelper és a @ConfigProperty annotáció is lehetővé teszi,
hogy az egyik konfig értéke egy másik konfigurációra hivatkozzon. Ilyen esetben { és } karakterek
közt kell a hivatkozott konfigurációt megadni.

.Hivatkozás másik konfigurációra
[source,java]
----
@Inject
private ConfigEtcdHandler configEtcdHandler;
...
configEtcdHandler.putValue("protected.iop.url.main",      "http://sample-sandbox.hu/kr_esb_gateway/services/IOPService?wsdl");
configEtcdHandler.putValue("protected.iop.url.alternate", "http://localhost:8178/SampleMockService/IOPService2?wsdl");
configEtcdHandler.putValue("public.iop.url", "{protected.iop.url.main}");
String contactEmail = configEtcdHandler.getValue("public.iop.url"); //A visszaadott érték "http://sample-sandbox.hu/kr_esb_gateway/services/IOPService?wsdl"
----
A hivatkozás szigorúan egy adott másik konfigurációra kell, hogy hivatkozzon, más tartalom nem engedélyezett.
Pl. a beágyazott hivatkozás nem kerül feloldásra (http://{masik.etcd.conf}:8178/SampleMockService/IOPService2?wsdl").

== ConfigEtcdService osztály
Lehetőséget nyújt konfigurációs értékek lekérdezésére, írására, listázására, keresésére.
A felsoroltak közül a legalacsonyabban fekvő osztály. A fenti mechanizmusok mindegyike ezen keresztül
valósítja meg működését. Vélhetően csak akkor lesz szükség a használatára, ha törölni,
listázni szeretnénk a konfigurációkat.

.Konfiguráció írása, lekérdezése, törlése
[source,java]
----
@Inject
private ConfigEtcdService configEtcdService;
...
configEtcdService.putValue("protected.iop.url.main", "http://sample-sandbox.hu/kr_esb_gateway/services/IOPService?wsdl"); //írás
String senderEmail = configEtcdService.getValue("protected.iop.url.main"); //olvasás
configEtcdService.delete("protected.iop.url.main"); //törlés
----

.Konfigurációk listázása
[source,java]
----
@Inject
private ConfigEtcdService configEtcdService;
...
Map<String, String> allConfigMap = configEtcdService.getList(); //összes konfiguráció listázása
Map<String, String> publicConfigMap = configEtcdService.searchList("public."); //adott prefixű kulccsal rendelkező konfigok listázása (nem lehet üres String)
----
A service nem engedélyezi null vagy üres String érték mentését konfiguráció értékeként. E helyett esetleg törölni lehet a konfigurációt.

Nem létező konfiguráció elkérése, törlése esetén BONotFoundException-t dob a service.
Mivel ezt a mechanizmust használja minden felsorolt lehetőség, így ez mindegyikre igaz.
@ConfigurationValue annotációval történő injektelés esetén a hibát elkapjuk, és null lesz a beállított érték.

== Konfigurációk kezelése frontend oldalon
Van egy mini rest alkalmazás, az *-config-service. Ez rendelkezésre bocsát 3 endpointot konfigurációk
egyenkénti vagy listázott lekérdezésére, valamint a `public.` prefix-szel rendelkező konfigurációk módosítására.

== Default értékek
A konfigurációkezelő nem támogat default értékeket, nem létező konfiguráció elkérése BONotFoundException-t dob, injektálás esetén null értékre értékelődik ki.

== Namespace-ek, konfiguráció elnevezési konvenciók
A konfiguráció kezelő nem támogat külön namespace-ket, minden, az etcd-ben tárolt információhoz hozzáférünk.

Minden konfiguráció kulcsa egy láthatósági prefix-szel kezdődik.
A következő konvenciók alapján kezelik ezeket:

[options="header",cols="1,1"]
|===
|Prefix   |Leírás   
//-------------
|`private.`   |Csak a backend számára elérhető konfiguráció   
|`protected.` |A backend és a frontend számára is elérhető konfiguráció, a frontend csak olvashat   
|`public.`    |A backend és a frontend számára is elérhető konfiguráció, a frontend is módosíthatja az értékét   
|===

== Rendelkezésre álló konfigutációk gyűjtő interfésze
Az alkalmazás által használt, rendelkezésre álló konfigurációkat az EtcdVal interfészben kerülnek
összegyűjtésre az *-common-dto modulban. Konfigurációk írásakor, olvasásakor az itt definiált
konstansokra hivatkoznak.

== Konfigurációk kezelés Command Line Tool segítségével
Töltsük le és csomagoljuk ki a rendszerünknek megfelelő ETCD csomagot: https://github.com/coreos/etcd/releases/

Állítsuk az ETCDCTL_API környezeti változó értékét 3-ra:
[source,batch]
----
#Linux
export ETCDCTL_API=3
 
#Windows
set ETCDCTL_API=3
----

Parancssorból az etcdctl segítségével írhatjuk, olvashatjuk az ETCD konfigurációban található értékeket:

[source,batch]
----
#Összes konfiguráció kiolvasása
etcdctl --endpoints=%ETCD_ENDPOINTS% get "" --from-key
 
#Egy adott konfiguráció értékének kiolvasása
etcdctl --endpoints=%ETCD_ENDPOINTS% get private.sample
 
#Egy adott konfiguráció értékének írása
etcdctl --endpoints=%ETCD_ENDPOINTS% put private.sample ertek
----