[#common_module_coffee-module-totp]
= coffee-module-totp

The purpose of this module is to create and verify Time-based one-time passwords (TOTP) according to the standard. 
We have implemented the algorithm described in RFC 6238, supplemented by the microprofile-config we use.  

NOTE: The algorithm in rfc-6238
https://tools.ietf.org/html/rfc6238

== Implementation in the project

=== pom.xml

.Coffee module activation
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee.module.totp</groupId>
    <artifactId>coffee-module-totp</artifactId>
</dependency>
----

Table 1 shows the configuration keys used by the module.

.configuration parameters
[options="header",cols="1,1,1"]
|===
|parameter name |default value |description   
//----------------------
|totp.password.digits.length |6 |The length of the password generated by our method (max. 9)   
|totp.password.timestep.millisec |30000 |The length of the time window in milliseconds associated with the currently generated password   
|totp.password.hash.algorithm |HmacSha1 |Use this hash algorithm to generate the password 
|totp.password.secret.length |16 |A secret of this length is generated/used  
|totp.verify.additional.windows.count |0 |This parameter is used to extend the password verification to adjacent time windows   
|===
The default values are set so that the module generates the same otp as google authenticator, but of course you can deviate from this.

.The main methods
* TOTPVerifier.verify

This allows us to validate the resulting OTP by extending the validity check to additional time windows.
You can specify all the data needed for the verification in a parameter, but you can also use the overload methods, where the stored/default values in the configuration are used.


* TOTPGenerator.generateBase32Secret

This generates a (shared) secret for the user, by default 16 bytes long. The desired length can be passed as a parameter. 

* TOTPGenerator.generatePassword

If we need an OTP, we can use the generatePassword method for this, also specifying all the parameters needed to generate it, or based on the configured/default values.

.Usage:
[source,java]
----
@Inject
private TOTPVerifier totpVerifier;
@Inject
private TOTPGenerator totpGenerator;

//secretKey generation, you can optionally specify the length of the secret in a parameter, but 16 is usually sufficient
String secretKeyBase32Encoded1 = totpGenerator.generateBase32Secret();
String secretKeyBase32Encoded2 = totpGenerator.generateBase32Secret(32);

//check the received password
//throws TechnicalExceptiont with error code CoffeeFaultType.INVALID_ONE_TIME_PASSWORD in case of wrong password
totpVerifier.verify(secretKey, clientOtp, currentUTCTimestamp, codeDigits, hashAlgorithm);
//if we use default configuration, we can call methods with less parameters 
totpVerifier.verify(secret, clientOtp);
totpVerifier.verify(secret, clientOtp, currentUTCTimestamp);


//totp generation
//output of the following methods is the generated password
String otp1 = totpGenerator.generatePassword(secret, currentUTCTimestamp, digits, TOtpAlgorithm);
//if we use default configuration, we can call methods with less parameters 
String otp2 = totpGenerator.generatePassword(secret);
String otp3 = totpGenerator.generatePassword(secret, currentUTCTimestamp);
----

WARNING: It is advisable to persist the last validated and accepted OTP at the project level, so that it cannot be reentered.

Coffee implements a default TOTPGenerator (DefaultTOTPGneratorImpl) and a TOTPVerifier (DefaultTOTPVerifierImpl) class, which can be overridden in the project using CDI if required.
