[#common_core_coffee-jpa]
= coffee-jpa

Modul célja a JPA bekötése.

Tartalmazza a deltaspike jpa és a hibernate bekötését.
Itt találhatók a lapozás segítő osztályok, tranzakció kezelési osztályok, és minden *Service őse, a BaseService osztály.

== TransactionHelper [[TransactionHelper]]

Segédmetódusokat tartalmaz *@Transactional* annotációval ellátva a *FunctionalInterfaces* osztályban deklarált *@FunctionalInterface*-ekhez.

Így lehetőségünk van arra, hogy ha egy osztály első belépési pontja nincs tranzakcióban, de azon belül szeretnénk tranzakcióban futtatni egy kód részletet, akkor elegendő a kívánt részt kiemelni egy *private* metódusba vagy bármilyen coffee által nyújtott *@FunctionalInterface*-be és meghívni a *TransactionHelper* megfelelő metódusát, ami elvégzi a tranzakcióban való futtatást.

Ezzel elkerüljük, hogy *@Transactional* annotációval ellátott *public* metódusba kelljen kiemelni a tranzakcióban futtatandó logikát és *CDI.current()*-en keresztül meghívni az osztályon belül elkészített metódust vagy ugyan ezt külön osztályba kiemelve elvégezni.

.TransactionHelper használati példa
[source,java]
----
import jakarta.enterprise.inject.Model;
import jakarta.inject.Inject;

import hu.icellmobilsoft.coffee.dto.exception.BaseException;
import hu.icellmobilsoft.coffee.dto.exception.InvalidParameterException;
import hu.icellmobilsoft.coffee.jpa.helper.TransactionHelper;

@Model
public class TransactionHelperExample {

    @Inject
    private InvoiceService invoiceService;

    @Inject
    private TransactionHelper transactionHelper;

    public void example(Invoice invoice) throws BaseException {
        if (invoice == null) {
            throw new InvalidParameterException("invoice is NULL!");
        }

        // tranzakción kívüli műveletek
        // ...

        // tranzakcióban futó BaseExceptionFunction
        transactionHelper.executeWithTransaction(invoiceService::save, invoice);

        // tranzakcióban futó BaseExceptionRunner (pl.: void metódus esetén)
        transactionHelper.executeWithTransaction(() -> saveInvoice(invoice));

        // tranzakción kívüli műveletek
        // ...
    }

    private void saveInvoice(Invoice invoice) throws BaseException {
        invoiceService.save(invoice);
    }
}
----

== IJpaBatchService [[IJpaBatchService]] (a.k.a BatchService)

Az *IJpaBatchService* a tömeges adatbázis műveletek (insert, update, delete) csoportosan való végrehajtására szolgál.
Hibernate alapú implementációja a `frappee-hibernate` modulban található.

== microprofile-health támogatás

A *DatabaseHealth* ellenőrizni tudja hogy elérhető-e az adatbázis.
A *DatabasePoolHealth* ellenőrizni tudja mennyire terhelt az adatbázishoz műveletekhez használt connection pool.

Ez a funkció a metrika adatain alapszik,
így szükséges hogy valamelyik implementáció aktiválva legyen.

.pom.xml
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mp-micrometer</artifactId> <1>
</dependency>
<!-- vagy -->
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mp-metrics</artifactId> <2>
</dependency>
----
<1> Micrometer metrika implementáció
<2> Microprofile-metrics metrika implementáció

.Startup használati példa
[source,java]
----
@ApplicationScoped
public class DatabaseHealthCheck {

    @Inject
    private DatabaseHealth databaseHealth;

    @Inject
    private Config mpConfig;

    public HealthCheckResponse checkDatabaseConnection() {
        DatabaseHealthResourceConfig config = new DatabaseHealthResourceConfig();
        config.setBuilderName("oracle");
        config.setDatasourceUrl("jdbc:postgresql://service-postgredb:5432/service_db?currentSchema=service");
        String datasourceName = mpConfig.getOptionalValue(IConfigKey.DATASOURCE_DEFAULT_NAME, String.class)
                .orElse(IConfigKey.DATASOURCE_DEFAULT_NAME_VALUE);
        config.setDsName(datasourceName);
        try {
            return databaseHealth.checkDatabaseConnection(config);
        }catch (BaseException e) {
            // need to be careful with exceptions, because the probe check will fail if we don't handle the exception correctly
            return HealthCheckResponse.builder().name("oracle").up().build();
        }
    }
    
    @Produces
    @Startup
    public HealthCheck produceDataBaseCheck() {
        return this::checkDatabaseConnection;
    }
}
----

.Readiness használati példa
[source,java]
----
@ApplicationScoped
public class DatabaseHealthCheck {

    @Inject
    private DatabaseHealth databaseHealth;

    public HealthCheckResponse checkDatabasePoolUsage() {
        try {
            return databasePoolHealth.checkDatabasePoolUsage("oracle");
        }catch (BaseException e) {
            return HealthCheckResponse.builder().name("oracle").up().build();
        }
    }
    
    @Produces
    @Readiness
    public HealthCheck produceDataBasePoolCheck() {
        return this::checkDatabasePoolUsage;
    }
}
----
