[#common_core_coffee-tool]
= coffee-tool

Modul célja az alap util osztályok gyűjtése.

Minden dátum, String, Number vagy egyéb statikus osztályoknak itt a helye.

`MavenURLHandler`::
Az XSD Catalog használatra szolgáló segédosztály, lehetővé teszi a
+
 maven:hu.icellmobilsoft.coffee.dto.xsd:coffee-dto-xsd:jar::!/xsd/hu/icellmobilsoft/coffee/dto/common/common.xsd
+
URL kezelését a kódban.
Külön aktiválni kell, tehát nem okoz komplikációt (de aktiválva sem).

`AesGcmUtil`::
AES 256 GCM encryptálásra és decryptálásra segédosztály. A cipher `AES/GCM/NoPadding` alapján történik, a kulcsnak 256 bit hosszúnak kell lennie, az IV 12 byte hosszú. Tartalmaz segéd metódusokat kulcs és IV generáláshoz is.
+
Példa használat:
+
[source, java]
----
String inputText = "test input test";
byte[] key = AesGcmUtil.generateKey(); //B64: HMTpQ4/aEDKoPGMMqMtjeTJ2s26eOEv1aUrE+syjcB8=
byte[] iv = AesGcmUtil.generateIv(); //B64: 5nqOVSjoGYk/oSwj

byte[] encoded = AesGcmUtil.encryptWithAes256GcmNoPadding(key, inputText.getBytes("UTF-8"), iv);
String encodedB64 = Base64.getEncoder().encodeToString(encoded); //fRCURHp5DWXtrESNHMo1DUoAcejvKDu9Y5wd5zXblg==

byte[] decoded = AesGcmUtil.decryptWithAes256GcmNoPadding(key, encoded, iv);
String decodedString = new String(decoded, "UTF-8"); //test input test
----
+
IMPORTANT: Adott kulcs-IV párt nem szabad újra használni! Emiatt az IV nélküli encrypt/decrypt-et csak egyszer használatos kulcsokkal szabad meghívni!

`JSON szerializálás/deszerializálás`::

Java objektumok JSON-re való szerializálása és deszerializálása az https://projects.eclipse.org/projects/ee4j.yasson[Eclipse Yasson] keretrendszerrel történik, mely egy szabványos réteget biztosít a Java osztályok és a JSON dokumentumok között (Yasson a hivatalos JSONB referencia implementációja)
+
Konfigurációja a project-defaults.yml által történik, az alábbi példa alapján:

[source, yml]
----
coffee:
    jsonb:
        config:
            propertyVisibilityStrategyClass: hu.icellmobilsoft.coffee.tool.jsonb.FieldOnlyVisibilityStrategy <1>
            binaryDataStrategy: BASE_64 <2>
            nullValues: false <3>
            formatting: false <4>
            failOnUnknownProperties: true <5>
            encoding: "UTF-8" <6>
            strictIJSON: false <7>
            propertyNamingStrategy: IDENTITY <8>
            propertyOrderStrategy: LEXICOGRAPHICAL <9>
            dateFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ" <10>
            locale: "en_US" <11>
            customAdapters: <12>
              - "your.custom.JsonbAdapter1"
              - "your.custom.JsonbAdapter2"
            customSerializers: <13>
              - "your.custom.JsonbSerializer1"
              - "your.custom.JsonbSerializer2"
            customDeserializers: <14>
              - "your.custom.JsonbDeserializer1"
              - "your.custom.JsonbDeserializer2"
----

A fenti beállításokban a következő értékek adhatóak meg:

<1> jakarta.json.bind.config.PropertyVisibilityStrategy interface-t megvalósító osztály teljes elérése.
<2> Ez a típus a jakarta.json.bind.config.BinaryDataStrategy enum értékeit veheti fel, hogy miként kezelődjön a bináris adat.
<3> Ezzel a beállítással megadható, hogy a json tartalmazzon-e null értékkel rendelkező mezőket vagy sem.
<4> Json tartalom formázása állítható be vele
<5> Ezzel a beállítással megadható, hogy ismeretlen mező esetén dobjon-e hibát vagy sem
<6> Szerializálásnál használt kódolási formátum
<7> I-JSON ("Internet JSON") korlátozott profil engedélyezése  https://datatracker.ietf.org/doc/html/rfc7493[I-JSON rfc]
<8> Szerializálásnál és deszerializálásnál használt mező nevezési stratégiája https://jakarta.ee/specifications/jsonb/1.0/apidocs/javax/json/bind/config/propertynamingstrategy[javadoc]
<9> Szerializálásnál és deszerializálásnál használt mezők rendezési stratégiája https://jakarta.ee/specifications/jsonb/1.0/apidocs/javax/json/bind/config/propertyorderstrategy[javadoc]
<10> Egyedi beállítás dátum formátumra
<11> Egyedi locale beállítás ISO szabvány formátumban
<12> Egyedi JsonbAdapter osztályok
<13> Egyedi JsonbSerializer osztályok
<14> Egyedi JsonbDeserializer osztályok

A példában megjelölt értékek az alapértelmezett értékei, amennyiben nincs külön konfiguráció megadva, ezeket az értékeket fogja használni.

`JsonUtil`::
A JsonUtil osztály egy a JSONB használatára épülő util osztály
+
[source, java]
.példa - generikus típus deszerializációja
----
String paramString = "[{\"key\":\"testTitleKey\",\"value\":\"testTitleValue\"}]";
Type paramListType = new TypeToken<List<ParameterType>>() {}.getType();
List<ParameterType> list = JsonUtil.toObject(paramString, paramListType);
System.out.println(list.get(0).getKey());
----
