= Gren usage

There is an unofficial GitHub tool that can be used to generate release notes and a changelog for a given GitHub project.

At the time of use on the project, the latest version is 0.17.3.

== Gren preconditions

The first step is to install Node.js to use Gren.

* For Windows users, it can be downloaded from this address: https://nodejs.org/en/download/
* For Linux users, the process is a bit more complicated due to the different distributions, but Node.js provides assistance for this as well: https://nodejs.org/en/download/package-manager/

The second step is to install the `github-release-notes` npm package:

```shell
npm install github-release-notes -g
```

Next, you need to generate a `GitHub token` with _**repo** scope_ following this guide: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line[link].

After that, you need to add the GREN_GITHUB_TOKEN key to your environment variables.

Linux:
```shell
export GREN_GITHUB_TOKEN=your_token_here
```

If you don't want to store the token in an environment variable, you can specify it when running the command:

```shell
gren release --token=[your token]
```

== Basic use cases


The `gren` tool directly uses the repository information from the current folder where it is run, which is initialized with `git`.

```shell
# Nnavigate to your project directory
cd ~/Path/to/repo
# Run the desired command (see below).
gren release
```

=== Parancsok

There are two main types of `gren` commands:

==== `gren release`

`gren` will find the latest tag, create a draft of the new release using closed tasks since the previous tag, and then publish it to the **release** panel of the GitHub repository for that project.

==== `gren changelog`

It creates a `CHANGELOG.md` file using all the release notes associated with the repository.
If the file already exists, it can be overwritten using the `--override` flag.

```shell
gren changelog --override
```

To generate a brand new release note using the same approach as for releases, you should run the command with the `--generate` flag.

```shell
gren changelog --generate
```


== Configuration file

You can create a configuration file where you can define various options in advance, so you don't need to specify them when running the command. https://github-tools.github.io/github-release-notes/options.html#configuration-file[A beállítási lehetőségeket itt találod]
The accepted files can be the following:

- `.grenrc`
- `.grenrc.json`
- `.grenrc.yml`
- `.grenrc.yaml`
- `.grenrc.js`

The following options are enforced in the file used by the project:

- debug enabled
- overwriting enabled
- Changelog and release are generated for every tag.
- include-messages `all`, to make everything visible
- CHANGELOG.md The default filename for the changelog file
- generate switch enabled
- Tasks labeled with "enhancement", "documentation", and "dependencies" are grouped under Enhancements, while tasks labeled with "bug" are grouped under Bug Fixes.
- A predefined layout is also defined in the config file under the `template` section.


https://github-tools.github.io/github-release-notes/options.html[You can find all options here]
For a more detailed description, see README.md in https://github.com/github-tools/github-release-notes#gren-[Gren's github repository].

