= Gren használata

Létezik egy nem hivatalos github tool, melynek segítségével generálni lehet release notes-ot valamint changelog-ot egy adott github projekthez.

A projekten való használat időpontjában a legfrissebb változat a 0.17.3.

== Gren előfeltételei

Első lépésben Node.js-re van szükség a Gren használatához.

* Windows-t használóknál ez a https://nodejs.org/en/download/ címen tölthető le.
* Linux-ot használók számára egy kicsit bonyolultabb a történet a különböző változatok miatt, de a Node.js segítséget nyújt ehhez is: https://nodejs.org/en/download/package-manager/

Második lépésben telepíteni kell a `github-release-notes` npm csomagot:

```shell
npm install github-release-notes -g
```

Ezután, generálni kell egy `GitHub tokent`, _**repo** scope-pal_, a következő segédlet alapján https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line[link].

Ezután fel kell venni a GREN_GITHUB_TOKEN kulcsot a környezeti változók közé.

Linux:
```shell
export GREN_GITHUB_TOKEN=your_token_here
```

Ha nem akarod a tokent környezeti változóba tárolni, van lehetőség a parancs futtatásakor megadni:

```shell
gren release --token=[your token]
```

== Alap használati esetek


A `gren` közvetlenül használja a repository információit az aktuális mappából ahol futtatva van, ami a `git`-tel van inicializálva.

```shell
# Navigálj a projekted mappájába
cd ~/Path/to/repo
# Futtasd kívánt parancsot (lásd lentebb)
gren release
```

=== Parancsok

Két fő típusa van a gren parancsnak:

==== `gren release`

`gren` meg fogja keresni a legutolsó tag-et, készít egy piszkozatot az új releaset a lezárt feladatok használatával az előző taghez képest, ezután az adott projekt GitHub repo-jának **release** paneljére publikálja.

==== `gren changelog`

Készít egy `CHANGELOG.md` fájlt minden release notes felhasználásával, ami a repohoz van.
Ha már létezik ez a fájl, akkor felülírható a `--override` kapcsolóval.

```shell
gren changelog --override
```

Egy vadonatúj release note generálásához, ugyanazt a megközelítést alkalmazva, mint a kiadásoknál, a `--generate` kapcsolóval kell futtatni a parancsot.

```shell
gren changelog --generate
```


== Konfigurációs fájl

Létre lehet hozni konfigurációs fájlt, ahol a külöböző kapcsolókat előre definiálni lehet, így nem kell a parancs futtatásakor megadni őket. https://github-tools.github.io/github-release-notes/options.html#configuration-file[A beállítási lehetőségeket itt találod]
Az elfogadott fájlok a következőek lehetnek:

- `.grenrc`
- `.grenrc.json`
- `.grenrc.yml`
- `.grenrc.yaml`
- `.grenrc.js`

A projektben használt fájlban a következő opciók vannak érvényesítve:

- debug engedélyezve
- felülírás engedélyezve
- minden tag-re lefut a changelog és release
- include-messages `all`, hogy minden látható legyen
- CHANGELOG.md fájl az alapértelmezett changelog fájl neve
- generate kapcsoló engedélyezve
- Csoportosítva jelennek meg a feladatok Enhancements alatt a "enhancement", "documentation", "dependencies" címkével ellátott feladatok, míg a Bug Fixes alatt a bug címkével ellátott feladatok
- Előre definiált kinézet van még meghatározva a config fájlban a template alatt.


https://github-tools.github.io/github-release-notes/options.html[Minden opciót megtalálsz itt]
Bővebb leírás a https://github.com/github-tools/github-release-notes#gren-[Gren github repójában] lévő README.md-ben található.

