= v1.11.0 → v1.12.0

coff:ee v1.11.0 -> v1.12.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

=== coffee-jpa

Bevezetésre került a link:#TransactionHelper[TransactionHelper] osztály.

=== coffee-tool

RandomUtil osztályban a generateId a javadoc-ban írt 16 karakter helyett 17-et is tudott visszaadni, mert a getNextIndex metódusban tovább tudott futni az index 1296-ig is, amit a generateId-ban 36-os számrendszerben 100-ra alakított, így túllépett. Javítás 1295-ig engedi az indexet.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redisstream
* `coffee.redisstream.{0}.consumer.manualAck` konfiguráció bevezetése. Lásd: link:#common_module_coffee-module-redisstream-config[coffee-module-redisstream konfiguráció]

==== Átállás
* Amennyiben a régi működést szeretnénk alkalmazni, azaz ha exception-t dob a redis stream consumer,
akkor ne történjen `XACK`, akkor a stream konfigjában fel kell venni a `coffee.redisstream.{0}.consumer.manualAck` kulcsot `true` értékkel.

=== coffee-module-mp-restclient
* `DefaultBaseExceptionResponseExceptionMapper` fel lett készítve "application/octet-stream" válaszra.
Ilyenkor megpróbálja a streamben válaszolt `BaseExceptionResultType`-ot json vagy xml szerint felparszolni. 

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* Létrejött egy új MessageBodyWriter,
ami a `application/octet-stream` + `BaseResultType` válaszokat kezeli.
Alapértelmezetten aktiválva van,
mivel nem volt ehhez hasonló megoldás a rendszerben és a Resteasy sem nyújtott semmi választ ilyenkor,
csak elnyelte a response body-t.

==== Átállás

Csak ott érinthet valamit amikor `application/octet-stream` mediatype a várt válasz és elszálás
történik a távoli stream előállításnál.
Meglehet hogy ezekre az esetekre valami egyedi mapper/writter lekezelés volt a projektben.
