= v1.5.0 → v1.6.0

coff:ee v1.5.0 -> v1.6.0 migrációs leírás, újdonságok, változások leírása

== Változások

* Bump Jedis 3.3.0 -> 3.6.0 - Natív java 8 és Redis 6.2 support
* Bump apache httpcore 4.4.5 -> 4.4.13 - https://archive.apache.org/dist/httpcomponents/httpcore/RELEASE_NOTES-4.4.x.txt
* Bump apache httpclient 4.5.4 -> 4.5.13 - https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt

=== coffee-module-redis
Redis 6.2 upgrade változást hozott hogy a timeout megadása int-ről long-ra változott.
Ez át lett vezetve a rendszerben is,
de mivel a java lekezeli az int->long típust,
nincs feltehetően projekt kód ütközés.

Bevezetésre került funkciók:

* *lmove* - (Redis 6.2) egy lépésben POP + PUSH másik listába
* *removeValueFromList* (*lrem*) - lista elem törlése érték szerint

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redisstream
* Átnezésre került a konfigurációs kulcs: `stream.maxlen` -> `producer.maxlen`-re.
* Az átnevezett `producer.maxlen` kulcsnak volt egy default 1.000.000 értéke,
mely el lett távolítva, tehát ha nincs megadva a konfigurációs kulcs,
végtelen mennyiségű kulcs marad a streamben (Redis korlátain belül).
* Bevezetésre került a `producer.ttl` kulcs,
amelynek szerepe van az új üzenet publikálásánál az adott stream-re.
Minden régebbi üzenet a streamen mely a `producer.ttl` (millisec) idősebb - törlésre kerül.

==== Átállás
A `stream.maxlen` kulcs átnevezését a konfigurációkban át kell vezetni.
