= v1.10.0 → v1.11.0

coff:ee v1.10.0 -> v1.11.0 migrációs leírás, újdonságok, változások leírása

== Változások

=== coffee-module-redis

* *JedisDataException TechnicalException*-be lett wrap-olva, így a régi logika nem tudta lekezelni azt, ezért a *cause*-ban
lévő *JedisDataException* kezelésére kellett módosítani a folyamtot.
* `RedisStreamConsumerExecutor`-ban a `handleGroup` lezárta a jedis connection-t amit a `consumeOne` még használt volna,
így exception keletkezett.
* Bevezetésre került a poolConfigKey lehetősége a Redis kapcsolat beállításoknál.

[source,yaml]
----
coffee:
    redis:
        auth: #<1>
            host: sample-sandbox.icellmobilsoft.hu #default: localhost
            port: 6380 #default: 6380
            password: pass1234 #default: null
            database: 1 #default: 0
            # előző beállítás, megszünt
            #pool:
            #    maxtotal: 128 #default: 64
            #    maxidle: 32 #default: 16
            pool:
                default: #<2>
                    maxtotal: 128 #default: 64
                    maxidle: 32 #default: 16
                custom:
                    maxtotal: 12 #default: 64
                    maxidle: 3 #default: 16
            timeout: 5000 #default: 5000
----

==== Átállás

Mivel a Redis kulcsozási lehetőség megváltozott,
így a projekteknél a konfigurációnál át kell vezetni a "default" csoportot.
Többi változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilisek.

=== coffee-module-mp-opentracing

* *OpenTraceErrorResponseFilter* NPE hibát dobott olyan esetben amikor a kérés a filter láncban megakadt az opentrace filter előtt, ami nem tudott létrehozni
spant, pl ha authentikáció során nem várt hiba keletkezik az egy ilyen eset, mivel az auth az opentrace-től általában magasabb prioritason van.
Lekezelésre került a hiba, csak logolunk olyan esetben amikor nem tudunk a trace flowhoz hozzáadni mivel nem létezik.


==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest
* Bekerült egy defaultként használható OpenApiFilter amit a következő configuráció segítségével lehet aktiválni:
[source,properties]
----
mp.openapi.filter=hu.icellmobilsoft.coffee.rest.filter.OpenAPIFilter
----

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-cdi
* Deltaspike függőségek megszűntek, átkerültek a coffee-module-localization modulhoz. Ezzel együtt a `LogProducer.getAppLogger()` megszűnt,
helyette a `LogProducer.logToAppLogger(...)` használható, functional interface-t és class-t vár, magában kezeli az AppLogger létrehozását és megszüntetését.
* A `LogProducer`-ből kivezetésre a korábban már deprecated-nek minősített metódusok, amelyek helyett a `Logger.getLogger(...)` használható:
** createDefaultJbossLogger(InjectionPoint injectionPoint)
** getStaticLogger(Class<?> clazz)
** getStaticLogger(String className)
** getStaticDefaultLogger(Class<?> clazz)
** getStaticDefaultLogger(String className)
* Megszűnt dependencyk:
** deltaspike-core-api
** deltaspike-core-impl

==== Átállás
Mivel a coffee-cdi már nem húzza be a deltaspike dependencyket, ezért a projekt pom.xml-ben meg kell adni.

[source,xml]
----
<dependency>
	<groupId>org.apache.deltaspike.core</groupId>
	<artifactId>deltaspike-core-api</artifactId>
</dependency>
<dependency>
	<groupId>org.apache.deltaspike.core</groupId>
	<artifactId>deltaspike-core-impl</artifactId>
</dependency>
----

A `LogProducer.logToAppLogger(...)` használata.

[source,java]
----
...
LogProducer.logToAppLogger((AppLogger appLogger) -> appLogger.info(msg.toString()), DefaultLoggerClientRequestFilter.class))
...
----

