= v1.0.1 → v1.1.0

coff:ee v1.0.1 -> v1.1.0 migrációs leírás, újdonságok, változások leírása

== Változások
=== coffee-module-mongodb

* Frissült a mongo-java-driver (3.12.5).
* CDI extension bevezetése dinamikus MongoService gyártáshoz
* Hatékonyabb connection kezelés
* yml paraméterezhetőség

MongoDbHandler deprecated lett, helyette a MongoDbClient vagy a MongoService<T> kiterjeszáse használható.

[source,java]
----
// régi definíció
@Inject
@MongoCustomConfiguration(databaseName = "database", urlKey = "urlKey")
private MongoDbHandler mongoDbHandler;

mongoDbHandler.setCollection("collection");
mongoDbHandler.insertOne(dtoDocument);
----

helyett MongoDbClient használata

[source,java]
----
// uj használat
@Inject
@MongoClientConfiguration(configKey = "configKey")
private MongoDbClient mongoDbClient;

mongoDbClient.initRepositoryCollection(collection);
mongoDbClient.insertOne(dtoDocument);
----

MongoService használata POJO-val

[source,java]
----
// régi definíció
@Model
public class CustomMongoService extends MongoService<MongoEntity> {

    @Inject
    @MongoCustomConfiguration(databaseName = "database", urlKey = "urlKey")
    private MongoDbHandler mongoDbHandler;

    @Override
    protected MongoCollection<MongoEntity> getMongoCollection() throws BaseException {
        return mongoDbHandler.getDatabase().getCollection("collection", MongoEntity.class);
    }
}
    
@Inject
private CustomMongoService customMongoService;

----

helyett 

[source,java]
----
// uj használat
@Dependent
public class CustomMongoService extends MongoService<MongoEntity> {
}

@Inject
@MongoServiceConfiguration(configKey = "configKey", collectionKey = "collectionKey")
private CustomMongoService customMongoService;
----
*Pagination*

A MongoService find() metódus használat előtt *initRepositoryCollection(getMongoCollection())* hívás szükséges 
ha nem az új annotációval használjuk.
[source,java]
----
// régi definíció
@Model
public class CustomMongoService extends MongoService<MongoEntity> {

    public PagingResult<MongoEntity> findByQueryParams(...) {
        ...
        // MongoService pagination find
        // initRepositoryCollection(getMongoCollection());
        find(filter, order, rows, page, InvoiceLog.class);
        ...
    }
}

@Inject
private CustomMongoService customMongoService;
----
 
helyett, @MongoServiceConfiguration annotáció használatával a collection automatikusan betöltődik.
 
[source,java]
----
// régi definíció
@Dependent
public class CustomMongoService extends MongoService<MongoEntity> {

    public PagingResult<MongoEntity> findByQueryParams(...) {
        ...
        // MongoService pagination find
        find(filter, order, rows, page, InvoiceLog.class);
        ...
    }
}


@Inject
@MongoServiceConfiguration(configKey = "configKey", collectionKey = "collectionKey")
private CustomMongoService customMongoService;
----
=== Loggolás
Az `AppLogger`-en belül használt loggolási rendszer jboss-ról java.util.logging-ra lett cserélve,
hogy a coffee-t használó projektek ne legyenek jboss környezetre kényszerítve.
Ezzel együtt a CDI független osztályok kiszervezésre kerültek a `coffee-se-logging` modul-ba.
Egyelőre a visszafele kompatibilitás megmaradt, azonban deprecated lett, így érdemes átállni az alábbiak szerint:

==== Átállás


. jboss Logger inject
+
a korábbi jboss Logger helyett a saját coffee `hu.icellmobilsoft.coffee.se.logging.Logger`-t lehet használni.
Az osztály csere miatt a `org.jobss.logging.Logger.tracev` jellegű metódusokat is le kell cserélni pl. `hu.icellmobilsoft.coffee.se.logging.Logger.trace`-re (az Logger default támogatja a MessageFormat-al történő paraméterezést)
+
NOTE: Továbbra is működik a jboss Logger Inject-álása, azonban későbbi verzióban ez változhat.
+
.Coffee 1.0.0
[source,java]
----
import org.jboss.logging.Logger;
...
    @Inject
    private Logger log;
...
log.tracev("Some traced log:[{0}]", param);
----
+
.Coffee 1.1.0+
[source,java]
----
import hu.icellmobilsoft.coffee.cdi.logger.AppLogger;
...
    @Inject
    private AppLogger log;
...
log.trace("Some traced log:[{0}]", param);
----


. static logger
+
A `LogProducer.getStaticLogger` deprecated lett, helyette a `LogProducer.getStaticDefaultLogger` használható.
+
.Coffee 1.0.0
[source,java]
----
LogProducer.getStaticLogger(BlaBla.class).trace("class blabla");
----
+
.Coffee 1.1.0+
[source,java]
----
LogProducer.getStaticDefaultLogger(BlaBla.class).trace("class blabla");
----

=== MDC
MDC kezelés is saját rendszeren keresztül történik;
ahol projekt szinten eddig volt használva `org.jboss.logging.MDC`,
ott érdemes az import-ot `hu.icellmobilsoft.coffee.se.logging.mdc.MDC`-re cserélni. Bővebben: <<common_core_coffee-se_coffee-se-logging_MDC, MDC>>.