= v1.4.0 → v1.5.0

coff:ee v1.4.0 -> v1.5.0 migrációs leírás, újdonságok, változások leírása

== Változások

=== coffee-tool
Bevezetésre került a `StringUtil.maskUriAuthenticationCredentials` függvény.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-mongodb
Alkalmazva lett a `StringUtil.maskUriAuthenticationCredentials` függvény a `MongoDbClientFactory.createMongoClient`-ben
MongoDB uri maszkolásra log-oláskor.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redis
Bevezetésre került a *lpop* opcionális változata a `RedisService` osztályba,
és a párja *rpop*.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redisstream
A stream konzumer kezelése további minor változáson esett át hogy könyebben lehessen a projekten teszre szabni.
Létrejött egy `IRedisStreamPipeConsumer` mely célja a kiterjesztett stream fogyasztás lehetősége.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
