= v1.12.0 → v1.13.0

coff:ee v1.12.0 -> v1.13.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

=== coffee-tool

* A `JsonUtil.initGson()` kiegészítésre került egy `YearMonthConverter` nevű `java.time.YearMonth` type adapter osztállyal.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-dto-base

* Bevezetésre került az `InvalidParameterException`, alapértelmezetten `CoffeeFaultType.WRONG_OR_MISSING_PARAMETERS` hibakóddal, amely azt a célt szolgálja, hogy a metódusok paraméter ellenőrzésnél egységes kivételt dobjunk az érvénytelen paraméterek esetén.
Ilyen például tipikusan a public metódusok esetén a null check.
A bevezetés során ahol eddig érvénytelen paraméterre `BaseException`-t kiterjesztő kivételt dobtunk, most már `InvalidParameterException`-t dobunk.

==== Átállás

* Ajánlott a projekteken is egységesen az `InvalidParameterException` használata az érvénytelen paraméterek esetén.
* A `BaseService`-ből törlésre került a `newInvalidParameterException(String msg)` metódus, helyette közvetlenül az `InvalidParameterException` használata szükséges.
* Az `AbstractBaseAction`-ből törlésre került a `newInvalidParameterException(String msg)` metódus, helyette közvetlenül az `InvalidParameterException` használata szükséges.
* Az `IXsdHelper` és a `JaxbTool` osztályok metódusai most már `XsdProcessingException` helyett `BaseException`-t dobnak.
A változásokat szükséges lekövetni.
* A további metódusok, amelyeknél bevezetésre került az `InvalidParameterException` használata rendre `BaseException`-t dobtak, így azoknál nem történt változás.

=== coffee-rest

* Bevezetésre került a `BaseProcessingException`, amely azt a célt szolgálja, hogy a `MessageBodyReader`-t és `MessageBodyWriter`-t kiterjesztő osztályokból tudjunk `BaseException`-t dobni.
Eredetileg az `XsdProcessingExceptionWrapper`-t használtuk erre, de az dedikáltan csak `XsdProcessingException`-t csomagolt be, így ezt leváltottuk és töröltük.
Így most már nem csak `XsdProcessingException` dobása történhet meg a `MessageBodyReader` és `MessageBodyWriter` osztályokban, hanem bármilyen `BaseException`.

==== Átállás

* A `JsonMessageBodyReaderBase` és `XmlMessageBodyReaderBase` osztályok `readFrom()` metódusai most már `BaseException`-t kapnak el és `BaseProcessingException`-t dobnak `XsdProcessingExceptionWrapper` helyett.
A változásokat szükséges lekövetni a projekten használt / felülírt osztályokban.

== Változások

* Bump jackson-databind from 2.13.2.1 to 2.13.4.2 - DTO generátoroknál van használva.

=== coffee-module-configdoc

* A `coffee-module-configdoc` windows-on való fordítás során `java.lang.IllegalArgumentException: Invalid relative name: META-INF\config_keys.adoc` hibát eredményezett.
A probléma a `ConfigDocProcessor` és `DynamicConfigDocsProcessor` osztályokat érintette, ahol is a `processingEnv.getFiler().createResource()` hívásban Path alapján került átadásra a fájl elérése:

** Paths.get("META-INF/", "config_keys.adoc") -> "META-INF\config_keys.adoc"
** Paths.get("META-INF/", "dynamic_config_keys") -> "META-INF\dynamic_config_keys"

+
Ez azért probléma, mert az előbb említett metódus használni fogja a `JavacFileManager`-t, amiben történik egy `new URI(u)` példányosítás az `isRelativeUri(String u)` metódusban.
A `new URI(u)` pedig `URISyntaxException` kivételt fog eredményezni a fenti példákra a `\` jelek miatt.
A hiba úgy került kezelésre, hogy a `processingEnv.getFiler().createResource()` metódus hívásoknak minden esetben a fájl elérések a `/` jeles változattal kerülnek átadásra.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-jpa

* A `BatchService` `java.sql.Types.BOOLEAN` mentés esetén, oracle jdbc driver használatával `java.sql.SQLException: Invalid column type` hibát eredményezett.
A `null` értékű objektumok `prepared statement` beállítás esetén mentesítve lettek az SQL típusoktól és univerzálisan `java.sql.Types.NULL` kerül beállításra.
A `java.sql.Types.BOOLEAN` típusok külön ágban kerülnek kezelésre, amelyben ha a beállítandó érték `java.lang.Boolean`, akkor a `prepared statement` erre biztosított `setBoolean(int parameterIndex, boolean x)` metódusa van használva, egyébként pedig a `setObject(int parameterIndex, Object x)`, amelyben a driver-re bízzuk, hogy kezelje le az adott értéket.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* hu.icellmobilsoft.coffee.rest.utils.RequestUtil: kikerültek a WARN "ResourceMethodInvoker is null!!"
és "invokedMethod is null!!" üzenetek.
Kiderült hogy a nem létező objektum helyzet sok esetben és jogosan fordul elő.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
