= v1.3.0 → v1.4.0

coff:ee v1.3.0 -> v1.4.0 migrációs leírás, újdonságok, változások leírása

== Változások

=== coffee-model-base

* Auditált entitások `creationDate`, `creatorUser` mezői `updatable = false` property-t kaptak,
így a jövőben update esetén nem kerülnek a hibernate által futtatott SQL-be.

==== Átállás

Amennyiben van olyan entitás, amin a mezők már korábban lementett rekordon felülírásra kerülnek, úgy a felülírt értékek a továbbiakban az adatbázisba nem kerül lementésre, amennyiben erre mégis igény van, úgy projekt szinten kell saját `AbstractAuditEntity`-t implementálni.

== coffee-module-redisstream
Bevezetésre került a Consumer *retryCount* beállítás mint `@RedisStreamConsumer` úgy a configurációban is.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

== coffee-module-redis
Bevezetésre került a *lpop* művelet a `RedisService` osztályba.
Az *rpushRedisData* művelet a `RedisService` osztályban ezentúl válaszolja a lista méretét.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
