= v1.4.0 → v1.5.0

coff:ee v1.4.0 -> v1.5.0 migrációs leírás, újdonságok, változások leírása

== Változások

* Bump guava 25.1-jre -> 29.0-jre - A frissítést a https://github.com/advisories/GHSA-5mg8-w23w-74h3 indította.
Mivel a coff:ee csak használt dependencyket köti be,
engedélyezni kellett com.google.guava:failureaccess függőséget,
ami a https://github.com/google/guava/releases/tag/v27.0 verzióval kötelezővé vált:
https://groups.google.com/g/guava-announce/c/Km82fZG68Sw .

=== coffee-tool
Bevezetésre került a `StringUtil.maskUriAuthenticationCredentials` függvény.

Bevezetésre került a Duration-ök szerializálásának/deszerializálásának támogatása a JsonUtil-ban (DurationConverter.class).

==== Átállás
A változtatások hatására a Duration Json deszerializálása megváltozott.
Eddigi formátum: "duration":{"signum":1,"years":1,"months":1,"days":1,"hours":1,"minutes":1,"seconds":1}
Jelenlegi formátum: "duration":"P1Y1M1DT1H1M1S" (ISO 8601 szabvány szerinti)

Ennek értelmében a változtatás visszafele nem teljesen kompatibilis. A változtatások átállási munkálatokat eredményezhetnek.
Az átállás segítésére és a könnyebb megértése érdekében kibővült a dokumentáció a 'Json támogatás' leírásával a link:../common/core/coffee-rest.adoc[coffee-rest] modulban

=== coffee-module-mongodb
Alkalmazva lett a `StringUtil.maskUriAuthenticationCredentials` függvény a `MongoDbClientFactory.createMongoClient`-ben
MongoDB uri maszkolásra log-oláskor.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redis
Bevezetésre került a *lpop* opcionális változata a `RedisService` osztályba,
és a párja *rpop*.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redisstream
A stream konzumer kezelése további minor változáson esett át hogy könyebben lehessen a projekten testre szabni.
Létrejött egy `IRedisStreamPipeConsumer` mely célja a kiterjesztett stream fogyasztás lehetősége.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

A `BaseApacheHttpClient`-ben módosítás történt a logolással kapcsolatban.
Mostantól a POST és PUT műveletek, `byte[]` body paraméter esetén a logolás szintjétől függően logolják az üzenetet.
TRACE és DEBUG esetén a teljes üzenet kerül logolásra, míg INFO szinten csak az első 80 karakter.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
