= v1.7.0 → v1.8.0

coff:ee v1.7.0 -> v1.8.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

=== coffee-dto

* Létrejött az UtcOffsetDateTimeXmlAdapter és az UtcOffsetTimeXmlAdapter.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redis
* Szét lett választva a consumer és a producer config. Külön poolból dolgoznak.

==== Átállás
* Az új verzióban ha azt szertnénk, hogy a producerünk vagy consumerünk önálló pool-al rendelkezzen, az inject-nél még fel kell annotálni az új Qualifierek egyikével:
@ConsumerPool/@ProducerPool.
Ha mindkettővel alátnánk, akkor azt a StreamAnnotationProcessor elbuktatná.
* A változtatások érintik a korábbi konfigurációs kulcsok szerkezetét.
régi:
```
coffee:
    redisstream:
        enabled: true
        sampleGroup:
    stream:
        maxlen: 10
        read:
            timeoutmillis: 60000
    consumer:
        threadsCount: 2
```
új:
```
coffee:
    redisstream:
        sampleGroup: #
            stream:
                read:
                    timeoutmillis: 60000 #default: 60000
            producer:
                maxlen: 10000 #default none
                ttl: 300000 #millisec, default none
            consumer:
                threadsCount: 2 #default: 1
                retryCount: 2 #default: 1
```

== Változások

=== coffee-rest
* "coffee.app.name" paraméterben megadható érték már nem kötelező, alapértelmezetten a "java:app/AppName" van használva.
* JaxbTool kiegészítése `byte[]` fogadására képes unmarshalXML metódusokkal

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-jpa
* A `BatchService` automatán beállítja az átadott entitások verzióját

==== Átállás
* Ha a batch mentés után kézzel lett a verzió növelve, azt meg kell szüntetni


=== coffee-model-base
* A 2 `AbstractIdentifiedAuditEntity` osztály (`java.util.Date` és `OffsetDateTime`-on alapuló) kapott egy közös generikus interface-t

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
