= v1.8.0 → v1.9.0

coff:ee v1.8.0 -> v1.9.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

=== JDK 17 support
A projekt mostmár támogatja a java 17 verziót,
így használható ilyen java alapon lévő projektben is.
A problémás részek legtöbb helyen dependency frissítéssel megjavult,
az egyetlen problémás rész a gson használata.

.gson
Ez a modul függőség reflection alapon működik (több hivatalos issue van ezzel kapcsolatban a gson projekten),
ami a java17-el korlátozva van így a teszteseteknél konfigurációra van szükség.
Várhatóan az implementált projektenél is fog kelleni a következő jvm paraméter:

[source,bash]
----
--add-exports=java.xml/com.sun.org.apache.xerces.internal.jaxp.datatype=ALL-UNNAMED
--add-opens=java.xml/com.sun.org.apache.xerces.internal.jaxp.datatype=ALL-UNNAMED
----
A későbbi verziókban felülvizsgáljuk a függőséget.

.java 11 && 17
A coff:ee 1.x.x továbra is java 11-el lessz kompilálva,
de kap fordítási és tesztelési ellenőrzéseket java 17-re is.
Így minimalizálni fogjuk a java verzió külömbségi problémákat.

==== BOM verzió emelések:
* google.code:gson 2.8.3 -> 2.8.9
* junit:jupiter 5.5.2 -> 5.8.1
* org.jboss.weld:weld-junit5 2.0.1.Final -> 2.0.2.Final


=== coffee-module-configdoc
* Létrejött a modul

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-tool
* DateXmlUtil -> XmlGregorianCalendar optimalizálása: DatatypeFactory.newInstance() példány cacheből kiszolgálása performancia okokból

=== coffee-module-mongodb
* DatatypeFactory.newInstance() cachelt példány lekérése DateXmlUtil alapján

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

== Változások

=== Általános

==== Java EE 8 -> Jakarta EE 8 átállás
Az elsőként kiadott jakarta verzió package és osztály szinten teljesen megegyezik
a korábbi Java EE 8-cal, csupán maven koordinátákban tér el.

==== Átállás

* Le kell cserélni a `javax`  dependency-ket a https://wiki.eclipse.org/Jakarta_EE_Maven_Coordinates[megfelelő
`jakarta` párjára], például:
+
.javax
[source,xml]
----
<dependency>
    <groupId>javax</groupId>
    <artifactId>javaee-api</artifactId>
    <version>8.0</version>
    <scope>provided</scope>
</dependency>
----
+
.jakarta
[source,xml]
----

<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-api</artifactId>
    <version>8.0.0</version>
    <scope>provided</scope>
</dependency>
----
+
Vagy külön kezelt dependency-k esetében:
+
.javax
[source,xml]
----
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
    <scope>provided</scope>
</dependency>
----
+
.jakarta
[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.2</version>
    <scope>provided</scope>
</dependency>
----
+
* Ellenőrizni kell a tranzitíven behúzott függőségeket is, az átállás után a projektben nem maradhat `javax`-os függőség,
mert ez nem várt hibákat eredményezhet. Ehhez használhatjuk a maven dependency-plugin `dependency:tree` goal-ját.
Előfordulhat, hogy projekt szinten kihasználtuk kódban az exclude-olt tranzitív dependecy-t, ilyenkor fordítási hibát
fogunk kapni, amit javíthatunk, ha felvesszük az exclude-olt `javax` artifact `jakarta` párját a dependency-k közé.