= v1.11.0 → v1.12.0

coff:ee v1.11.0 -> v1.12.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

=== coffee-jpa

* Bevezetésre került a link:#TransactionHelper[TransactionHelper] osztály.

=== coffee-rest

* Létrejött egy új MessageBodyWriter,
ami a `application/octet-stream` + `BaseResultType` válaszokat kezeli.
Alapértelmezetten aktiválva van,
mivel nem volt ehhez hasonló megoldás a rendszerben és a Resteasy sem nyújtott semmi választ ilyenkor,
csak elnyelte a response body-t.

==== Átállás

Csak ott érinthet valamit amikor `application/octet-stream` mediatype a várt válasz és elszálás
történik a távoli stream előállításnál.
Meglehet hogy ezekre az esetekre valami egyedi mapper/writter lekezelés volt a projektben.

== Változások

=== coffee-tool

* RandomUtil osztályban a generateId a javadoc-ban írt 16 karakter helyett 17-et is tudott visszaadni, mert a getNextIndex metódusban tovább tudott futni az index 1296-ig is, amit a generateId-ban 36-os számrendszerben 100-ra alakított, így túllépett. Javítás 1295-ig engedi az indexet.

* ConfigUtil osztályban a default configok betöltése az újabb Smallrye Config (Microprofile config implementáció) verzióban nagyon CPU igényes lett, ezért singleton megvalósítás került a betöltésre.

==== Átállás

* A ConfigUtil osztályban való változtatás miatt az eddigi `ConfigUtil.defaultConfig()` helyett `ConfigUtil.getInstance().defaultConfig()`.

=== coffee-module-redisstream
* `coffee.redisstream.{0}.consumer.manualAck` konfiguráció bevezetése. Lásd: link:#common_module_coffee-module-redisstream-config[coffee-module-redisstream konfiguráció]

==== Átállás
* Amennyiben a régi működést szeretnénk alkalmazni, azaz ha exception-t dob a redis stream consumer,
akkor ne történjen `XACK`, akkor a stream konfigjában fel kell venni a `coffee.redisstream.{0}.consumer.manualAck` kulcsot `true` értékkel.

=== coffee-module-mp-restclient
* `DefaultBaseExceptionResponseExceptionMapper` fel lett készítve "application/octet-stream" válaszra.
Ilyenkor megpróbálja a streamben válaszolt `BaseExceptionResultType`-ot json vagy xml szerint felparszolni. 

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-jpa

* A *BatchService* insert és update metódusai *java.util.Date* beállítása esetén *cannot cast 'java.util.Date' to 'java.sql.Timestamp'* hibát dobtak (coffee 1.10.0 óta).
A *setPsObject()* metódusban innentől az alap hibernate típusok egységesen a *SingleColumnType* ősre kerülnek ellenőrzésre.
Ez magában foglalja, hogy az adott érték pontosan milyen *java.sql.Types*-nak van megfeleltetve, így most már a megfelelő típus szerint kerül beszúrásra minden ilyen érték.
Ezenkívül a *java.sql.Types.TIME* és *java.sql.Types.TIMESTAMP* szerint külön ellenőrzés van érték beállításra, amelyekben nézzük, hogy a *hibernate.jdbc.time_zone* be van állítva a *persistence.xml*-ben.
Ha be van állítva, akkor az érték szerinti *instanceof* alapján végezzük el a megfelelő időzóna szerinti beállításokat.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
