= v1.7.0 → v1.8.0

coff:ee v1.7.0 -> v1.8.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

* log level optimalizáció

=== coffee-dto
* Létrejött az UtcOffsetDateTimeXmlAdapter és az UtcOffsetTimeXmlAdapter.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

== Változások

=== coffee-rest
* "coffee.app.name" paraméterben megadható érték már nem kötelező, alapértelmezetten a "java:app/AppName" van használva.
* JaxbTool kiegészítése `byte[]` fogadására képes unmarshalXML metódusokkal
* DefaultBaseExceptionMapper létrehozása a beépített BaseException-k kezelésére

==== Átállás
* A deprecated InvalidRequestException és SaxParseBaseException törlésre került, helyettük a XsdProcessingException használata ajánlott
* DefaultBaseExceptionMapper-re átállás. Ha van projekt specifikus kivétel amit kezelni szeretnénk, akkor ki
kell terjeszteni a mappert az alábbi módon:
[source,java]
----
@Provider // <1>
public class BaseExceptionMapper extends DefaultBaseExceptionMapper {

    @Override // <2>
    protected Response handleException(BaseException e) {
        if (e instanceof SampleException) {
            return createResponse(e, Response.Status.BAD_REQUEST, new BusinessFault());
        }

        return super.handleException(e);
    }
}
----
<1> @Provider-ként szükséges kiterjeszteni a DefaultBaseExceptionMapper
<2> handleException @Override, ha szükséges projekt specifikus exception mappelése

=== coffee-jpa
* A `BatchService` automatán beállítja az átadott entitások verzióját

==== Átállás
* Ha a batch mentés után kézzel lett a verzió növelve, azt meg kell szüntetni


=== coffee-model-base
* A 2 `AbstractIdentifiedAuditEntity` osztály (`java.util.Date` és `OffsetDateTime`-on alapuló) kapott egy közös generikus interface-t

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-csv
* opencsv upgrade 3.9 -> 5.5.2

==== Átállás
* `@CsvBind` annotációkat cserélni kell `@CsvBindByNamePosition`-re
