= v1.12.0 → v1.13.0

coff:ee v1.12.0 -> v1.13.0 migrációs leírás, újdonságok, változások leírása

== Változások

* Bump jackson-databind from 2.13.2.1 to 2.13.4.2 - DTO generátoroknál van használva.

=== coffee-module-configdoc

* A `coffee-module-configdoc` windows-on való fordítás során `java.lang.IllegalArgumentException: Invalid relative name: META-INF\config_keys.adoc` hibát eredményezett.
A probléma a `ConfigDocProcessor` és `DynamicConfigDocsProcessor` osztályokat érintette, ahol is a `processingEnv.getFiler().createResource()` hívásban Path alapján került átadásra a fájl elérése:

** Paths.get("META-INF/", "config_keys.adoc") -> "META-INF\config_keys.adoc"
** Paths.get("META-INF/", "dynamic_config_keys") -> "META-INF\dynamic_config_keys"

+
Ez azért probléma, mert az előbb említett metódus használni fogja a `JavacFileManager`-t, amiben történik egy `new URI(u)` példányosítás az `isRelativeUri(String u)` metódusban.
A `new URI(u)` pedig `URISyntaxException` kivételt fog eredményezni a fenti példákra a `\` jelek miatt.
A hiba úgy került kezelésre, hogy a `processingEnv.getFiler().createResource()` metódus hívásoknak minden esetben a fájl elérések a `/` jeles változattal kerülnek átadásra.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-jpa

* A `BatchService` `java.sql.Types.BOOLEAN` mentés esetén, oracle jdbc driver használatával `java.sql.SQLException: Invalid column type` hibát eredményezett.
A `null` értékű objektumok `prepared statement` beállítás esetén mentesítve lettek az SQL típusoktól és univerzálisan `java.sql.Types.NULL` kerül beállításra.
A `java.sql.Types.BOOLEAN` típusok külön ágban kerülnek kezelésre, amelyben ha a beállítandó érték `java.lang.Boolean`, akkor a `prepared statement` erre biztosított `setBoolean(int parameterIndex, boolean x)` metódusa van használva, egyébként pedig a `setObject(int parameterIndex, Object x)`, amelyben a driver-re bízzuk, hogy kezelje le az adott értéket.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* hu.icellmobilsoft.coffee.rest.utils.RequestUtil: kikerültek a WARN "ResourceMethodInvoker is null!!"
és "invokedMethod is null!!" üzenetek.
Kiderült hogy a nem létező objektum helyzet sok esetben és jogosan fordul elő.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
