= v1.1.0 → v1.2.0

coff:ee v1.1.0 -> v1.2.0 migrációs leírás, újdonságok, változások leírása

== Változások

=== coffee-cdi
* LogContainer-ben a különböző logszintek megadásánál, a formázott üzenetekhez használt több argumentum megadási lehetőségek közül, csak a Varargs maradt meg (multiple arguments).
* LogContainer logjai automatikusan kapnak létrejöttükkor egy LocalDateTime.now() -t, ami a logok kiírásakor is kiíródik.
* LogContainer-ben Throwable kiírásakor most már a paraméterben kapott üzenet is kiíródik, valamint struktúráltabban íródik ki hozzá a stacktrace.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-dto
* common.xsd-ben a TimestampType típust leíró regex bővítésre került, a törtmásodperceket a korábbi 3 helyett 6 jegy pontossággal képes befogadni.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* RequestResponseLogger válasz kiíráatás kibővült xml kiírással, ha a mediaType application/xml,text/xml vagy application/atom+xml.
* RequestResponseLogger válasz kiíráatásnál, a json kiírás is mediaType függővé lett téve.
* RequestResponseLogger válasz kiíráatásnál minden egyéb, nem String objektum esetben, az objektum toString() metódusával kerül kiírásra a válasz objektum.
* BaseServicePath osztály átkerült a coffee-dto csomagba.
* ApplicationConfiguration - ha nem talál a konfigurációs kulcshoz értéket - ezentúl csak egy WARN sort logol, stacktrace nélkül.
* JsonMessageBodyReaderBase összes metódusa kiterjeszthető.

==== Átállás

A `BaseServicePath` osztályt ősként használó osztályok-ban az importot meg kell változtatni:
`hu.icellmobilsoft.coffee.rest.url.BaseServicePath` -> `hu.icellmobilsoft.coffee.dto.url.BaseServicePath`

=== coffee-tool
* DateUtil osztályhoz hozzáadásra került egy LocalDate-ről Date-re konvertáló metódus.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-mp-restclient
* Default ResponseExceptionMapper<BaseException> implementáció

==== Átállás

A default ResponseExceptionMapper<BaseException> priority nélkül lett létrehozva, attól eltérő implementáció használata priority megadásával lehetséges.

=== coffee-dto-base
* InvalidRequestException deprecated
* SaxParseBaseException deprecated

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
A két exception nincs használatban, szerepüket az XsdProcessingException tölti be.