= v1.12.0 → v1.13.0

coff:ee v1.12.0 -> v1.13.0 migrációs leírás, újdonságok, változások leírása

== Változások

=== coffee-module-configdoc

* A `coffee-module-configdoc` windows-on való fordítás során `java.lang.IllegalArgumentException: Invalid relative name: META-INF\config_keys.adoc` hibát eredményezett.
A probléma a `ConfigDocProcessor` és `DynamicConfigDocsProcessor` osztályokat érintette, ahol is a `processingEnv.getFiler().createResource()` hívásban Path alapján került átadásra a fájl elérése:

** Paths.get("META-INF/", "config_keys.adoc") -> "META-INF\config_keys.adoc"
** Paths.get("META-INF/", "dynamic_config_keys") -> "META-INF\dynamic_config_keys"

+
Ez azért probléma, mert az előbb említett metódus használni fogja a `JavacFileManager`-t, amiben történik egy `new URI(u)` példányosítás az `isRelativeUri(String u)` metódusban.
A `new URI(u)` pedig `URISyntaxException` kivételt fog eredményezni a fenti példákra a `\` jelek miatt.
A hiba úgy került kezelésre, hogy a `processingEnv.getFiler().createResource()` metódus hívásoknak minden esetben a fájl elérések a `/` jeles változattal kerülnek átadásra.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
