= v1.10.0 → v1.11.0

coff:ee v1.10.0 -> v1.11.0 migrációs leírás, újdonságok, változások leírása

== Változások

=== coffee-module-redis

* *JedisDataException TechnicalException*-be lett wrap-olva, így a régi logika nem tudta lekezelni azt, ezért a *cause*-ban
lévő *JedisDataException* kezelésére kellett módosítani a folyamtot.
* `RedisStreamConsumerExecutor`-ban a `handleGroup` lezárta a jedis connection-t amit a `consumeOne` még használt volna,
így exception keletkezett.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-mp-opentracing

* *OpenTraceErrorResponseFilter* NPE hibát dobott olyan esetben amikor a kérés a filter láncban megakadt az opentrace filter előtt, ami nem tudott létrehozni
spant, pl ha authentikáció során nem várt hiba keletkezik az egy ilyen eset, mivel az auth az opentrace-től általában magasabb prioritason van.
Lekezelésre került a hiba, csak logolunk olyan esetben amikor nem tudunk a trace flowhoz hozzáadni mivel nem létezik.


==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
