= v1.14.0 → v1.15.0

coff:ee v1.14.0 -> v1.15.0 migrációs leírás, újdonságok, változások leírása

=== coffee-tool

** JsonUtil használatával is lehetséges a generikus típusok deszerializációja.
** Új `ParamValidatorUtil` segédosztály publikus függvények paramétereinek egységes validációjára.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.


=== coffee-jpa

** microprofile-health támogatást kapott

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redis

** microprofile-health támogatást kapott

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-etcd

** microprofile-health támogatást kapott

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-model-base

** `AbstractEntity.toString()` fgv-e `java.sql.Blob` és `java.sql.Clob` típusok esetén a mező értéke helyett a mező típusát használja fel.
Korábban a mező értékével dolgozott ilyen esetekben is, így pl logozás esetén felolvasta a stream-et.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest
* *RequestResponseLogger memoria tuning*: A `BaseRestLogger` osztály alapján létrejött egy optimalizált változat: `hu.icellmobilsoft.coffee.rest.log.optimized.BaseRestLoggerOptimized`. Segítségével az alkalmazások kevesebb memóriát használnak fel a request és response body log-olás során. Emellett létrehozásra került a `hu.icellmobilsoft.coffee.rest.log.optimized.RequestResponseLoggerOptimized` osztály is, ahol a request és response entity logolások hossza meghatározásra kerül miszerint, ha a request vagy response entity `application/octet-stream` vagy `multipart/form-data` és nem szerepel a REST interface-en LogSpecifier annotáció, akkor korlátozzuk a log méretet. Valamint a `BYTECODE_MAX_LOG` konstans átvevezésre került `ENTITY_MAX_LOG`-ra.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
