= v1.13.0 → v1.14.0

coff:ee v1.13.0 -> v1.14.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

Bevezetésre került a https://grpc.io/[gRPC] támogatása.
Ennek köszönhetően létrejöt új subprojekt gyűjtő `coffee-grpc` néven.

=== coffee-grpc
Következő funkció támogatások kerültek a rendszerbe:

* coffee-grpc-api - Általános gRPC kezelés Coff:ee API (annotációk, verzió, ...)
* coffee-grpc-base - protobuf és gRPC stub általános gyűjtője
* coffee-grpc-protoc - proto -> class generálás támogatása
* coffee-dto/coffee-dto-xsd2proto - Generált proto fájlok ami a `coffee-dto-xsd` XSD fájlokból vannak generálva.
* coffee-dto/coffee-dto-stub-gen - Generált osztályok a Coff:ee proto fajlokból 

== Változások

=== coffee-jpa

* A `BaseService` `repositoryFailed` metódusa `java.lang.IllegalArgumentException: can't parse argument number: explicit` hibát eredményezett olyan `org.hibernate.QueryException` esetén melynek üzenetében kapcsos zárójel is szerepelt (pld. `fetched association was not present in the select list [FromElement{explicit,not a collection join`). A `MessageFormat.format` úgy érzékelte, hogy ott egy paraméter placeholder van és megpróbált értéket behelyttesíteni a helyére.
A hiba úgy került kezelésre, hogy egy új param placeholder került az üzenetbe `params.length` helyi értékkel, valamint az Exception `getLocalizedMessage` értéke hozzá lett fűzve az eredeti paraméter tömbhöz.
* Deltaspike tranzakció kezelése helyett javax `@javax.transaction.Transactional` használatát, rollback paraméter testreszabásával.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

== coffee-module-notification-action

* Az email és push esetén az adatbázis mentés a deltaspike-os tranzakció kezelés helyett a coffee-ban testreszabott `hu.icellmobilsoft.coffee.jpa.annotation.Transactional` annotációt kapta.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

== coffee-module-etcd

* A `hu.icellmobilsoft.coffee.module.etcd.util.EtcdClientBuilderUtil`-ba bevezetésre került a CONNECT_TIMEOUT_MILLIS paraméter, 
ez megakadályozza a felfutásnál előforduló timeout hibákat, amik a lekérdezés és az etcd szerverhez való timeout paraméter eltérése okozott.
* Bump io.etcd:jetcd-core 0.6.1 -> 0.7.5

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.