= v2.0.0 → v2.1.0

coff:ee v2.0.0 -> v2.1.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

Bevezetésre került a https://grpc.io/[gRPC] támogatása.
Ennek köszönhetően létrejöt új subprojekt gyűjtő `coffee-grpc` néven.

=== coffee-grpc
Következő funkció támogatások kerültek a rendszerbe:

* coffee-grpc-api - Általános gRPC kezelés Coff:ee API (annotációk, verzió, ...)
* coffee-grpc-base - protobuf és gRPC stub általános gyűjtője
* coffee-grpc-protoc - proto -> class generálás támogatása
* coffee-dto/coffee-dto-xsd2proto - Generált proto fájlok ami a `coffee-dto-xsd` XSD fájlokból vannak generálva.
* coffee-dto/coffee-dto-stub-gen - Generált osztályok a Coff:ee proto fajlokból
* coffee-grpc-server-extension - CDI gRPC szerver implementáció támogatása
* coffee-grpc-client-extension - CDI gRPC client implementáció támogatása

== Változások

=== coffee-module-etcd

** Bump io.etcd:jetcd-core 0.6.1 -> 0.7.5

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

