= v2.4.0 → v2.5.0

coff:ee v2.4.0 -> v2.5.0 migrációs leírás, újdonságok, változások leírása

=== coffee-tool

* Létrejött új "AES/CBC/PKCS5PADDING" kódoló osztály
(`hu.icellmobilsoft.coffee.tool.utils.crypto.AesCbcCryptoUtil`)
* Hozzá adva a SHA3-512 kódoló metódus a `hu.icellmobilsoft.coffee.tool.utils.string.EncodeUtil` osztályhoz,
régi `Sha512(String str)` kivezetésre fog kerülni.
* MavenURLHandler osztályban aktuális szál alapotú resource lekérést kerül.

==== Migration

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redisstream

* Graceful leállítást segítű működést kaptak a redis consumerek
(`hu.icellmobilsoft.coffee.module.redisstream.bootstrap.ConsumerLifeCycleManager`)

==== Migration

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* Ha nincs definiálva a version a validateXMLs annotációban, akkor nem próbálja meg kiolvasni a requestVersion a requestből.

==== Migration

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-mongodb

* A `@Deprecated(forRemoval = true, since = "1.1.0")` annotációval ellátott oszályok és metódusok törlése.
* Az implementálatlan, használaton kívüli metódus törlése: `hu.icellmobilsoft.coffee.module.mongodb.service.MongoService#getMongoCollection()`

==== Migration

* A `hu.icellmobilsoft.coffee.module.mongodb.annotation.MongoConfiguration` osztály helyett ezt az osztályt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoClientConfiguration`
* A `hu.icellmobilsoft.coffee.module.mongodb.config.MongoDbConfig` osztály helyett ezt az osztályt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoConfigHelper`
* A `hu.icellmobilsoft.coffee.module.mongodb.config.MongoDbConfigImpl` osztály helyett ezt az osztályt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoClientConfiguration`
* A `hu.icellmobilsoft.coffee.module.mongodb.handler.MongoDbHandler` osztály helyett ezt az osztályt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClient`
* A `hu.icellmobilsoft.coffee.module.mongodb.producer.MongoFactory` osztály helyett ezt az osztályt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClientFactory`
* A `hu.icellmobilsoft.coffee.module.mongodb.service.MongoServiceImpl` osztály helyett ezt az osztályt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClient`
* A `hu.icellmobilsoft.coffee.module.mongodb.service.MongoService#getMongoCollection()`  metódus helyett ezt kell használni: `hu.icellmobilsoft.coffee.module.mongodb.extension.MongoDbClient#initRepositoryCollection(java.lang.String)`