= v2.7.0 → v2.8.0

coff:ee v2.7.0 -> v2.8.0 migrációs leírás, újdonságok, változások leírása

== Global

=== coffee-jpa

💥 ***BREAKING CHANGE*** 💥

A `hu.icellmobilsoft.coffee.jpa.sql.batch.BatchService` átalakítások:

* A `BatchService` Hibernate függősége megszünt (a `coffee-jpa`-nak továbbra is függősége a Hibernate).
* Típusa osztályból interface lett.
* Ős interface az új `hu.icellmobilsoft.coffee.jpa.sql.batch.IJpaBatchService`.
* Implementációja a Frapp:EE projekt `frappee-hibernate` modulba lett átmozgatva.

==== Átállás

A `hu.icellmobilsoft.coffee.jpa.sql.batch.BatchService` használata:

* Be kell behúznunk a `hu.icellmobilsoft.frappee:frappee-hibernate` modult a függőségek közé és készen is vagyunk. Itt
 található a `hu.icellmobilsoft.frappee.batch.hibernate.HibernateBatchService` implementáció.
* Ha kiterjesztettük a korábbi `BatchService`-t, akkor a `HibernateBatchService`-t kell kiterjesztenünk.
Bővebb információ a Frapp:EE dokumentációban található.

=== coffee-rest

* Több xml katalógus fájl támogatása `,` jellel elválasztva
* Marshalling esetén megadható a `JaxbTool`-nak több osztály, amit hozzá szeretnénk adni a `JAXBContext`-hez

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
