= v2.7.0 → v2.8.0

coff:ee v2.7.0 -> v2.8.0 migrációs leírás, újdonságok, változások leírása

== Global

Dependency csere: `org.hibernate:hibernate-core` -> `org.hibernate.orm:hibernate-core` (a korábbi csak egy proxy volt már).

=== coffee-jpa

💥 ***BREAKING CHANGE*** 💥

A `hu.icellmobilsoft.coffee.jpa.sql.batch.BatchService` megszűnt és átmozgatásra került a frapp:ee projektbe a
függőségeivel együtt, úgy mint `BatchMode`, `Status` és `StringBasicType`.

==== Átállás

* Be kell behúznunk a `hu.icellmobilsoft.frappee:frappee-jpa-batch-api` modult a függőségek közé.
* A korábbi `BatchService` helyett a `hu.icellmobilsoft.frappee.jpa.batch.IJpaBatchService` használandó.
* Az `IJpaBatchService` Hibernate-es implementációja `hu.icellmobilsoft.frappee:frappee-hiberante-batch` modulban
 található `HibernateBatchService` néven.
* A `HibernateBatchService` JakartaEE 10-es producerét a `frappee-hiberante-batch-jee10` modul szolgáltatja
 `HibernateBatchServiceProducer` néven.
* Ha kiterjesztettük a korábbi `BatchService`-t, akkor a `HibernateBatchService`-t kell kiterjesztenünk és
 kell készíteni hozzá egy producert is. Bővebb információ a Frapp:EE dokumentációban található.

=== coffee-dto-base

`TechnicalException` deprecated lett, helyette a `coffee-se-api`-ba átmozgatott
 `hu.icellmobilsoft.coffee.se.api.exception.TechnicalException` használandó.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis. Javasolt az
 új `hu.icellmobilsoft.coffee.se.api.exception.TechnicalException` használata.

=== coffee-tool

* A `RandomUtil` deprecated lett, helyette a `coffee-se-util` modulban található
 `hu.icellmobilsoft.coffee.se.util.string.RandomUtil` használandó.
* A `MavenURLHandler` optimalizálva lett a Quarkus csomagoláshoz.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis. Javasolt a
 `hu.icellmobilsoft.coffee.se.util.string.RandomUtil` használata.

=== coffee-se-api

`hu.icellmobilsoft.coffee.se.api.exception.TechnicalException` bevezetése.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-se-util

Új coff:ee modul. Utility osztályok gyűjteménye.

A `hu.icellmobilsoft.coffee.se.util.string.RandomUtil` bevezetése.

* A `generateToken()` metódus `public` módosítót kapott, ellentétben a régi RandomUtil osztállyal, ahol `protected` volt.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-mode-base

Az `EntityIdGenerator` az azonosító generáláshoz a `coffee-se-util`-ba átmozgatott `RandomUtil`-t használja.
Implementációja 100%-ban megegyezik a korábban itt található megoldással.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* Több xml katalógus fájl támogatása `,` jellel elválasztva
* Marshalling esetén megadható a `JaxbTool`-nak több osztály, amit hozzá szeretnénk adni a `JAXBContext`-hez

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-grpc

** microprofile-health támogatás

** Külön managed-executor-service használata (java /ee/concurrency/executor/grpc) a gRPC hívásokhoz.
A `managed-executor-service` konfigurációja a `coffee-grpc-server-extension` dokumentációban van bemutatva.

** GrpcClientConfig kibővítve a requestLogSize és a responseLogSize paraméterekkel,
ezek a kliens kérés és válasz maximális log méretének korlátozására szolgálnak karakterekben,
a limit feletti karakterek levágásra kerülnek.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module

* A `@ConfigDoc` annotáció által generált adoc fájlban az emoji információ leírás címsora törölve lett.

==== Átállás

* A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-dto-base

Új XSD simple type-okkal bővült a `http://common.dto.coffee.icellmobilsoft.hu/common` névterű XSD:

* DateType - xsd:date típus yyyy-MM-dd formátummal
* TimestampWithoutMillisType - xsd:dateTime típus yyyy-MM-ddTHH:mm:ssZ formátummal

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-se-io

Új modul.

* `SizeLimitExceededIOException`: InputStream olvasás közben elértük a limitet.
* `LimitedSizeInputStream`: Olyan InputStream, ami `SizeLimitExceededIOException`-t dob ha a stream olvasása közben eléri a
beállított limitet.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
