= v2.1.0 → v2.2.0

coff:ee v2.1.0 -> v2.2.0 migrációs leírás, újdonságok, változások leírása

=== coffee-tool

** JsonUtil használatával is lehetséges a generikus típusok deszerializációja.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-jpa

** microprofile-health támogatást kapott

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redis

** microprofile-health támogatást kapott
** Jedis kapcsolati metrikát szolgáltat

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-etcd

** microprofile-health támogatást kapott

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-base

** ClassFieldsAndMethodsCache ConcurrentModificationException hibát okozott nagy terhelés alatt.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

** hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXML és hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXMLs annotációk átkerültek a coffee-dto-base modulba.

==== Átállás

A változás path változással járt, amit esetlegesen le kell követni az implementációs helyen:

* hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXML -> hu.icellmobilsoft.coffee.*dto*.validation.xml.annotation.ValidateXML
* hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXMLs -> hu.icellmobilsoft.coffee.*dto*.validation.xml.annotation.ValidateXMLs
