= v2.13.0 → v2.14.0

coff:ee v2.13.0 -> v2.14.0 migrációs leírás, újdonságok, változások leírása

== Global

* ETCD driver verzió frissítése 0.8.5 -> 0.8.6
* io.grpc verzió frissítés 1.70.0 -> 1.76.0

== coffee-se-util

* `RandomUtil.generateId` optimalizálva lett, most harmad annyi idő alat fut le, mint előtte

=== Migration
A változtatások visszafelé kompatibilisek, migrációs lépés nem szükséges.

== coffee-tool

* `GZIPUtil` metódusok overload-old verziót kaptak `initialBufferSize` paraméterrel,
így ha van egy becsült kimeneti méreted, nagymértékben csökkentheted a heap garbage keletkezését nagy fájlok esetén.
Valamint a régi metódusok a bemeneti adatokon alapuló heurisztikákat használtak az `initialBufferSize` kiszámításához.

=== Migration
A változtatások visszafelé kompatibilisek, migrációs lépés nem szükséges.

== coffee-deltaspike-api

* API osztályok ki lettek emelve a `coffee-deltaspike-data` modulból az új `coffee-deltaspike-api` modulba.

=== Migration
A változtatások visszafelé kompatibilisek, migrációs lépés nem szükséges.
