= v2.10.0 → v2.11.0

coff:ee v2.10.0 -> v2.11.0 migrációs leírás, újdonságok, változások leírása

=== coffee-tool
* GZipUtil kapott néhány új metódust a kisebb memóriahasználatért, valamint DTO/JSON tömörítésre
* Hozzáadásra került egy RandomSplitGenerator osztály
* Hozzáadásra került az EvictAction, hogy az Evictable-t implementáló osztályokat egységesen meg lehessen hívni cache törlés szempontjából.
* JsonbUtil#getCustomClassInstance implementációja megváltozott, Class.forName helyett Thread.currentThread().getContextClassLoader().loadClass használata
* DateUtil új metódusokat kapott: `daysBetweenLocalDates` és `tryToParseAbsoluteRelativeDate`
* Hozzáadásra került az AbstractEntityProcessorAction osztály, hogy alapot nyújtson az entitások feldolgozásához (pl. Javító folyamatok)
* BaseRedisConsumerStarter kiegészítésre került threadszám ellenőrzéssel és metrika adat küldéssel CDI async eventen keresztül.
* Új abstract cache implementációk: AbstractCache és AbstractLoadingCache
* Új AbstractRedisStreamPipeConsumerExecutor és EventControlAction osztályok kerültek a redisstream modulba

==== Migration
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== Hibernate verzió emelés
Hibernate `6.2.13.Final` -> `6.6.1.Final` emelés (Wildfly 34 támogatás).

==== Migration
* https://docs.jboss.org/hibernate/orm/6.6/migration-guide/migration-guide.html[Hibernate 6.6 migration guide]
* Egyébként nem történt olyan válatoztatás coff:ee szinten, ami gátolná dependency exclude-al a korábbi hibernate verzió használatát

=== coffee-module-etcd-extension

Új Quarkus extension a coffee-module-etcd modul Quarkus natív kompatibilitás támogatásához.
Leírás: <<common_coffee-quarkus-extensions-module-etcd, coffee-module-etcd-extension>>

=== coffee-tool-extension

Új Quarkus extension a coffee-tool modul Quarkus natív kompatibilitás támogatásához.
Leírás: <<common_coffee-quarkus-extensions-tool, coffee-module-etcd-extension>>
