= v2.4.0 → v2.5.0

coff:ee v2.4.0 -> v2.5.0 migrációs leírás, újdonságok, változások leírása

=== coffee-tool

* Létrejött új "AES/CBC/PKCS5PADDING" kódoló osztály
(`hu.icellmobilsoft.coffee.tool.utils.crypto.AesCbcCryptoUtil`)
* Hozzá adva a SHA3-512 kódoló metódus a `hu.icellmobilsoft.coffee.tool.utils.string.EncodeUtil` osztályhoz,
régi `Sha512(String str)` kivezetésre fog kerülni.

==== Migration

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redisstream

* Graceful leállítást segítű működést kaptak a redis consumerek
(`hu.icellmobilsoft.coffee.module.redisstream.bootstrap.ConsumerLifeCycleManager`)

==== Migration

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* Ha nincs definiálva a version a validateXMLs annotációban, akkor nem próbálja meg kiolvasni a requestVersion a requestből.
* Átmozgatásra kerültek a `hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXML` és `hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXMLs` annotációk a coffee-dto-base modul alá.

==== Migration

A változás eredményeképpen, ha felhasználási oldalon is hivatkozva van ezen annotációkra, frissíteni kell az importokat:
`hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXML` -> `hu.icellmobilsoft.coffee.dto.annotation.validation.xml.ValidateXML`
`hu.icellmobilsoft.coffee.rest.validation.xml.annotation.ValidateXMLs` -> `hu.icellmobilsoft.coffee.dto.annotation.validation.xml.ValidateXMLs`

=== coffee-cdi

* Átmozgatásra kerültek a `hu.icellmobilsoft.coffee.cdi.annotation.Range` és `hu.icellmobilsoft.coffee.cdi.annotation.Version`  annotációk a coffee-dto-base modul alá.

==== Migration

A változás eredményeképpen, ha felhasználási oldalon is hivatkozva van ezen annotációkra, frissíteni kell az importokat:
`hu.icellmobilsoft.coffee.cdi.annotation.Range` -> `hu.icellmobilsoft.coffee.dto.annotation.Range`
`hu.icellmobilsoft.coffee.cdi.annotation.Version` -> `hu.icellmobilsoft.coffee.dto.annotation.Version`
