= v2.0.0 → v2.1.0

coff:ee v2.0.0 -> v2.1.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

Bevezetésre került a https://grpc.io/[gRPC] támogatása.
Ennek köszönhetően létrejöt új subprojekt gyűjtő `coffee-grpc` néven.

=== coffee-grpc
Következő funkció támogatások kerültek a rendszerbe:

* coffee-grpc-api - Általános gRPC kezelés Coff:ee API (annotációk, verzió, ...)
* coffee-grpc-base - protobuf és gRPC stub általános gyűjtője
* coffee-grpc-protoc - proto -> class generálás támogatása
* coffee-dto/coffee-dto-xsd2proto - Generált proto fájlok ami a `coffee-dto-xsd` XSD fájlokból vannak generálva.
* coffee-dto/coffee-dto-stub-gen - Generált osztályok a Coff:ee proto fajlokból
* coffee-grpc-server-extension - CDI gRPC szerver implementáció támogatása
* coffee-grpc-client-extension - CDI gRPC client implementáció támogatása
* coffee-grpc-traces-api - Coffee tracing API (annotációk...)
* coffee-grpc-opentracing-impl - gRPC https://github.com/eclipse/microprofile-opentracing[microprofile-opentracing] implementáció

== Változások

* Bump com.google.guava:guava https://github.com/google/guava/releases/tag/v31.1[31.1-jre]
-> https://github.com/google/guava/releases/tag/v32.1.1[32.1.1-jre]
(https://github.com/advisories/GHSA-7g45-4rm6-3mm3[CVE-2023-2976])

=== coffee-module-etcd

** Bump io.etcd:jetcd-core 0.6.1 -> 0.7.5
** `DefaultEtcdConfigImpl` több classloader esetén nem találta a microprofile-config.properties-ben felvett értékeket.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-rest

* Bevezetésre került az `OptimisticLockException`, alapértelmezetten `CoffeeFaultType.OPTIMISTIC_LOCK_EXCEPTION` hibakóddal.
* Átalakításra került a `DefaultBaseExceptionMapper` osztályban a hibakezelés:
* Üzleti hiba - BusinessException esetén 422 státuszkódot adunk az eddigi 500 státuszkód helyett.
* Technikai hiba - OptimisticLockException esetén 409 státuszkódot adunk az eddigi 500 státuszkód helyett.
* A `JsonMessageBodyReaderReaderBase` a JSON-kérés deserializálásakor a HTTP `Content-Type` fejlécben szereplő charset attribútumot használja. A fejléc helyes használata: `Content-Type: application/json; charset=utf-8`. Ha a charset nincs megadva, a deserializálás alapértelmezés szerint UTF-8-at használ!

==== Átállás

* Az eddigi exception státuszkód kezelés megtartásához a projekteken saját ExceptionMapper létrehozása szükséges.

=== coffee-module-mp-restclient

** A `DefaultBaseExceptionResponseExceptionMapper` beállítja a HTTP státusz kódot a `RestClientResponseException`-ben 

==== Átállás

* Az eddigi exception státuszkód kezelés megtartásához a projekteken saját ExceptionMapper létrehozása szükséges.

=== coffee-tool

** NPE javítás az AnnotationUtil.getAnnotation(Class<?> clazz, Class<A> annotationClass) metódusban. 

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-jpa

** NoSuchMethodException javítás a JPAUtil.toNativeSQL(NoEx) metódusban, amit a hibernate 6.x upgrade okozott. 

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== BatchService

** Már a natív insert/update metódusok is (batchMergeNative, batchInsertNative, batchUpdateNative) figyelembe veszik az insertable és updateable flag-eket.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

