= v2.10.0 → v2.11.0

coff:ee v2.10.0 -> v2.11.0 migrációs leírás, újdonságok, változások leírása

* Egy új coffee-bom-grpc modul került bevezetésre a grpc függőség verziók karbantartására
* A coffee-grpc most már buildelhető osx natív arm64 architektúrán is (lásd dokumentáció)
* ETCD driver version bump to 0.8.5
* io.grpc version bump to 1.70.0
* com.google.protobuf version bump to 3.25.5
* commons-lang3 version bump 3.12.0 -> 3.15.0 
* commons-codec version bump 1.15 -> 1.17.1
* commons.io version bump 2.11.0 -> 2.16.1
* httpcomponents-httpclient version bump 4.5.13 -> 4.5.14 
* httpcomponents-httpcore version bump 4.4.15 -> 4.4.16 
* eclipse-yasson version bump 3.0.3 -> 3.0.4

=== coffee-tool
* GZipUtil kapott néhány új metódust a kisebb memóriahasználatért, valamint DTO/JSON tömörítésre
* Hozzáadásra került egy RandomSplitGenerator osztály
* Hozzáadásra került egy abstract EvictAction osztály, hogy az Evictable interface-t implementáló osztályokat egységesen meg lehessen hívni cache törlés szempontjából.
* JsonbUtil#getCustomClassInstance implementációja megváltozott, Class.forName helyett Thread.currentThread().getContextClassLoader().loadClass használata
* DateUtil új metódusokat kapott: `daysBetweenLocalDates` és `tryToParseAbsoluteRelativeDate`
* Hozzáadásra került az AbstractEntityProcessorAction osztály, hogy alapot nyújtson az entitások feldolgozásához (pl. Javító folyamatok)
* Új abstract cache implementációk: AbstractCache és AbstractLoadingCache
* Új AbstractRedisStreamPipeConsumerExecutor és EventControlAction osztályok kerültek a redisstream modulba

==== Migration
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== Hibernate verzió emelés
Hibernate `6.2.13.Final` -> `6.6.1.Final` emelés (Wildfly 34 támogatás).

==== Migration
* https://docs.jboss.org/hibernate/orm/6.6/migration-guide/migration-guide.html[Hibernate 6.6 migration guide]
* Egyébként nem történt olyan válatoztatás coff:ee szinten, ami gátolná dependency exclude-al a korábbi hibernate verzió használatát

=== coffee-module-etcd-extension

Új Quarkus extension a coffee-module-etcd modul Quarkus natív kompatibilitás támogatásához.
Leírás: <<common_coffee-quarkus-extensions-module-etcd, coffee-module-etcd-extension>>

=== coffee-tool-extension

Új Quarkus extension a coffee-tool modul Quarkus natív kompatibilitás támogatásához.
Leírás: <<common_coffee-quarkus-extensions-tool, coffee-module-etcd-extension>>

=== coffee-module-redisstream

* BaseRedisConsumerStarter kiegészítésre került threadszám ellenőrzéssel és metrika adat küldéssel CDI async eventen keresztül.
