= v2.6.0 → v2.7.0

coff:ee v2.6.0 -> v2.7.0 migrációs leírás, újdonságok, változások leírása

== Global

=== coffee-se-api

Új modul, mely alap Coffee API-t definiál úgy mint enumok, DTO-k, kivételek, melyeknek csak Java SE függősége lehet.

Tartalma:

* `hu.icellmobilsoft.coffee.se.api.exception.BaseException` (`hu.icellmobilsoft.coffee.dto.exception.BaseException` mintájára)
* `hu.icellmobilsoft.coffee.se.api.exception.enums.Severity` (`hu.icellmobilsoft.coffee.dto.exception.enums.Severity` mintájára)
* `hu.icellmobilsoft.coffee.se.api.exception.BusinessException` (`hu.icellmobilsoft.coffee.dto.exception.BusinessException` mintájára)
* `hu.icellmobilsoft.coffee.se.api.exception.DtoConversionException` (`hu.icellmobilsoft.coffee.dto.exception.DtoConversionException` mintájára)


=== coffee-se-function

Új modul, mely a Coffee-ban használatos funkcionális interface-eket tartalmazza, melyeknek csak Java SE illetve olyan Coffee modul,
aminek szintén csak Java SE függősége lehet.

Tartalma: (`hu.icellmobilsoft.coffee.tool.common.FunctionalInterfaces` mintájára, de már az új 
`hu.icellmobilsoft.coffee.se.api.exception.BaseException`-t deklarálja)

* `hu.icellmobilsoft.coffee.se.function.BaseExceptionConsumer`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionFunction`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionFunction2`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionFunction3`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionFunction4`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionFunction5`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionFunction6`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionRunner`
* `hu.icellmobilsoft.coffee.se.function.BaseExceptionSupplier`

=== coffee-tool

* `hu.icellmobilsoft.coffee.tool.common.FunctionalInterfaces` deprecated lett. A becsomagolt funkcionális interfészek 
az új `coffee-se-function` modulban létrehozott interfészeket terjesztik ki.

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis. Azonban ha egy új funkcionális interfészt 
implementálunk, akkor már az új `hu.icellmobilsoft.coffee.se.api.exception.BaseException`-t kell lekezelni az adott helyen 
pl exception mapperek, típus vizsgálatok pl `e instanceof BaseException`, try-catch blokkok.

=== coffee-dto-base

* `hu.icellmobilsoft.coffee.dto.exception.enums.Severity` deprecated lett.
* `hu.icellmobilsoft.coffee.dto.exception.BaseException` deprecated lett.
* `hu.icellmobilsoft.coffee.dto.exception.BusinessException` deprecated lett.
* `hu.icellmobilsoft.coffee.dto.exception.DtoConversionException` deprecated lett.

==== Átállás

* `hu.icellmobilsoft.coffee.dto.exception.enums.Severity` helyett a `coffee-se-api` modulban található 
`hu.icellmobilsoft.coffee.se.api.exception.enums.Severity` használandó.
* deprecated Exceptionok helyett a `hu.icellmobilsoft.coffee.se.api.exception.*`
packagebe kerültek a pótlások (pl. `hu.icellmobilsoft.coffee.dto.exception.BaseException` helyett az ősosztálya a
`hu.icellmobilsoft.coffee.se.api.exception.BaseException` használandó).
** Az eredeti `getSeverity()` fgv már az új típussal a `hu.icellmobilsoft.coffee.se.api.exception.enums.Severity`-vel tér 
vissza. Az eretei típus eléréséhez használjuk a `getOldSeverity()` fgv-t.

=== coffee-cdi

💥 ***BREAKING CHANGE*** 💥

* `hu.icellmobilsoft.coffee.cdi.trace.spi.ITraceHandler` változások:
** A `runWithTrace()` fgv átnevezésre került `runWithTraceNoException()`-re ami paraméterül `java.util.function.Supplier`-t 
vagy `java.lang.Runnable`-t vár. Az így trace-elt fgv-ek csak RTE-t dobhatnak.
** Az eredeti `runWithTrace()` fgv mostantól `java.util.function.Supplier` helyett 
`hu.icellmobilsoft.coffee.se.function.BaseExceptionSupplier` vagy `hu.icellmobilsoft.coffee.se.function.BaseExceptionRunner` 
fgv-t vár, amik dobhatnak `hu.icellmobilsoft.coffee.se.api.exception.BaseException`-t.

==== Átállás

* Az eredeti `ITraceHandler.runWithTrace()` hívásoknál le kell kezelni vagy tovább kell dobn a 
`hu.icellmobilsoft.coffee.se.api.exception.BaseException`-t.
* Ha olyan fgv-t trace-elünk, ami csak RTE-t dobhat, akkor használjuk a `runWithTraceNoException()` fgv-t.

=== coffee-rest

* `hu.icellmobilsoft.coffee.rest.exception` package-ben található `DefaultBaseExceptionMapper`,
`DefaultExceptionMessageTranslator`, `DefaultGeneralExceptionMapper` és `IExceptionMessageTranslator` osztályok már 
az új `hu.icellmobilsoft.coffee.se.api.exception.BaseException`-el dolgoznak.

==== Átállás

* A `jakarta.ws.rs.ext.ExceptionMapper` és `hu.icellmobilsoft.coffee.rest.exception.IExceptionMessageTranslator` 
implementációkban álljunk át az új `hu.icellmobilsoft.coffee.se.api.exception.BaseException`-re.

=== coffee-grpc

* Új `hu.icellmobilsoft.coffee.grpc.base.converter.ProtoConverter` interface,
ami anyDto <--> protoDto konverziót támogatja
* Új util osztály a proto dátum konverziók támogatására
(`hu.icellmobilsoft.coffee.grpc.base.util.ProtoDateUtil`)

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module-redis

* Jedis driver verzió upgrade 4.2.3 -> 5.1.2

[IMPORTANT]
====
Az újabb kliens a redist 6.0 verziótól támogatja!

====

==== Átállás

A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== coffee-module

* A `@ConfigDoc` annotáció kibővült két új paraméterrel(opcionálisak), `isStartupParam` illetve `isRuntimeOverridable`.
A generált táblázatban egy új oszlop, `Features` alá jönnek az értékeik egy-egy emotikonnal reprezentálva ha true-ra vannak állítva(default false).
** `isStartupParam` true esetén az emotikon: 🚀
** `isRuntimeOverridable` true esetén az emotikon: ⏳
* A `@ConfigDoc` annotáció kibővült egy új paraméterrel(opcionális), `title`.
A generált táblázatok alapértelmezett címét lehet felülírni ennek a megadásával.

==== Átállás

* A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis, viszont mostmár megadható ez a három paraméter a `@ConfigDoc` annotációban.

=======