[#common_module_coffee-module-mongodb]
= coffee-module-mongodb

A modul célja a MongoDB NOSQL adatbázis kezelésének támogatása, amihez különböző kiszolgáló osztályokat és metódusokat tartalmaz.
CDI extension kiterjesztésen alapszik http://cdi-spec.org/[cdi-spec]. 


== Implementálás a projektbe

.Coffee modul aktiválás
=== pom.xml
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mongodb</artifactId>
</dependency>
----


=== Konfiguráció yml-ben:
.project-defaults.yml
[source,yaml]
----
coffee:
    mongodb:
        xmlapi: #<1>
             database: xmlapi
             uri: mongodb://sample_xmlapi:sample_xmlapi@sample-sandbox.icellmobilsoft.hu:27017/sample_xmlapi?ssl=false
             connectionsPerHost: 150 #default: 100
             minConnectionsPerHost: 1 #default: 1
             connectTimeout: 10000 #default: 10000
             serverSelectionTimeout: 5000 #default: 5000
             socketTimeout: 0 #default: 0
             maxConnectionIdleTime: 20000 #default: 20000
             maxConnectionLifeTime: 20000 #default: 20000
             heartbeatFrequency: 500 #default: 500
             minHeartbeatFrequency: 500 #default: 500
        tada:
            database: tada
            uri: mongodb://sample_tada:sample_tada@sample-sandbox.icellmobilsoft.hu:27017
            connectionsPerHost: 400 #default: 150
----
<1> A mongoDB kapcsolat egyedi azonosítója (configKey). "database" és "uri" megadása kötelező. A többi default értékkel rendelkezik.
Paraméterek részletes leírása MongoConfigHelper osztályban található.

Több monogDB szerverhez is lehet megadni paramétereket. A configKey egyedisége határozza meg az adatbázist. 

=== Használat

==== @MongoClientConfiguration annotáció
Ez az annotáció lehetővé teszi hogy MongoDbClient objektumot injektáljunk. Ezen keresztül elérhető a MongoDB.
[source,java]
----
@Inject
@MongoClientConfiguration(configKey = "xmlapi") #<1>
private MongoDbClient mongoDbClient;
----
<1> A yml-ben meghatározott configKey érték. Egyedi azonosító.

A coff:ee mongoDB modulja le fogja gyártani a MongoDbClient objektumot, a yml-ben megadott értékeket alapul véve.
A használni kívánt collection-t külön kell megadnunk.
Ez a default MongoService implementáció ami BasicDBObject típussal képes dolgozni.

.Service használata 
[source,java]
----
// collection megadása
mongoDbClient.initRepositoryCollection("xmlapi_collection");

// a MongoUtil-ok segítéségével lehet a típusos objektumokat kezelni
String dtoJson = MongoJsonUtil.toJson(dtoDocumentType);
BasicDBObject dtoDocument = MongoUtil.jsonToBasicDbObject(dtoJson);

// az elem beszúrása
mongoDbClient.insertOne(dtoDocument);

// a beszúrt elem id-jának lekérdezése
String id = dtoDocument.getString(MongoConstants.COLUMN_MONGO_ID);

// keresés filter-el
BasicDBObject filter = new BasicDBObject();
filter.put(MongoConstants.COLUMN_MONGO_ID, new ObjectId(mongoId));
BasicDBObject result = mongoDbClient.findFirst(filter);

// keresés id-vel
BasicDBObject result = mongoDbClient.findById(mongoId);
----

==== @MongoServiceConfiguration annotáció
Ezt az annotációt aknázza ki a CDI extension, minden osztályhoz ami kiterjeszti a MongoService<T> osztályt, automatikusan legenerálódik
egy @Producer ami lehetővé teszi az inject-álást.

.Service használata 
[source,java]
----
/**
 * MongoService kiterjesztése, POJO megadásával
 */
@Dependent
public class CustomMongoService extends MongoService<MongoEntity> {
    //nem szükséges semmit felülírni
}

/**
 * Az extension a configKey és collectionKey paraméterek alapján injectálja a CustomMongoService-t
 */
@Inject
@MongoServiceConfiguration(configKey = "xmlapi", collectionKey = "xmlapi_collection")
private CustomMongoService customMongoService;
----
A CustomMongoService őse a MongoService<T>, ami miatt az extension feldolgozza, és a generikus paramétert figyelembe véve beállítja a háttérben
az objektumot (MongoEntity) amivel dolgozik a CustomMongoService. Az ősben lévő műveletek felülírhatóak. A CustomMongoService scope értéke is felülírható ha nem lenne megfelelő a @Dependent.
@Stateless EJB-ből használva nem működik a @Model scope, az csak a Rest interfaceken alkalmazható, ahol a http hívás végén megszűnnek az inject-ált MongoService példányok. 

Használat során nem szükséges a collection-t megadni, mivel az annotációban ez megtörténik. Bármelyik MongoService használhat bármilyen collection-t, nincs megkötés.
[source,java]
----
// lekérdezés
MongoEntity entity = customMongoService.findById("mongoId");

// beszúrás
MongoEntity mongoEntity = new MongoEntity();
customMongoService.insertOne(mongoEntity);
----
