[#common_module_coffee-module-redis]
= coffee-module-redis

Modul célja Redis online key-value kezelése.

A "redis.clients:jedis" java driver alapon működő modul nemcsak a Redisből való lekérdezéseket és mentéseket szolgálja ki, de tud nyújtani egy Redisben mentett cache kezelést is, ami a CDI interceptor alapjain működik.

== RedisConnection

Bevezetésre került a `@RedisConnection` qualifier.
Ennek használatával nincs szükség Redis kapcsolatonként külön definiálni/implementálni a Redis konfigurációt, JedisPool-t, Jedis-t, RedisService -t; CDI-on keresztül mindegyik legyártásra kerül és injectelhetó.
Konfiguráció yaml-ben:

[source,yaml]
----
coffee:
    redis:
        auth: #<1>
            host: sample-sandbox.icellmobilsoft.hu #default: localhost
            port: 6380 #default: 6380
            password: pass1234 #default: null
            database: 1 #default: 1
            pool:
                maxtotal: 128 #default: 64
                maxidle: 32 #default: 64
            timeout: 5000 #default: 5000
----
<1> A redis kapcsolat egyedi azonosítója (configKey). Minden mező opcionális.

A fenti konfig-hoz tartozó RedisService használata:

[source,java]
----
@Inject
@RedisConnection(configKey = "auth")
private RedisService authRedisService;
----

== Redis műveletek

=== hscen

Végigiterál a kiválasztott redis db-ben lévő objektumon kulcs alapján. A művelet közben változhat az adat, nem blokkol (ez az előny az SMEMBERS művelettel szemben).
Arra nincs garancia hogy minden elemet visszaad, a redisben tárolt objektumok méretétől függ.
Ha meghaladja a limitet akkor a default COUNT értéke 10 lesz, ennél több elemet nem fog visszaadni egy kérésben.
Lehetőség van paraméterezni a COUNT értékét, ha meghaladnánk a méret korlátot.
Bővebb leírás a korlátokról: https://redis.io/commands/scan

[source,java]
----
authRedisService.hscanRedisData("key", 10, 100);
----
