[#common_module_coffee-module-mongodb]
= coffee-module-mongodb

A modul célja a MongoDB NOSQL adatbázis kezelésének támogatása, amihez különböző kiszolgáló osztályokat és metódusokat tartalmaz.
CDI extension kiterjesztésen alapszik http://cdi-spec.org/[cdi-spec]. 

== CDI Extension készítés
Extension készítéshez implementálni kell a `Extension` interface-t, ami a Java SE service provider architektúrában van definiálva.
A CDI 2.0 specifikáció szerint: *javax.enterprise.inject.spi.Extension*

.Extension
[source,xml]
----
// Extension-t kezelő osztályunk
public class MongoExtension implements javax.enterprise.inject.spi.Extension {
}
----
Létre kell hozni a `META-INF/services/jakarta.enterprise.inject.spi.Extension` nevű file-t,
amiben megadjuk a saját osztályunk-at ami implementálja az interface-t: *hu.icellmobilsoft.coffee.module.mongodb.extension.MongoExtension*

A `MongoExtension` osztályban a CDI konténer által meghatározott eseményeket tudjuk elkapni és módosítani az osztályok működését.
A teljes lista itt található: https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html[JSR 365].

Két fő csoportba lehet az eseményeket sorolni:
 
* Application lifecycle events: egyszer hívódnak meg
* Bean discovery events: többször hívódnak meg

Ezekből az *afterBeanDiscovery* (Application lifecycle) és a *processInjectionTarget* (Bean discovery) event-et fogjuk feldolgozni.

.processInjectionTarget event
[source,xml]
----
// lehetőséget ad hogy a CDI konténer által felolvasott típusokat ellenőrízzük
// ebben valósul meg a MongoService<T> osztályt implementáló osztályok összegyűjtése
public <T> void processInjectionTarget(final @Observes ProcessInjectionTarget<T> pit) {
}
----

.afterBeanDiscovery event
[source,xml]
----
// amikor a CDI konténer inicializált minden Bean-t akkor ezen a ponton még tudunk módosítani az osztályokon
// itt kerülnek legyártásra azok a Producerek amik a MongoService-t kiterjesztő osztályokat inject-álhatóvá teszik
public void afterBeanDiscovery(@Observes final AfterBeanDiscovery abd, BeanManager beanManager) {
}
----

A producerek létrehozásához a `MongoServiceProducerFactory` osztály készült.
Tartalmaz egy mongoServiceTemplateProducer metódust amit a MongoExtension alapul vesz, ez adja a templatet a producerek gyártásához.


=== MongoDbClientFactory
`MongoDbClient` legyártása a feladata. yml-ben megadott configKey alapján legyártja és benne
inicializálja a `com.mongodb.client.MongoClient` osztályt és `com.mongodb.client.MongoDatabase` interface-t,
ezzel kommunikálunk a MongoDb-vel. Ezen a ponton használjuk fel a yml-ben definiált paramétereket, a configKey használatával.

.produceMongoDbClient producer
[source,xml]
----
@Produces
@MongoClientConfiguration(configKey = "")
@Dependent
public MongoDbClient produceMongoDbClient(InjectionPoint injectionPoint) throws BaseException {
----
=== MongoDbClient
Tartalmazza a `com.mongodb.client.MongoDatabase` osztályt ami már a kiválasztott Mongo adatbázist tudja kezelni.
Tartalmaz alap funkciókat, ha nem POJO mongo entitásokkal szeretnénk dolgozni. Delegálja a műveleteket
a MongoService<BasicDBObject> felé.

=== MongoServiceProducerFactory
A producerek gyártásához definiál template metódust. A template metódus belül a `MongoDbClient` osztályt kéri el a CDI konténertől, 
igy generikus a működés és felhasználjuk a már létrehozott `MongoDbClientFactory` működését. Az annotációból érkező collectionKey értékével,
miután inicializálta a `MongoDbClient`-et, beállítja a használandó Mongo collection-t.
Ezután elkészíti a projektben definiált MongoService-t kiterjesztő osztályt a generikus paraméterben megadott MongoEntity típussal.

.mongoServiceTemplateProducer template metódus
[source,xml]
----
// producer template
@MongoServiceConfiguration(configKey = "", collectionKey = "")
public <T> MongoService<T> mongoServiceTemplateProducer(final InjectionPoint injectionPoint) {
----


== Implementálás a projektbe

.Coffee modul aktiválás
=== pom.xml
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.coffee</groupId>
    <artifactId>coffee-module-mongodb</artifactId>
</dependency>
----


=== Konfiguráció yml-ben:
.project-defaults.yml
[source,yaml]
----
coffee:
    mongo:
        xmlapi: #<1>
             database: icon_xmlapi
             uri: mongodb://sample_xmlapi:sample_xmlapi@sample-sandbox.icellmobilsoft.hu:27017/sample_xmlapi?ssl=false
             connectionsPerHost: 150 #default: 100
             minConnectionsPerHost: 1 #default: 1
             connectTimeout: 10000 #default: 10000
             serverSelectionTimeout: 5000 #default: 5000
             socketTimeout: 0 #default: 0
             maxConnectionIdleTime: 20000 #default: 20000
             maxConnectionLifeTime: 20000 #default: 20000
             heartbeatConnectTimeout: 20000 #default: 20000
             heartbeatFrequency: 500 #default: 500
             heartbeatSocketTimeout: 20000 #default: 20000
             minHeartbeatFrequency: 500 #default: 500
        tada:
            database: nejp_tada
            uri: mongodb://sample_tada:sample_tada@sample-sandbox.icellmobilsoft.hu:27017
            connectionsPerHost: 400 #default: 150
----
<1> A mongoDB kapcsolat egyedi azonosítója (configKey). "database" és "uri" megadása kötelező. A többi default értékkel rendelkezik.
Paraméterek részletes leírása MongoConfigHelper osztályban található.

Több monogDB szerverhez is lehet megadni paramétereket. A configKey egyedisége határozza meg az adatbázist. 

=== Használat

==== @MongoClientConfiguration annotáció
Ez az annotáció lehetővé teszi hogy MongoDbClient objektumot injektáljunk. Ezen keresztül elérhető a MongoDB.
[source,java]
----
@Inject
@MongoClientConfiguration(configKey = "xmlapi") #<1>
private MongoDbClient mongoDbClient;
----
<1> A yml-ben meghatározott configKey érték. Egyedi azonosító.

A coff:ee mongoDB modulja le fogja gyártani a MongoDbClient objektumot, a yml-ben megadott értékeket alapul véve.
A használni kívánt collection-t külön kell megadnunk.
Ez a default MongoService implementáció ami BasicDBObject típussal képes dolgozni.

.Service használata 
[source,java]
----
// collection megadása
mongoDbClient.initRepositoryCollection("xmlapi_collection");

// a MongoUtil-ok segítéségével lehet a típusos objektumokat kezelni
String dtoJson = MongoJsonUtil.toJson(dtoDocumentType);
BasicDBObject dtoDocument = MongoUtil.jsonToBasicDbObject(dtoJson);

// az elem beszúrása
mongoDbClient.insertOne(dtoDocument);

// a beszúrt elem id-jának lekérdezése
String id = dtoDocument.getString(MongoConstants.COLUMN_MONGO_ID);

// keresés filter-el
BasicDBObject filter = new BasicDBObject();
filter.put(MongoConstants.COLUMN_MONGO_ID, new ObjectId(mongoId));
BasicDBObject result = mongoDbClient.findFirst(filter);

// keresés id-vel
BasicDBObject result = mongoDbClient.findById(mongoId);
----

==== @MongoServiceConfiguration annotáció
Ezt az annotációt aknázza ki a CDI extension, minden osztályhoz ami kiterjeszti a MongoService<T> osztályt, automatikusan legenerálódik
egy @Producer ami lehetővé teszi az inject-álást.

.Service használata 
[source,java]
----
/**
 * MongoService kiterjesztése, POJO megadásával
 */
@Dependent
public class CustomMongoService extends MongoService<MongoEntity> {
    //nem szükséges semmit felülírni
}

/**
 * Az extension a configKey és collectionKey paraméterek alapján injectálja a CustomMongoService-t
 */
@Inject
@MongoServiceConfiguration(configKey = "xmlapi", collectionKey = "xmlapi_collection")
private CustomMongoService customMongoService;
----
A CustomMongoService őse a MongoService<T>, ami miatt az extension feldolgozza, és a generikus paramétert figyelembe véve beállítja a háttérben
az objektumot (MongoEntity) amivel dolgozik a CustomMongoService. Az ősben lévő műveletek felülírhatóak. A CustomMongoService scope értéke is felülírható ha nem lenne megfelelő a @Dependent.
@Stateless EJB-ből használva nem működik a @Model scope, az csak a Rest interfaceken alkalmazható, ahol a http hívás végén megszűnnek az inject-ált MongoService példányok. 

Használat során nem szükséges a collection-t megadni, mivel az annotációban ez megtörténik. Bármelyik MongoService használhat bármilyen collection-t, nincs megkötés.
[source,java]
----
// lekérdezés
MongoEntity entity = customMongoService.findById("mongoId");

// beszúrás
MongoEntity mongoEntity = new MongoEntity();
customMongoService.insertOne(mongoEntity);
----
