[#common_module_coffee-module-etcd]
= coffee-module-etcd

Modul célja az ETCD kezelése. Működése a hivatalos 

.maven
[source,xml]
----
<dependency>
    <groupId>io.etcd</groupId>
    <artifactId>jetcd-core</artifactId>
    <version>0.5.0</version>
</dependency>
----
driveren alapszik, kiterjesztve céges használati modell lehetőségekkel. Pontosabb leírás külön oldalon található

NOTE: ETCD kezelése bővebben: <<howto_etcd,ETCD>>

Röviden összefoglalva az ETCD-ben szereplő kulcs-érték párosok a microprofile-config-en keresztül eléhetőek, de más lehetőségek is léteznek, ajánlottak a következőek

.ETCD key-value
[source,java]
----
// 1. ConfigurationHelper használata (ajánlott request scope cache végett)
@Inject
private ConfigurationHelper configurationHelper;
...
Integer ttl = configurationHelper.getInteger("public.login.session.token.validity");
 
 
// 2. ApplicationConfiguration használata (ajánlott application scope cache végett)
@Inject
private ApplicationConfiguration applicationConfiguration;
...
String minVersion = applicationConfiguration.getString(EtcdVal.KEY_PUBLIC_INVOICE_MIN_REQUEST_VERSION);
----

== Loggolás
A lekérdezett kulcsok és a kapott értékek logolásra kerülnek, kivéve ha a kulcs megfelel a `.+++*+++?(pass|secret).+++*+++?` reguláris kifejezésnek, ez esetben az érték maszkolva lesz kilogolva.
Az alapértelmezett regex felülírható, ha valamelyik *alapértelmezett* microprofile-config forrásban (sys var, env var, META-INF/microprofile-config.properties) megadjuk a `coffee.config.log.sensitive.key.pattern` konfigot.