[#common_module_coffee-module-redis]
= coffee-module-redis

Modul célja Redis online key-value kezelése.

A "redis.clients:jedis" java driver alapon működő modul nemcsak a Redisből való lekérdezéseket és mentéseket szolgálja ki, de tud nyújtani egy Redisben mentett cache kezelést is, ami a CDI interceptor alapjain működik.

== RedisConnection

Bevezetésre került a `@RedisConnection` qualifier.
Ennek használatával nincs szükség Redis kapcsolatonként külön definiálni/implementálni a Redis konfigurációt, JedisPool-t, Jedis-t, RedisService -t; CDI-on keresztül mindegyik legyártásra kerül és injectelhetó.
Konfiguráció yaml-ben:

[source,yaml]
----
coffee:
    redis:
        auth: #<1>
            host: sample-sandbox.icellmobilsoft.hu #default: localhost
            port: 6380 #default: 6380
            password: pass1234 #default: null
            database: 1 #default: 1
            pool:
                maxtotal: 128 #default: 64
                maxidle: 32 #default: 64
            timeout: 5000 #default: 5000
----
<1> A redis kapcsolat egyedi azonosítója (configKey). Minden mező opcionális.

A fenti konfig-hoz tartozó RedisService használata:

[source,java]
----
@Inject
@RedisConnection(configKey = "auth")
private RedisService authRedisService;
----

== Redis műveletek

=== hscan

Végigiterál a kiválasztott redis db-ben lévő objektumon kulcs alapján. A művelet közben változhat az adat, nem blokkol (ez az előny az SMEMBERS művelettel szemben).
Arra nincs garancia hogy minden elemet visszaad, a redisben tárolt objektumok méretétől függ.
Ha meghaladja a limitet akkor a default COUNT értéke 10 lesz, ennél több elemet nem fog visszaadni egy kérésben.
Lehetőség van paraméterezni a COUNT értékét, ha meghaladnánk a méret korlátot.
Bővebb leírás a korlátokról: https://redis.io/commands/scan

[source,java]
----
redisService.hscanRedisData("key", 10, 100);
----

=== rpush

A kulcs-ként megadott listába pakolja az értéket
és beállítja a lista lejárati értékét másodpercben.
Válaszban a listában lévő tételek mennyisége.
Bővebb leírás: https://redis.io/commands/rpush + https://redis.io/commands/expire

[source,java]
----
redisService.rpushRedisData("key", "element", 100);
----

=== lpop/rpop

(coffee v1.4+)
A kulcs-ként megadott listából kiszedi és válaszolja az első (lpop) vagy utolsó (rpop) értéket a sorból.
Ha már üres a lista a Redis automatán törli azt.
Ha nem létező listából (közben kiürült és a Redis törölte) kérjük az adatot a rendszer `BONotFoundException` hibát fog dobni,
vagy `Optional.empty()`-t.
Bővebb leírás a korlátokról: https://redis.io/commands/lpop

[source,java]
----
redisService.lpopRedisData("key"); <1>
redisService.lpopRedisDataOpt("key"); <2>

redisService.rpopRedisData("key"); <1>
redisService.rpopRedisDataOpt("key"); <2>
----
<1> Ha nem talál értéket akkor `BONotFoundException` 
<2> Ha nem talál értéket akkor `Optional.empty()`
