<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hu.icellmobilsoft.coffee</groupId>
        <artifactId>coffee-module-docgen</artifactId>
        <version>2.14.0-SNAPSHOT</version>
    </parent>

    <artifactId>coffee-module-docgen-sqlcatalog</artifactId>

    <name>Coff:ee Module - Docgen - SQL Catalog</name>

    <properties>
        <version.google.auto-service>1.0.1</version.google.auto-service>
    </properties>

    <dependencies>
        <dependency>
            <groupId>hu.icellmobilsoft.coffee</groupId>
            <artifactId>coffee-module-docgen-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>${version.google.auto-service}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>hu.icellmobilsoft.coffee</groupId>
            <artifactId>coffee-deltaspike-data</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>hu.icellmobilsoft.coffee</groupId>
            <artifactId>coffee-deltaspike-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.auto.service</groupId>
                            <artifactId>auto-service</artifactId>
                            <version>${version.google.auto-service}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
                <executions>
                    <execution>
                        <id>default-testCompile</id>
                        <configuration>
                            <annotationProcessorPaths>
                                <!-- Only for tests -->
                                <path>
                                    <groupId>${project.groupId}</groupId>
                                    <artifactId>${project.artifactId}</artifactId>
                                    <version>${project.version}</version>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
